### ISSUE TITLE
Snapshot redesign

### ISSUE THREAD

**Issue by LegendreM** [meilisearch/MeiliSearch#1009]
# Summary

Snapshots design could have some improvements in CLI options and in error messages 

# CLI

1) Add a boolean option to activate or deactivate snapshot scheduling instead of using `--snapshot-path` as defined:
`--schedule-snapshot` 

2) rename `--load-from-snapshot` to `--import-snapshot` to be consistent with dumps

3) rename `--snapshot-path` to `--snapshot-dir` to be consistent with dumps (related to #988)

# error message

add a tips on error message `"database already exists at data.ms"`:
`"database already exists at data.ms, try to delete it or rename it"`

# Related

- [ ] Validated by the team
  - [ ]  @bidoubiwa
  - [ ] @MarinPostma 
- [ ] [Documentation](https://github.com/meilisearch/documentation/pull/552)

**Comment by bidoubiwa** [comment]
Just to be sure, `--schedule-snapshot` will need an additional boolean to make it work?

```bash
meilisearch --schedule-snapshot true
```

**Comment by MarinPostma** [comment]
There ares some things I don't understand:
- What do  `--schedule-snapshot` on it's own do? Does it trigger snapshoting with default values for `dir` and `interval`? What are those values? These should be reported in the doc **and in the CLI** help command.
- > Just to be sure, --schedule-snapshot will need an additional boolean to make it work?
I have a feeling that this will be necessary, this is a (poor) design choice clap made, and that we have to stick with for now. Not sure that the conditions are met though, It would be interesting to check.

**Comment by MarinPostma** [comment]
> meilisearch --snapshot-dir custom/path --snapshot-interval-sec 2345
no snapshot would be created, it would just override default values

this is useless, or am i missing something?

**Comment by LegendreM** [comment]
yes it is but lets say you are an env_var guy, yo would set up:
MEILI_SNAPSHOT_DIR=custom/path

and be able to choose to schedule snapshots or not without having to remove and probably forget the variable saying where are stored snapshots

**Comment by LegendreM** [comment]
@MarinPostma @curquiza @bidoubiwa are we agree about this ?

**Comment by bidoubiwa** [comment]
I realize I have a few concern about the error message:

### Absolute or relative db path

>"database already exists at data.ms":
"database already exists at data.ms, try to delete it or rename it"

What happens if I used the following flag 
```bash
./meilisearch --import-snapshot ../dir1/dir2 --db-path ../dir1/dir2/
```
Does the error message becomes or does it gives the absolute path ot it ?
* `database already exists at ../dir1/dir2/data.ms, try to delete it or rename it` => relative
* `database already exists at Users/me/dir1/dir2/data.ms, try to delete it or rename it` => absolute

In the relative case, could we consider the following if the data.ms is at the root of the binary `./data.ms`

### Error rewording

`A database was found at the following path: ./data.ms, try to delete it, rename it, or change its path using --db-path`

### Global CLI

Also what happens if we launch MeiliSearch using brew for example, where it becomes a global CLI? What would the link to the database look like?

**Comment by LegendreM** [comment]
Hey @bidoubiwa here is the actual message:
`Error: database already exists at "./data.ms", try to delete it or rename it`

**Comment by bidoubiwa** [comment]
The absolute path would ask for fewer changes the day we have a global CLI but the relative path works for me as of today.
So it's up to you or someone who really wants the relative. I think absolute is best but both are okey.
