### ISSUE TITLE
Synonyms are Case-Sensitive

### ISSUE THREAD

**Issue by CameronSumpter** [meilisearch/MeiliSearch#1048]
**Describe the Bug**
Synonyms only work when passed to the Settings API as all-lowercase strings without accents.

**To Reproduce**
Add a document with the word 'Catalonia' appearing in a searched attribute and apply the following synonym configuration:
`['Cataluña' => ['Catalonia'], 'Cathalaunia' => ['Catalonia']]`

**Expected Behavior**
Queries for `Cataluña`, `Cataluna`, and `Cathalaunia` should return the document. This only works if all four strings are lowercase and contain no accented characters, i.e.:
`['cataluna' => ['catalonia'], 'cathalaunia' => ['catalonia']]`

**Additional Context**
Tested using v0.15.0.

**Comment by MarinPostma** [comment]
Hello @CameronSumpter, we are well aware of this, and we tried to address this in #964. We had to reconsider this because unicasing and de-unicoding is not always desirable, for example, for languages that do not use the Latin script. This will be solved in the future by the ongoing work we're doing on the tokenizer, but until then, you should pass `all-lowercase strings without accents` to achieve the desired behaviour.

**Comment by CameronSumpter** [comment]
Thanks for the clarification, @MarinPostma. That's perfectly understandable; I think mentioning it in the documentation will set proper expectations and save others a bit of time!

**Comment by MarinPostma** [comment]
linking to #964
