### ISSUE TITLE
Feature request: similarity search

### ISSUE THREAD

**Issue by autresrhumbs** [meilisearch/MeiliSearch#1070]
It would be nice to have a "similarity" search, where you would provide ID of a document and MeiliSearch will return a list of similar documents, which match the most.

**Comment by qdequele** [comment]
Hello, Thanks for this feature proposal! 

I will close this issue in favor of our [public roadmap](https://roadmap.meilisearch.com/c/63-get-similar-documents?utm_medium=social&utm_source=portal_share). 

I invite everyone interested in this feature to update it on the roadmap.

**Comment by pixelkoduje** [comment]
It's been two years and this still hasn't been implemented? och :/

**Comment by Kerollmops** [comment]
Hey @pixelkoduje,
I see you gave your insight on getting similar documents on our roadmap websote, but could you explain your use-case and if you need a specific implementation?
Thank you very much!

**Comment by KULTI1995** [comment]
@Kerollmops 

I will be applying to a large ecommerce/price comparison platform for millions of products.

So I need to get a similar product, in terms of attributes probably.
So that the result for umbrellas is other umbrellas. and for red trekking shoes other red trekking shoes.
I would do it, for example, on the principle of a vector and how far the product is, or how close to another product.
(I'm not talking about similar products, as for shoes suggesting shoe polish - but different shoes)

**Comment by KULTI1995** [comment]
@Kerollmops Let me mention this thread. If you can get this started with the crew, I'd appreciate it.

https://github.com/meilisearch/instant-meilisearch/issues/1014

**Comment by pixelkoduje** [comment]
@Kerollmops 

I have an attribute object that is also for faceting.
And in it is, on the example of shoes:
color: ["red"],
season: ["winter"]
type: ["trekking"]
brand: ["adidas"]
Based on that, having a vector and comparing to another, I'll get a perfect match of shoes that will be almost identical.

The most beautiful would be the way of setting, as it is done in meilisearch. e.g.
similar: {
vectorizeFields: ["attributes.*"]
excludeVectorizeFields: ["attributes.type"]
}

And then you can ask for id - and on this basis return the rest of the similar ones.
e.g. meilisearch.similar(id, {other_params*})

other_params - e.g. pages, perPage, limit, etc.

**Comment by Kerollmops** [comment]
Hey @pixelkoduje and @KULTI1995,

First question: Are you working together? 😄

@pixelkoduje do you think that any similarity search algorithm would work? What you seem to describe is to search for the subset of documents that have the most categories i.e. `filterableAttributes` in common with the document you input? Wouldn't a BM25/TF-IDF work?

Can it be a basic route like `GET /indexes/products/similar-to/345` where `345` is the id of the document you want to search for similar products?

> Let me mention this thread. If you can get this started with the crew, I'd appreciate it.

@KULTI1995 I don't know if that's very hard to implement, but you can give it a try and start an implementation maybe? As you mentioned it: _There are all the things that make it work_.

**Comment by pixelkoduje** [comment]
1. Can it be a basic route like GET /indexes/products/similar-to/345 where 345 is the id of the document you want to search for similar products?

Exactly what I am talking about.

If I were to create a meilisearch to use in a project, I would finish it in 2024. No offense.

Anyway, you can see how much demand there is in the community for this topic. And if I am to sign meilisearch with my huge eccomerce project with a comparison engine, the function you are talking about above would have to be implemented.

**Comment by Kerollmops** [comment]
Ah> If I were to create a meilisearch to use in a project, I would finish it in 2024. No offense.

Do you mean that the Meilisearch team is too slow and should have implemented the features you want long ago?

We prioritize features based on user feedback and the similarity route you are talking about has been prioritize already.

Could you please confirm that @KULTI1995 and @pixelkoduje are the same person or are associated to the same company or group of person?

**Comment by pixelkoduje** [comment]
@Kerollmops 

No, of course not. I was talking about myself. If I had to add meilisearch functionalities and implement the project at the same time. :)

However, the thread of similar things has been open for 2 years and has a hundred followers. Too bad you didn't give it top priority. Because meilisearch will be suitable for easy solutions, but not for larger projects. And it seems to me that it was just created for larger projects and ultra-fast searching. I love the speed of meilisearch - it is number one among open source projects in terms of speed. Typesense is just as fast, but meilisearch is much better at handling heavier queries. Eg when the project has hundreds of filterable attributes and it has to return facets.

Missing in my opinion:
- instantsearch meilisearch - DynamicWidget(it doesn't work and meilisearch returns all facets)
- There is no guy search, in instantsearch.(refinementlist)
- search for similar items is not implemented.
- In instantsearch refinenentlist I don't show show more (even though the api returns more values in facets)

On these fields, typesense beats meilisearch, which is a pity - because meilisearch is faster.

**Comment by Kerollmops** [comment]
Could you please confirm that @KULTI1995 and @pixelkoduje are the same person or are associated to the same company or group of person?

**Comment by pixelkoduje** [comment]
Maybe you misunderstood me. I think meilisearch is great and you guys are doing a lot for the community. :) Could you tell me if and when similar things are planned? So that I can check if I am able to use meilisearch or if I need to change the software.

I don't understand the kinship question. What does that mean in context? This is my account, which sometimes happens I log in on different browsers and send a message by mistake. It doesn't matter in the context of the conversation.

**Comment by pixelkoduje** [comment]
If I answered your questions, could you answer mine? @Kerollmops

**Comment by Kerollmops** [comment]
> There is no guy search, in instantsearch.(refinementlist)

What is a guy search? Do you have a link or something?

> In instantsearch refinenentlist I don't show show more (even though the api returns more values in facets)

What do you precisely need? Do you need to search in the facets or something similar?

> Could you tell me if and when similar things are planned?

It depends on the number of people asking for this feature. Not a lot of demand, but it could change in the future. We have planned to experiment with vector/semantic search so, maybe one day.

**Comment by pixelkoduje** [comment]
And query suggestions? There are already 100 people, and you don't even plan on it. And that's not on the list since yesterday either.

**Comment by pixelkoduje** [comment]
You could have written to me many times that sometime in a year you would think about it. Then we wouldn't be having this conversation.

**Comment by Kerollmops** [comment]
Could you answer the few questions I asked above? I need help understanding this peak of aggressivity.

> And query suggestions? There are already 100 people, and you don't even plan on it.

Query suggestions can be implemented by creating another index with only the main fields you want to auto-suggest. If you want to improve it, you can insert the previous user queries in this index too!

I don't know if you are aware of [our public roadmap website](https://roadmap.meilisearch.com/tabs/5-ideas), but we consider query suggestions.

> You could have written to me many times that sometime in a year you would think about it. Then we wouldn't be having this conversation.

I don't understand what you are saying. Could you be more clear, please?

**Comment by adaboese** [comment]
Maybe a good idea to hide these off-topic conversations.

**Comment by guacs** [comment]
@Kerollmops I would like this feature as well. Let me explain my specific use case. I have a bunch of questions (previous year questions of certain exams) that users can search in order to practice a specific topic or something. I would like to provide them a way to be able to find the similar questions to a specific question. Currently, I have to query my database to get the question, then combine the different parts of the question (such as the question and the answers in the case of multiple-choice questions) into one string and then use that as the query. This seems like a waste when meillisearch already has all the required data.

Tantivy has a feature like this as seen [here](https://docs.rs/tantivy/latest/tantivy/query/struct.MoreLikeThisQuery.html). It uses TF-IDF I think. It'd be great if meillisearch could use BM25, but for my use case TF-IDF works great as well since similar questions tend to have a lot of the same keywords.
