### ISSUE TITLE
Introduce facetDistributionMinCount

### ISSUE THREAD

**Issue by bb** [meilisearch/MeiliSearch#1085]
I'm showing many facets to the user at the same time. After facetFiltering, a lot of the values are 0, but all the facet values are still in the response and filtered in the client. This roughly doubles the response body compared to filtered facet values.

I'd like to configure a `facetDistributionMinCount` at query time and most of the time configure it with `1` so all those with zero are not transmitted. The obvious default would be `0`.

To take it further, it might make this configurable per index.

A specialization might be to specify or configure different values per attribute, but that's a use case I do not currently have.

**Comment by Kerollmops** [comment]
Hey @bb,

We already had a similar issue/PR about this behavior and we rejected it because was going against MeiliSearch principles, where we prefer not adding parameters to set up things that can be easily handled front side!

https://github.com/meilisearch/MeiliSearch/issues/1064#issuecomment-724087638

But it is a pleasure to have you in the community, you are really involved in your work! :)

**Comment by bb** [comment]
Sorry for not looking at the existing issues close enough.

**Comment by lpkobamn** [comment]
Is it possible not to receive those facets with a value of 0 from the server?

**Comment by curquiza** [comment]
Hello @lpkobamn 

No you cannot so far, you have to do it on front end
You can use this tool that will not display them by default (byt you can re-activate them): https://github.com/meilisearch/meilisearch-js-plugins/tree/main/packages/instant-meilisearch#keep-zero-facets
