### ISSUE TITLE
Deploy on heroku button

### ISSUE THREAD

**Issue by Ajju2211** [meilisearch/MeiliSearch#1092]
Deploying on platform.sh and digital ocean arr not free. 
So please provide deployment for the heroku platform also.
Either provide heroku deployment button or provide github action to deploy on heroku. 
Thanks in advance

**Comment by eskombro** [comment]
Thanks for the suggestion @Ajju2211 

It is indeed interesting, we can't prioritize this right now, but we will probably add it soon :)

**Comment by eskombro** [comment]
Actually, I found an old PR removing the Heroku button for automatic deployment, which means this was already tested and discarded: 

https://github.com/meilisearch/MeiliSearch/pull/570

**Comment by Ajju2211** [comment]
Thanks for that, I will look into that pr.

**Comment by Ajju2211** [comment]
Heroku is operating on dynos after data inactive or restarting dynos data will be cleared.
Why not implementing database to save instead of inmemory.
Like mongodb, firebase, postgres.
Any among the above implementation is better to implement.
So please look into this issue.

**Comment by eskombro** [comment]
There are two different implications to this idea:

First of all, MeiliSearch is designed to work on top of LMDB, which stores data directly in disk. Meaning that with the current implementation of MeiliSearch, it is not capable of using other solutions as Postgres or Mongo to store it's own data, and this is key because it is designed to have the best possible performance, which could be significantly affected by using this kind of solutions. So it would be a lot of work that might end up hurting own of the main goals of the product.

Sencondly, most of this databases must be run in paid instances to guarantee persistence too. So in the end this deployment wouldn't probably be free after all for the end user.

This is my humble opinion on the matter, let me know if you have a different POV! :)

**Comment by Ajju2211** [comment]
Okay, I got it.
Can you suggest me any heroku like free platform to host.
