### ISSUE TITLE
Sudden spike in CPU usage in production causes server crash

### ISSUE THREAD

**Issue by bhavyalatha26** [meilisearch/meilisearch#1110]
**Describe the bug**

I have a meilisearch one-click app deployed to Digital Ocean (2vCPU + 2GB RAM + 25GB SSD + 3TB Transfer) 3 days ago. In the last two days thrice there was a sudden spike in CPU usage, that caused the droplet to crash with **502 nginx error**. I had to restart the droplet all the time to make it up and running.

I have followed the steps in [meilisearch-digital-ocean](https://github.com/meilisearch/meilisearch-digital-ocean) documentation and hosted the application. Not sure what causes this sudden spike. I have only a single index and 7k small documents within the index on the hosted application.

I am not sure if meilisearch is deployed as standalone or docker application on Digital Ocean one-click, but any guide on how to debug such issues would be a great help !

**Screenshot**

The highlighted spikes in CPU usage caused the crash.
![image](https://user-images.githubusercontent.com/13586777/100456462-67fa4b80-30e6-11eb-8ed7-8c100cba416b.png)

**Additional context**
On contacting the DO support team. They responded with the below message:

> While looking into the history of the physical host the Droplet is on, there doesn't appear to be any recent cases that would clearly outline a source for any issues. However, reviewing your Droplet graphs, I see that CPU usage spiked to 100%.
> 
> Please note that as a self-managed provider we do not directly access customer deployments within droplets. We are happy to offer guidance and any insights we might have to help you move forward even though we may not be able to provide a direct solution. 
> 
> That said, typically, high CPU usage would be a result of either an application/process or the kernel process running within the Droplet itself. While we can and do monitor the CPU usage on the physical host, the usage on the hypervisor itself doesn't translate to the CPU usage within the Droplet.

Regards,
Bhavya

**Comment by eskombro** [comment]
Hi!

I will try to help you a bit to try and find the problem. Please be sure you can SSH to your droplet for the following steps and ideas :)

1. Meilisearch is running as a service, using `systemd`. This means that all the application logs should be available to you by doing:

```bash
journalctl -u meilisearch.service
```

Remember that you can use `--since ` and `--until` to limit your research. Try to check MeiliSearch logs to see if there are any unusual requests.

2. It is also possible that the service runs in a process that is taking too much memory, and it could get killed by the OS. In this case, you won't find anything useful in MeilISearch logs, as when the OS kills the process, MeilISearch is incapable of logging anything at all before it's sad death. In this case, you can probably find in your journalctl (not filtering for MeiliSearch) an Out of memory error.

I suggest you activate memory tracking on Digital Ocean, by installing their Metrics agent (and set alerts if you want to monitor easily): https://www.digitalocean.com/docs/monitoring/how-to/install-agent/

3. Normally, `systemd` restarts your program when it crashed or some internal error occurs. But in case the OS kills MeiliSearch (like in the out of memory example) it may not restart. You can change the restart policy by opening the service file located at `/etc/systemd/system/meilisearch.service` and add a `Restart=always` policy in your `[Service]` section. Your file would look like this:

```
...
[Service]
Type=simple
Restart=always # add this line!
ExecStart=/usr/bin/meilisearch
...
```

Save and exit. Now let's restart deamons and `meilisearch.service`

```bash
systemctl deamon-reload
systemctl restart meilisearch
```

PS: This will restart your service but it can also hide some problems, so it may be better to use it and monitoring at the same time (metrics and alerts). If it restarts too often because it doesn't have enough memory, you might not even notice it, but get service interrutpions etc.

**Comment by bhavyalatha26** [comment]
Hi @eskombro,

Thank you for the detailed help !

I updated my droplet settings with some of the suggestions above :
- Restart always
- Also upgraded the DO metrics from legacy to recent version

I also tried to take a look at the application logs using `journalctl -u meilisearch.service` , but found no useful app logs there.

Also I am little concerned over the **spike in the Disk I/O operation** (as in the above mentioned screenshot) which could also be a potential cause for spike in the CPU usage. Does meilisearch perform any kind of background I/O jobs periodically ?

Regards,
Bhavya.

**Comment by eskombro** [comment]
> Also I am little concerned over the **spike in the Disk I/O operation** (as in the above mentioned screenshot) which could also be a potential cause for spike in the CPU usage. Does meilisearch perform any kind of background I/O jobs periodically ?

I think @MarinPostma could give you a little more insight on this? :)

**Comment by MarinPostma** [comment]
Sorry for the delay, Meili does not perform I/O periodically, unless you are using snapshots or backups, but I don't think that would explain this surge. Do you happen to also have an history of memory usage? This is very odd

**Comment by bhavyalatha26** [comment]
Hi @MarinPostma,

Thanks for getting back. I do not retain any history of memory usage. But this keeps happens randomly not sure why.

**Comment by nubpro** [comment]
I was able to reproduce the same problem by searching a specific string.

I have passed this string to @marinpostma for investigation.

**Comment by bhavyalatha26** [comment]
Hi @MarinPostma ,

I just observed it now and here attaching the screenshots of the metrics, if it helps. Please let me know what other stats can i gather next time when it goes down, to help this debug further.

![Screenshot (17)](https://user-images.githubusercontent.com/13586777/103470934-3f2d3c00-4d9f-11eb-82ca-f687fe538020.png)
![Screenshot (18)](https://user-images.githubusercontent.com/13586777/103470935-40f6ff80-4d9f-11eb-8525-c55637c12248.png)
![Screenshot (19)](https://user-images.githubusercontent.com/13586777/103470937-418f9600-4d9f-11eb-8375-2d3a7aa42897.png)

**Comment by vinhnguyen1211** [comment]
![image](https://user-images.githubusercontent.com/15612361/104847261-97248080-5911-11eb-883c-dc5e7d38e1ca.png)
My instance is experiencing the same problem. Should I retain logs for further investigation?

**Comment by Numline1** [comment]
I feel like we're experiencing something very similar
![image](https://user-images.githubusercontent.com/12192684/113523624-09b80a80-95a9-11eb-9528-285f096bc955.png)

At that time, there was no surge of operations or updates (according to a status log). @curquiza can you elaborate on this before 0.21.0 is out please? Is that something that can be prevented on older versions? Thanks!

**Comment by curquiza** [comment]
Hello @Numline1!
Unfortunately, we don't have a real solution before the v0.21.0 is out. Maybe @Kerollmops has some workarounds to share?

**Comment by NatBLida68** [comment]
@cur

> Hello @Numline1!
> Unfortunately, we don't have a real solution before the v0.21.0 is out. Maybe @Kerollmops has some workarounds to share?

Since  V 0.21.0 is yet to release do we have a solution for this in 0.20.0 ?

**Comment by curquiza** [comment]
Hello @NatBLida68! Sorry, I've just asked Kero for a work-around, but he does not have any either. Sorry!

**Comment by bayareawebpro** [comment]
I experienced something similar.   When updating the index settings, the process consumes all available memory and the process is killed by the system.   It appears the engine will keep doing this over and over stuck in a loop.  The only solution I found is to destroy the index and rebuild it starting from scratch.

**Comment by curquiza** [comment]
Thanks for sharing your metrics and the error report @bayareawebpro!
For 1.6M of documents, I recommend using a bigger machine, like 16Gb memory or bigger depending on the size of each document.

**Comment by bayareawebpro** [comment]
@curquiza  Thanks for the tip, will do!

**Comment by curquiza** [comment]
Hello @bhavyalatha26, @bayareawebpro, @Numline1, @vinhnguyen1211, @nubpro and everyone following the issue!

The [first RC of MeiliSearch v0.21.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.21.0rc0) is out.
We did our best to fix indexation and crash issues. We succeeded to improve it, but not to totally fix them.

You can test this new release by downloading the binaries available in this release.
Or you can use it with docker:

```bash
docker run -p 7700:7700 getmeili/meilisearch:v0.21.0rc0 ./meilisearch
```

We will still improve this after the release of the v0.21.0. We would rather release a non-completely optimized version rather than delay it and, at the same time, delay the release of new features. Be sure we are doing our best to always improve these indexation issues.

As a reminder:
* despite the improvements, we always recommend pushing your documents to MeiliSearch by batch and not one by one. The maximum payload size of MeiliSearch is 100Mb and [can be optionally increased](https://docs.meilisearch.com/reference/features/configuration.html#payload-limit-size). It means most of the dataset can be pushed with one call to the API.
* If you still have a memory crash, it means the RAM of your machine might not be adapted to your dataset size. We recommend increasing the RAM of your machine.

Thanks for your patience and your help with this! ❤️

**Comment by curquiza** [comment]
Hello everyone reading this issue.

I close this issue due to the lack of feedback since it was happening with an old version of Meilisearch.

However, for anyone having issues in general with indexation performance, like this issue, please, refer to [this discussion](https://github.com/meilisearch/meilisearch/discussions/2131). Your feedback will be really appreciated 🙂
