### ISSUE TITLE
Highlighting items in array

### ISSUE THREAD

**Issue by ebess** [meilisearch/MeiliSearch#1146]
**Describe the bug**
Items of an array are not highlighted despite matches are present in the `_matchesInfo` results.

**Expected behavior**
Matches should be wrapped in `<em>` like regular string attributes in the `_formatted` result.

**Screenshots**
![Selection_021](https://user-images.githubusercontent.com/5565003/103276076-e425ce80-49c5-11eb-9ff1-3ea9dc40f448.png)

**Comment by Tadaz** [comment]
Just wanted to point out that the values of objects are not being highlighted as well.

While searching for query **_ball_** I get these results:

![Screenshot 2021-05-21 at 4 07 02 pm](https://user-images.githubusercontent.com/10881931/119159385-11dfe280-ba4f-11eb-8e8e-7a1270f06963.png)

But the expected behaviour is this:

![Screenshot 2021-05-21 at 4 07 16 pm](https://user-images.githubusercontent.com/10881931/119159436-1f956800-ba4f-11eb-9e92-429e948c1a70.png)

**Comment by curquiza** [comment]
We are working on fixing both of these highlight issues 🙂

**Comment by curquiza** [comment]
Fixed by the integration of the new search engine in https://github.com/meilisearch/MeiliSearch/pull/1421
