### ISSUE TITLE
No backward compatibility guarantee?

### ISSUE THREAD

**Issue by iredmail** [meilisearch/MeiliSearch#1152]
Dear developers,

I found this in official document [Updating MeiliSearch](https://docs.meilisearch.com/guides/advanced_guides/installation.html#updating-meilisearch):

> Note that all MeiliSearch versions are not compatible with each other, and you may need to re-index your documents. If you get the error `Cannot open database, expected MeiliSearch engine version: X.X.X, current engine version Y.Y.Y`, delete your database folder (defaults to `data.ms`), and re-index all your documents.

We're evaluating MeiliSearch for indexing emails, we receive + index + compress + encrypt about 20k emails from a production server, it's not fun at all to decrypt + decompress all those processed emails and re-index after upgrade MeiliSearch.

Is it just too early to offer the backward compatibility guarantee, or no plan at all?

**Comment by MarinPostma** [comment]
Hello @iredmail !
Indeed, there is no backward compatibility guarantee for now since we are still in beta. As soon as we hit stable, this should not be a problem anymore (no ETA).

As for migration, there is a backup feature that exports the database in a backward compatible format, but it needs reindexation: https://docs.meilisearch.com/guides/advanced_guides/snapshots_and_dumps.html#dumps

let me know if it helps

**Comment by iredmail** [comment]
Thanks for the explanation. It's better add the content in your reply to the official document too to avoid confusion. :)

**Comment by MarinPostma** [comment]
> Thanks for the explanation. It's better add the content in your reply to the official document too to avoid confusion. :)
ping @react-learner
