### ISSUE TITLE
Why this project named `Meili`

### ISSUE THREAD

**Issue by botsphp** [meilisearch/MeiliSearch#1182]
Sorry guys, it's not an issue.

i'm from china, i have spend some time on this project to study, and write some article share to other people.

`Meili` is a china words means `beautiful`  `美丽`, so some friends thought it was an open source project created by Chinese people.

I'm curious does it mean something else in other language or area?

;)

**Comment by CaroFG** [comment]
Hi, @botsphp!!!
Meili takes its name after a Norse god: https://en.wikipedia.org/wiki/Meili

The Icelandic historian [Snorri Sturluson](https://en.wikipedia.org/wiki/Snorri_Sturluson) considers Meili to be ‘the god of oblivion,’ hence, the need to have a powerful search engine in order to find what we might have forgotten :)
