### ISSUE TITLE
Example in meilisearch-core broken

### ISSUE THREAD

**Issue by ncioj10** [meilisearch/MeiliSearch#1203]
**Describe the bug**

As  it makes more sense to directly implement MeiliSearch in Rust for our use case, we tried to execute the example given in meilisearch-core (from_file.rs). 
It silently fails on our csv, which we assume to be happening during the updates. We used cat to look into the update.mdb created and it contains an error with the key "missing_primary_key".
In our csv there is a column called "id", thus we tried to add it to UpdateSettings via:

`settings.primary_key = UpdateState::Update("id".to_string());`

Unfortunately the problem seems to persist. Is it possible to update/fix the example code to work again?
In addition documentation for this example would be really helpful, as it is quite difficult to dig through the code without any comments/documentation. 

**Expected behavior**
Correctly set up index. 

**Additional context**
This occurs using the current master branch.

**Comment by MarinPostma** [comment]
Hey @ncioj10!

I have to admit that this part of the code is not really maintained, and it should probably be removed. If you have to the heart to fix it I'll accept it and it'll  live a bit longer ;)

We won't do much more maintenance on this part, since this is all going to be replaced in the short future, and I wouldn't rely on the stability of the internal API if I were you

cheers!
