### ISSUE TITLE
"Get Started" link 404s

### ISSUE THREAD

**Issue by cgardens** [meilisearch/MeiliSearch#1221]
**Describe the bug**
* "Get Started" link 404s

**To Reproduce**
1. Go to https://www.meilisearch.com/
2. Click on 'Get Started'
3. 404

**Expected behavior**
Not 404

**Screenshots**
![Screen Cast 2021-02-02 at 4 21 48 PM](https://user-images.githubusercontent.com/9092207/106680190-01c0f780-6573-11eb-89a6-eaff4c16cc39.gif)

**Desktop (please complete the following information):**
 - OS: macOS 11.1
 - Browser: Chrome
 - Version  Version 88.0.4324.96 (Official Build) (x86_64)

**Comment by cgardens** [comment]
Same with the "Contact" button.

**Comment by cgardens** [comment]
Maybe related: https://github.com/meilisearch/MeiliSearch/pull/1220

**Comment by curquiza** [comment]
Hello @cgardens!

Thanks a lot for your feedback 👍 
Issues are already opened in the documentation about this:
- https://github.com/meilisearch/documentation/issues/738
- https://github.com/meilisearch/documentation/issues/736
This is indeed due to a huge docs restructuration (https://github.com/meilisearch/documentation/pull/735), we hope you will enjoy our new docs! 😁

We are currently fixing this asap, and we are really sorry for the inconvenience!
