### ISSUE TITLE
 200 indexes hard limit

### ISSUE THREAD

**Issue by volkandkaya** [meilisearch/MeiliSearch#1242]
**Is your feature request related to a problem? Please describe.**
We have a lot of small indexes, <10mb and would like an API to search them all.

**Describe the solution you'd like**
Remove the hard limit if possible.

**Describe alternatives you've considered**
Nothing yet, this solution seems perfect.

**Comment by berkes** [comment]
I'm in need of this too.

The alternative that I'm looking at, is some permission system, implemented with [filtering](https://docs.meilisearch.com/reference/features/filtering.html).

So, from my initial, shallow research, I'd like to add:

**Describe alternatives you've considered:**

1. Add an Array with e.g. ids. E.g. `accessible_by: [1, 5, 13, 100]`
2. Ensure the query has a filter that filters on, say. current_user_id. e,g, `{ filters: { accessible_by: <current_user_id> } }`

This will limit the resulting documents. 

It will not, however, return different versions of documents, which is another requirement that I have. 

This can be done client-side, where a server acts as proxy and removes or changes fields or data that should not be visible to current user.
While filtering out fields of documents is a valid use-case for a proxy or application layer, filtering out documents is not, as that interferes with the scoring.

Both cases would be solved for me, by creating small, per user, indexes, as stated in the original feature request above.

**Comment by volkandkaya** [comment]
Filtering would slow down searches massively and increase index size?

I was looking at using the snapshop feature to swap and replace the "DB". Which seems like an okay solution but I can't figure out how to run a snapshop on command.

**Comment by MarinPostma** [comment]
Hey! I suggest you take a look at faceting, it should solve your problem

**Comment by volkandkaya** [comment]
@MarinPostma each dataset can be very different, they won't have the same fields. Otherwise it looks like a great solution.

**Comment by berkes** [comment]
> Hey! I suggest you take a look at faceting, it should solve your problem

Thanks for taking the time to respond. And thanks for the suggestion.

I'm afraid I wasn't clear about *my* use-case, or else I might misunderstand how Meilisearch sees facets. But for me, it does not solve the issue.

My use case, very much simplified, is as follows.

Bob has a list of contacts in his addressbook. He can search through these contacts. A contact, Anne, may have disclosed her bio and emailaddress to Bob: "Anne is Freelance translator" and "anne@flosstranslators.org". 
Carol also has a list of contacts. Her contact, Anne, allowed Carol to see her bio, but not her emailaddress.

So, when both Carol and Bob search for "Translator", Anne shows up. But when both search for "flosstranslations.org", only Bob gets the document for Anne.

Currently, if we proceed with Meilisearch, we'd need to handle the filtering and disclosing of attributes, client-side. That is complex and hard work, because it involves not just removing or censoring attributes, it must ensure that searching for an attribute that is not visible, should not yield a result.

We're attempting Meilisearch because it's many-indexes model allows us to get quite far without hacks. But it would impose a limit of 200 users/addressbooks per installation, which currently isn't an issue yet, but should best not become an issue in future either. 

Please note that I'm merely chiming in here with *my* use case, and cannot speak for @volkandkaya whose use-case may be different. In which case I'm sorry for the noise and will take this issue to a new ticket!

**Comment by volkandkaya** [comment]
https://github.com/search?q=200+in%3Afile+repo%3Ameilisearch%2FMeiliSearch&type=Code i couldn't find the limit in the code.

**Comment by curquiza** [comment]
Fixed by the integration of the new search engine in https://github.com/meilisearch/MeiliSearch/pull/1421

There is no limit anymore
