### ISSUE TITLE
Use 200 status code for healthcheck endpoint

### ISSUE THREAD

**Issue by MightySCollins** [meilisearch/MeiliSearch#1282]
**Is your feature request related to a problem? Please describe.**
My issue is related to https://github.com/meilisearch/meilisearch-kubernetes/issues/56. If you want to deploy this to GKE using there ingress you need a health check which returns a 200 status code

**Describe the solution you'd like**
Either a new health check endpoint or the existing one to return a 200 status code. I understand why 204 is used so I guess it could return 200 with the words success or similar.

**Describe alternatives you've considered**
The solution in the other ticket uses / as the endpoint for the health check but seems to not return 200 in production when using a master key.
The other solution I can think of is using Nginx to proxy the 204 and change it to a 200 code but this is another dependency which should not be required.

**Comment by curquiza** [comment]
Hello @MightySCollins!
We already have this in mind -> https://github.com/meilisearch/MeiliSearch/pull/1164
Thanks for your feedback!

**Comment by eskombro** [comment]
Trying to find sources on good practices on health checks, it seems to be generally "expected" to send a JSON body with relevant information or data about the status. I think this is why it is widely considered that a Health check returns 200 and not 204. For example, [IBM practices for health checks in microservices](https://www.ibm.com/garage/method/practices/manage/health-check-apis/) state:

> With a simple health check API, you can test whether the service is available. Consider a microservice that is responsible to retrieve user information from a database. The main dependency is the database where the user entries are stored. In pseudocode, a health check API might look like this example:

```
Route.add(‘/api/v1/healthcheck’, Method=’GET’) {
    If (userdb.connect() == “Successful”) {
        headers={‘http_status’:200, ‘cache-control’:  ‘no-cache’}
        body={‘status’: ‘available’}
        }
    Else {
        headers={‘http_status’:500, ‘cache-control’:  ‘no-cache’}
        body={‘status’: ‘unavailable’}
        }
}
```

IBM requirements include:

```
The derived requirements are as follows:

...

    The results must be returned as an HTTP status code with JSON data
```

Load balancer implementation in most cloud providers use `200 OK` as a standard for health check:

[GCP](https://cloud.google.com/load-balancing/docs/health-checks#optional-flags-hc-protocol-http):

```
If Google Cloud finds the expected response string anywhere in the first 1,024 bytes of the received response body, and if the HTTP status is 200 (OK), the probe is considered successful.
```

[AWS](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-healthchecks.html):

```
If the load balancer receives any response other than "200 OK" within the response timeout period, the instance is considered unhealthy
```

[DigitalOcean](https://www.digitalocean.com/docs/app-platform/concepts/health-check/):

```
an HTTP health check can be configured to ping the root URL of your site and ensure that the response is HTTP 200 (OK)
```

I don't see any useful reason to change this "expected" or standard behaviour, because this can introduce complexity as stated at the beginning on this issue.

#1164 Could be a good solution for this, and a JSON body stating a clear message of availability is the, IMO, a good choice!

**Comment by curquiza** [comment]
Thanks for your investigation @eskombro!
FYI @MightySCollins we are going to release a new version of MeiliSearch containing several fixes including this change.
The core team is in rush at the moment but we'll try to release this as soon as possible 🙂

**Comment by MightySCollins** [comment]
@curquiza No problem at all. It's open source so take all the time you need. Thanks for keeping me updated.

**Comment by curquiza** [comment]
Here is the final decision about what we are going to implement: the health route will return a `200` with a JSON body `"status": "available"`. According to the investigation of @eskombro, it seems to be a conventional way to handle the health route.

@irevoire will implement it as his first task in the core team 🎉 
I'm going to close the PR #1164 to let him open another one (easier to close and reopen as trying to rebase it).
