### ISSUE TITLE
Performance issue with 1Gb of docs

### ISSUE THREAD

**Issue by georgezhangjiacheng** [meilisearch/meilisearch#1295]
Why can I only have 228132 documents in the same index 
In data.ms, The data size is only 1.1G
I can't continue adding documents

**Comment by georgezhangjiacheng** [comment]
already set MEILI_HTTP_PAYLOAD_SIZE_LIMIT: 1048576000

**Comment by curquiza** [comment]
Hello @georgezhangjiacheng

What is the returned error please?

**Comment by georgezhangjiacheng** [comment]
In docker , The container returned to me without error

**Comment by MarinPostma** [comment]
Hello @georgezhangjiacheng, can you provide us with reproduction steps please?

**Comment by georgezhangjiacheng** [comment]
1.run meilisearch project in docker
![image](https://user-images.githubusercontent.com/49780609/111607106-e9e7bf00-8812-11eb-8d27-7cff0a41e20c.png)
2.
use python
```
import meilisearch
client = meilisearch.Client(xxxxxx)
client.create_index('test', {'primaryKey': 'content_id'})
ret = [{xxxxxx},{xxxxxxx}]
for i in range(ret):
      client.index('test').add_documents(i)
```
3.When I add about 220000 datas, I don't receive an error, but the number of documents on the home page won't increase
![image](https://user-images.githubusercontent.com/49780609/111607713-7a260400-8813-11eb-9a1d-454fc67e02d8.png)

**Comment by MarinPostma** [comment]
Are you adding the documents 1 by 1?

**Comment by georgezhangjiacheng** [comment]
I tried to push every 2000 pieces of data，and tried 10000 pieces of data

**Comment by MarinPostma** [comment]
Have you checked that all of the updates had been processed

**Comment by georgezhangjiacheng** [comment]
I run a new meilisearch project,  and added the document again
![image](https://user-images.githubusercontent.com/49780609/111719473-e138cc80-8896-11eb-9839-0f9cb554b1cf.png)
```
import meilisearch

if __name__ == '__main__':
    client = meilisearch.Client('http://xxxxxxxx:7700/')
    a = client.index('test').get_all_update_status()
    print(a)

```
![image](https://user-images.githubusercontent.com/49780609/111719187-5526a500-8896-11eb-9274-6c55153c714d.png)

**Comment by harnit-bakshi** [comment]
Facing the same issue we ingested 10Million records Meili shows just 2.7 million on the U/I

**Comment by Numline1** [comment]
Same issue, just with around 400k results, updates were enqueued and changing to processed, just with no data being added, however the endpoint with updates was showing 'number: 100' on processed updates. Version 0.19.0, Docker, last seen messages in docker logs were
```
[2021-03-26T01:25:52Z ERROR meilisearch_http::helpers::meilisearch] Error during criteria builder; AttributeNotFound
[2021-03-26T03:13:39Z ERROR meilisearch_http::helpers::meilisearch] value: "Disfruta de mi cuerpo al máximo "; index: 0, match: MatchPosition { start: 25, length: 2 }
[2021-03-26T03:13:48Z ERROR meilisearch_http::helpers::meilisearch] value: "Disfruta de mi cuerpo al máximo "; index: 0, match: MatchPosition { start: 25, length: 2 }
```

No special config, just master key in .env. The total size of the DB was around 1.3G, file sizes weren't changing once it stalled.

**Comment by cheluskin** [comment]
There was the same problem. Helped to increase swap. It took several hours to add 2 million documents

**Comment by curquiza** [comment]
Hello,

For people having troubles with huge datasets like millions of documents -> MeiliSearch is not currently designed to handle this amount of documents.
However, the core team is currently working hard on a new search engine that will handle huge datasets. The new search engine will be release in the v0.21.0. We'll keep you informed of the release date.

**Comment by curquiza** [comment]
Hello @cheluskin, @harnit-bakshi, @georgezhangjiacheng and everyone following the issue!

The [first RC of MeiliSearch v0.21.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.21.0rc0) is out.
We did our best to fix indexation and crash issues. We succeeded to improve it, but not to totally fix them.

You can test this new release by downloading the binaries available in this release.
Or you can use it with docker:

```bash
docker run -p 7700:7700 getmeili/meilisearch:v0.21.0rc0 ./meilisearch
```

We will still improve this after the release of the v0.21.0. We would rather release a non-completely optimized version rather than delay it and, at the same time, delay the release of new features. Be sure we are doing our best to always improve these indexation issues.

As a reminder:
* despite the improvements, we always recommend pushing your documents to MeiliSearch by batch and not one by one. The maximum payload size of MeiliSearch is 100Mb and [can be optionally increased](https://docs.meilisearch.com/reference/features/configuration.html#payload-limit-size). It means most of the dataset can be pushed with one call to the API.
* If you still have a memory crash, it means the RAM of your machine might not be adapted to your dataset size. We recommend increasing the RAM of your machine.

Thanks for your patience and your help with this! ❤️

**Comment by curquiza** [comment]
Hello everyone reading this issue.

I close this issue due to the lack of feedback since it was happening with an old version of Meilisearch.

However, for anyone having issues in general with indexation performance, like this issue, please, refer to [this discussion](https://github.com/meilisearch/meilisearch/discussions/2131). Your feedback will be really appreciated 🙂
