### ISSUE TITLE
Error 503 - Service unavailable

### ISSUE THREAD

**Issue by Numline1** [meilisearch/meilisearch#1341]
**Describe the bug**
We're using Meilisearch on a fairly large DigitalOcean droplet, however we periodically get errors like
```
MeiliSearch\Exceptions\ApiException

Service Unavailable
```

when updating the index using Laravel Scout. I haven't been able to trace this back to anything specific, and there's no further information in the ApiException that I can see.

What I can see however, although I'm not sure it's related, it the error log from `docker logs` on our server:

```
[2021-04-15T13:46:05Z ERROR meilisearch_core::bucket_sort] error during filtering: expected value for document id 23334
[2021-04-15T13:46:05Z ERROR meilisearch_core::bucket_sort] error during filtering: expected value for document id 23970
[2021-04-15T13:46:05Z ERROR meilisearch_core::bucket_sort] error during filtering: expected value for document id 24271
[2021-04-15T13:46:05Z ERROR meilisearch_core::bucket_sort] error during filtering: expected value for document id 24497
[2021-04-15T13:46:05Z ERROR meilisearch_core::bucket_sort] error during filtering: expected value for document id 24532
[2021-04-15T13:46:05Z ERROR meilisearch_core::bucket_sort] error during filtering: expected value for document id 25386
[2021-04-15T13:46:05Z ERROR meilisearch_core::bucket_sort] error during filtering: expected value for document id 26936
```
I'm not sure these two are related, however there's several thousands of these errors with different IDs (these are not document IDs, we're using a custom _id key with values like up_123 or uv_123).

These are potentially happening during update spikes (the 503 errors) but neither CPU nor disk IO are extremely busy:

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/12192684/114961746-b75cd080-9e69-11eb-88eb-db1e4467131a.png">

**To Reproduce**
I don't have a specific behavior reproduction steps, however we're mostly seeing these errors when trying to push a new or update an existing document or multiple documents.

**Expected behavior**
Properly queueing and indexing the documents

**Instance info**
- OS: [e.g. iOS] - Ubuntu Server 19.03.12
- 4 cores, 8 GB RAM
- **Concurrency** - Couple of dozen searches per second
- Nr of docs in index - around 400k

**Comment by curquiza** [comment]
Hello @Numline1, thanks for your report. We are currently working on a new search engine that will be released in the v0.21.0. If the v0.21.0 does not fix your issue, be sure we will investigate deeper on it!

Thanks for using MeiliSearch 🙂

**Comment by NatBLida68** [comment]
![IMG-20210613-WA0016](https://user-images.githubusercontent.com/55424433/121797358-4bb29c00-cc3d-11eb-974a-faba8d1c46a0.jpg)
We have tried setting auto reboot  but this is bad in past 24 hr  can't even count the reboots 
![IMG_20210613_114401](https://user-images.githubusercontent.com/55424433/121797419-b7950480-cc3d-11eb-80f5-d02ec56896e9.jpg)

**Comment by curquiza** [comment]
Hello, can you people share with us:
- the dataset size and an example of one typic document?
- the machine memory size?
- when the error starts to occur (when adding documents, pushing settings...)?

Thanks in advance for your help 😊

**Comment by NatBLida68** [comment]
Sorry idk this will help you or not 
In my case 
I have a single index which is my db name.
26models  in which used tosearchable array  to 7 common columns  ( saving only the common 7 column from each model in meili database ) . 
Each table has not greater than 50000 data   some of them are less than 5000.
 using droplet in digital  2gb 50gb 2Tb ($10).
Sadly I  have no idea why it is failing  because if I edit  same data sometimes it gets inserted sometimes  it doesn't  since 100% spike and it goes down    ,  what  I can clearly say not working is  getAllIndex    delete allindex methods are not working it throws error like there is no indexes  (using meilisearch php client )  but  getindex works

**Comment by curquiza** [comment]
26 * 50 000 = 1.3M is not a small dataset for MeiliSearch. 2Gb of RAM is not enough. You should take a DO droplet with more RAM (8GB I think)
Plus, it depends on the size of your documents: you can have only 7 columns but 500 words in each column of each document. So, depending on that you should more increase the RAM of your machine.

**Comment by curquiza** [comment]
Hello @Numline1 @NatBLida68 and everyone following the issue!

The [first RC of MeiliSearch v0.21.0](https://github.com/meilisearch/MeiliSearch/releases) is out.
We did our best to fix indexation and crash issues. We succeeded to improve it, but not to totally fix them.

You can test this new release by downloading the binaries available in this release.
Or you can use it with docker:

```bash
docker run -p 7700:7700 getmeili/meilisearch:v0.21.0rc1 ./meilisearch
```

We will still improve this after the release of the v0.21.0. We would rather release a non-completely optimized version rather than delay it and, at the same time, delay the release of new features. Be sure we are doing our best to always improve these indexation issues.

As a reminder:
* despite the improvements, we always recommend pushing your documents to MeiliSearch by batch and not one by one. The maximum payload size of MeiliSearch is 100Mb and [can be optionally increased](https://docs.meilisearch.com/reference/features/configuration.html#payload-limit-size). It means most of the dataset can be pushed with one call to the API.
* If you still have a memory crash, it means the RAM of your machine might not be adapted to your dataset size. We recommend increasing the RAM of your machine.

Thanks for your patience and your help with this! ❤️

**Comment by curquiza** [comment]
Hello everyone reading this issue.

I close this issue due to the lack of feedback since it was happening with an old version of Meilisearch.

However, for anyone having issues in general with indexation performance, like this issue, please, refer to [this discussion](https://github.com/meilisearch/meilisearch/discussions/2131). Your feedback will be really appreciated 🙂
