### ISSUE TITLE
Cannot run server by backward compatibility

### ISSUE THREAD

**Issue by djKooks** [meilisearch/MeiliSearch#1361]
**Describe the bug**
Hello,
I cannot run the project after I've pull the codes.
Seems it is the problem of backward compatibility...is there a way to refresh(or delete) old database storage?

**To Reproduce**
```
$ cargo run --release
...
Compiling actix-cors v0.5.4
    Finished release [optimized + debuginfo] target(s) in 2m 28s
     Running `target/release/meilisearch`
Error: Cannot open database, expected MeiliSearch engine version: 0.18.XX, current engine version: 0.20.0
```

**Expected behavior**
MeiliSearch server should be started

**Comment by curquiza** [comment]
Hello @djKooks,

2 solutions:
- delete `data.ms` file and re-push your documents. Not really convenient if you are in production, but here you seem to run the project as any contributor 🙂
- use the dumps: https://docs.meilisearch.com/reference/features/dumps.html#creating-a-dump.

**Comment by MarinPostma** [comment]
On an additional note to what @curquiza said, I will add that MeiliSearch follows [semantic versioning](https://semver.org/). Since we are pre 1.0, the minor version are not compatible with each other, but two version with the same minor (i.e only differing in patch version) are compatible with each other. Hope that helps :)

**Comment by djKooks** [comment]
@curquiza @MarinPostma thanks for help~
