### ISSUE TITLE
Create related indexes

### ISSUE THREAD

**Issue by mevangelinakis** [meilisearch/MeiliSearch#1393]
Hi,

Is there a way to create multiple indexes using another index as the documents source?

For example, I have an index `products` which I fill with a set of documents from my database and has the default ranking rules.

I want to give users some sorting options, so I have to create some new indexes, lets say `products_asc_price` and `products_desc_price` setting a ranking rule `asc(price)` and `desc(price)` respectively.

The indexes' documents are the same, the only thing that changes is the order.

Thanks!

**Comment by curquiza** [comment]
Hello @mevangelinakis, thanks for your feedback!
What you ask for is not available right now with MeiliSearch.

I don't think this idea is in our current roadmap either. However, we have a public roadmap where our user can share their ideas and their needs. It would be awesome if you can add your idea so that other users will upvote it if they need it as well.
https://roadmap.meilisearch.com/tabs/5-ideas

Thanks in advance :)

**Comment by gmourier** [comment]
Hello @mevangelinakis!

I think you might be interested in the feature we are working on, we plan to release it in 0.22. There will be no more need to create several indexes as a workaround to the fact that the sort feature is missing at search time. 😉 https://github.com/meilisearch/product/issues/43 (If you want to know how we idealized this feature to what we specified). 

Please, let me know if it solves your issue so that we can close this issue.

**Comment by curquiza** [comment]
Closing this issue since it's a feature request and it's not handle on this repo :)
