### ISSUE TITLE
Meilisearch timing out and crashing on GVC

### ISSUE THREAD

**Issue by ALittleMoreDevTeam** [meilisearch/meilisearch#1412]
Hey, 

I am currently using an instance of the search on Google Virtual Computer.

I have not had any issues before, but since deleting one index, I now cannot use the search at all, even simply uploading one row of data crashes the engine 

this is my delete request 
        private static async void DeleteIndexes()
        {
            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Add("X-Meili-API-Key", "XXXXXX");
                using (var request = new HttpRequestMessage(new HttpMethod("DELETE"), "https://xxxxxxxx/indexes/mattressmannew"))

                {
                    var response = await httpClient.SendAsync(request);
                    var RESULT = response.Content.ReadAsStringAsync().Result;

                    Console.WriteLine(RESULT);
                }
            }

        }

whether I try to search, return index info, anything at all, it now crashes 

I can't seem to see why

**Comment by CaroFG** [comment]
Hi! What version of MeiliSearch are you using? Were you still indexing the documents when you deleted the index?

**Comment by ALittleMoreDevTeam** [comment]
hey :) latest version.

I'm deleting an entire index 

then requesting documents from another

that process seemed to kill meilisearch to the point where any search request or interaction at all results in a 502

**Comment by ALittleMoreDevTeam** [comment]
I have now tried the process again and i can confirm it is the deletion of the indexes that crashes the entire system 

i have deleted an index because it was not updating, and now the entire Meilisearch is down

**Comment by ALittleMoreDevTeam** [comment]
> Hi! What version of MeiliSearch are you using? Were you still indexing the documents when you deleted the index?

hey :) latest version.

I'm deleting an entire index

then requesting documents from another

that process seemed to kill meilisearch to the point where any search request or interaction at all results in a 504


I have now tried the process again and i can confirm it is the deletion of the indexes that crashes the entire system

i have deleted an index because it was not updating, and now the entire Meilisearch is down

**Comment by curquiza** [comment]
Hello @ALittleMoreDevTeam, and everyone following the issue!

The [first RC of MeiliSearch v0.21.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.21.0rc0) is out.
We did our best to fix indexation and crash issues. We succeeded to improve it, but not to totally fix them.

You can test this new release by downloading the binaries available in this release.
Or you can use it with docker:

```bash
docker run -p 7700:7700 getmeili/meilisearch:v0.21.0rc0 ./meilisearch
```

We will still improve this after the release of the v0.21.0. We would rather release a non-completely optimized version rather than delay it and, at the same time, delay the release of new features. Be sure we are doing our best to always improve these indexation issues.

As a reminder:
* despite the improvements, we always recommend pushing your documents to MeiliSearch by batch and not one by one. The maximum payload size of MeiliSearch is 100Mb and [can be optionally increased](https://docs.meilisearch.com/reference/features/configuration.html#payload-limit-size). It means most of the dataset can be pushed with one call to the API.
* If you still have a memory crash, it means the RAM of your machine might not be adapted to your dataset size. We recommend increasing the RAM of your machine.

Thanks for your patience and your help with this! ❤️

**Comment by curquiza** [comment]
Hello everyone reading this issue.

I close this issue due to the lack of feedback since it was happening with an old version of Meilisearch.

However, for anyone having issues in general with indexation performance, like this issue, please, refer to [this discussion](https://github.com/meilisearch/meilisearch/discussions/2131). Your feedback will be really appreciated 🙂
