### ISSUE TITLE
Breaking changes in GET /search facetsDistribution usage

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#1489]
**Describe the bug**

Previously `facetsDistribution` was expecting an array of attributes: 
`/search?facetsDistribution=["genres", "title"]`

It is now expected a string of attributes:

`search?facetsDistribution=genres,title`

**To Reproduce**
1. Create index with movies containing `title` and `genres` field
2. try to get facetsDistribution the way it was done in v0.20
3. Error thrown
```json
{
    "message": "invalid facet distribution, the fields [\"genres'] are not set as filterable",
    "errorCode": "bad_request",
    "errorType": "invalid_request_error",
    "errorLink": "https://docs.meilisearch.com/errors#bad_request"
}
```

**Expected behavior**
Same behavior 

**MeiliSearch version**:
v0.21.0

**Comment by gmourier** [comment]
Nice spot @bidoubiwa, thanks! The API convention will state on query parameters.

**Comment by curquiza** [comment]
Checked with @gmourier: for the v0.21.0 we let the behavior as it is now: we only accept this syntax `attribute1,attribute2,attribute3` and not this JSON syntax `["attribute1", "attribute2", "attribute3"]`.

I ping the @meilisearch/docs-team because it will involve a tiny change in the docs: `["*"]` should be `*` [in this array](https://docs.meilisearch.com/reference/api/search.html#query-parameters) at the line `attributesToRetrieve`

I ping @bidoubiwa because it will involve changes in the JS SDK for the `search` method using GET. 

Sorry for the inconvenience, the JSON syntax should not have been accepted as a query parameter in the `GET` request.

**Comment by curquiza** [comment]
I close this issue then since we keep the behavior as it is.
