### ISSUE TITLE
Can't add documents (and not showing error) when the primary key contains non-alphanumeric

### ISSUE THREAD

**Issue by nafkhanzam** [meilisearch/MeiliSearch#1566]
**Describe the bug**
Can't add documents (and not showing error) when the primary key contains non-alphanumeric (tested on '?' and '.' characters). Didn't find any warning about this in the documentation.

**To Reproduce**
1. Use meilisearch nodejs sdk
2. Create index with primaryKey: "serial"
3. Call addDocuments to the index with `[{ "serial": "test-serial?", ... }, { "serial": "valid-serial", ... }]`
4. The documents aren't added and doesn't receive an error. (I guess because it is atomic, the valid serial aren't added as well)

**Expected behavior**
Show an error or be able to add documents with non-alphanumeric characters on primary key

**MeiliSearch version:** [e.g. v0.20.0]
v0.20.0

**Additional context**
Run on docker on cloud vm

**Comment by curquiza** [comment]
Hello @nafkhanzam!

MeiliSearch processes its tasks asynchronously. It means you will only get an `updateId` when sending your documents, but to know if the task failed or not and why, you have to check the [`GET /indexes/:uid/updates/:updateId` routes](https://docs.meilisearch.com/reference/api/updates.html#get-an-update-status).
More details here: https://docs.meilisearch.com/faq/#i-did-a-call-to-an-api-route-and-i-only-got-an-updateid-as-a-response-what-does-it-mean

Your addition probably failed because indeed you cannot add documents where the primary key contains special characters. This is explained here in the documentation: https://docs.meilisearch.com/learn/core_concepts/documents.html#document-id

**Comment by nafkhanzam** [comment]
Ahh, I definitely missed that, thank you
