### ISSUE TITLE
Update nothing happend

### ISSUE THREAD

**Issue by mrmaxonline** [meilisearch/MeiliSearch#1569]
Since RC2 update of existen doc is not working. Doc data is old. RC2 work fine. RC3 and RC4 from git via cargo build is fail to update. Only new docs data is present.

**Comment by CaroFG** [comment]
Hi! You can find the v0.21 documentation here: https://dev.docs.meilisearch.com/ but keep in mind it's still a WIP and the search bar is not working on this one, it's only working for the stable version (v0.20) so you'll have to navigate through the menus.

**Comment by curquiza** [comment]
Hello @mrmaxonline!

I'm not sure to understand, can you detail your steps so that we can reproduce the bug and fix it?

**Comment by mrmaxonline** [comment]
Hi!

Build RC3 (or RC4) from git update. POST 'documents' with data but after search old data present in result. Only Add document working - Update notthing happend.

**Comment by curquiza** [comment]
Hello, here is the step I do with RC4

- adding with [`POST /indexes/:uid/documents`](https://docs.meilisearch.com/reference/api/documents.html#add-or-replace-documents)
```json
[
  { "id": 2,    "title": "Pride and Prejudice",  "author": "Jane Austin",  "genre": "romance", "price": 3.5 }
]
```
-> the document is well added, I get it with [`GET /indexes/:uid/documents/2`](https://docs.meilisearch.com/reference/api/documents.html#get-one-document)

- Then I try to update with [`PUT /indexes/:uid/documents`](https://docs.meilisearch.com/reference/api/documents.html#add-or-update-documents)
```json
[
  {
	"id": 2,
	"author": "J. Austen",
	"date": "1813"
  }
]
```
`author` should be updated.
`date` is added.
The other fields stay unchanged.

- When I get the document `2` with [`GET /indexes/:uid/documents/2`](https://docs.meilisearch.com/reference/api/documents.html#get-one-document)
```json
{
        "id": 2,
        "title": "Pride and Prejudice",
        "author": "J. Austen",
        "genre": "romance",
        "price": 3.5,
        "date": "1813"
}
```
-> `genre`, `title` and `price` have been unchanged
-> `date` has been added
-> `author` has been correctly updated

The [update route](https://docs.meilisearch.com/reference/api/documents.html#add-or-update-documents) has the expected behavior.
Did you check all your updates have been processed with [`GET /indexes/:uid/updates` route](https://docs.meilisearch.com/reference/api/updates.html#get-all-update-status)?

Maybe I did not understand your issue. Can you detail the step as I do so that I can exactly understand the bug your have.

**Comment by mrmaxonline** [comment]
Hi!

We are always using POST (not PUT) for update all data in document. And using ID as Guid value.

![image](https://user-images.githubusercontent.com/12570364/130394598-86931572-71b1-4b5a-a34d-eaec672bb3e4.png)

**Comment by curquiza** [comment]
Hello @mrmaxonline!
Can you give us the dataset and the steps you did to reproduce the bug, please? Otherwise we cannot help you.

**Comment by CaroFG** [comment]
Hi @mrmaxonline, are you sure MeiliSearch is using `DOCUMENTUID` as the primary key? You can check it by calling the [GET /indexes/:index_uid](https://dev.docs.meilisearch.com/reference/api/indexes.html#get-one-index) route, and checking the `primaryKey` in the response.

**Comment by mrmaxonline** [comment]
> Hi @mrmaxonline, are you sure MeiliSearch is using `DOCUMENTUID` as the primary key? You can check it by calling the [GET /indexes/:index_uid](https://dev.docs.meilisearch.com/reference/api/indexes.html#get-one-index) route, and checking the `primaryKey` in the response.

HI @CaroFG !
Result is:
{"uid":"rtea_documents_dev","name":"rtea_documents_dev","createdAt":"2021-08-11T06:22:02.659019145Z","updatedAt":"2021-08-24T08:29:50.226966702Z","primaryKey":"documentUid"}

**Comment by mrmaxonline** [comment]
> Hello @mrmaxonline!
> Can you give us the dataset and the steps you did to reproduce the bug, please? Otherwise we cannot help you.

Hi @curquiza !
Sorry, I can't bacause it countains closed data

**Comment by curquiza** [comment]
I understand. The issue is we cannot reproduce your bug without more context. Is the new release ([v0.21.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.21.0)) fixing your issue?
Do you have the same issue with one of previous versions? [v0.20.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.20.0) for example.

**Comment by mrmaxonline** [comment]
0.20 work fine.
0.21 release testing right now. I'll send a comment

**Comment by mrmaxonline** [comment]
Work fine.
