### ISSUE TITLE
`download-latest.sh` script for Windows users

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#1570]
Make the `download-latest.sh` script work for Windows users. At the moment it works only for Unix and Darwin

https://github.com/meilisearch/MeiliSearch/blob/63daa8b15ab21d40710a78dc4e09b5d0dac04711/download-latest.sh#L121-L134

**Comment by singh08prashant** [comment]
adding 'WindowsNT' should work?
@curquiza Tell me if I'm wrong here. I would like to take up this issue.

**Comment by curquiza** [comment]
Hello @singh08prashant 
Thanks for your involvement 🙂
Are you a windows user? I mean, do you have a machine to test the script?
Because we don't have Windows users at Meili and I just realized that is maybe not convenient at all to execute shell script on a Windows machine

**Comment by singh08prashant** [comment]
uname is not recognized on Windows.
uname on Cygwin gives CYGWIN_NT.
uname on Git Bash gives MINGW64_NT.

Instead of using  `os_name=$(uname -s)` on line 123, we can use $OSTYPE which is a [Built-In Shell Variable.](https://se.ifmo.ru/~ad/Documentation/Bash_Shell/bash3-APP-B-SECT-4.html)


If this variable works correctly in all the operating systems we support then we can drop a `uname` call and potentially speed up the script some more.
> 
> I'm still going to include a fallback to `uname` just in case the variable is empty for some reason.
> 
> 
> OS	$OSTYPE
> Linux	`linux-gnu`
> CYGWIN	`cygwin`

**Comment by singh08prashant** [comment]
Review for modifications, if any.
