### ISSUE TITLE
Processed time for queues increases with each batch

### ISSUE THREAD

**Issue by NAIJULU** [meilisearch/MeiliSearch#1667]
I installed the MeiliSearch using the guide for deployment in AWS ([https://docs.meilisearch.com/create/how_to/aws.html](https://docs.meilisearch.com/create/how_to/aws.html))

Note: but I reproduce the same issue with SO clean installation.  Because in community slack I get the recommendation of upgrade to v0.21.

I have 100K records to sync with the indexes, so I started to sync using the PHP SDK (1K docs by batch, but I already tested multiple amounts 25, even 10K per batch). At the beginning, everything looks normal, but with each process increase the time, and at some point, MeiliSearch accumulates thousands of unprocessed queues and in some cases server crashes and I need to restart the sync. Even if I restart the server and resume the sync the engine continues increasing the processing time. That behavior makes that some queue processes should be take up to 24 hours making it impossible to work in production with the engine. 

1. Installing MeiliSearch in Cloud server (AWS, Digital Ocean) - I get the same problem installing the engine without the community EC2 instance in AWS)
2. Starting to sync documents in 1K batches
3. Check the updates endpoint to see the increases. First 41 entries: [https://pastebin.com/P8xwUvzt](https://pastebin.com/P8xwUvzt)

**Expected behavior**
I want that MeiliSearch processes the queues at least a similar time in each chunk, Or that the engine process the queues in the fastest way. 

**MeiliSearch version:** v0.20.0 and v0.21.1

**Additional context**
Ubuntu 20.04 and Debian 10.3 (Using the community MeiliSearch AMI on AWS)
Laravel Scout and PHP SDK
Document example: [https://pastebin.com/Q2Amai3n](https://pastebin.com/Q2Amai3n)

Thanks for your help, I really like the concept and the way that you're doing with Meilisearch, I appreciate it if someone you have some advice or ways to fix that. I really want to use it in a production environment.  🖖

**Comment by curquiza** [comment]
Hello @NAIJULU 

The maximum payload size of MeiliSearch is 100Mb and [can be optionally increased](https://docs.meilisearch.com/reference/features/configuration.html#payload-limit-size). It means most of the dataset can be pushed with one call to the API.
I think your dataset of 100 000 documents can be pushed in one batch, or 2. If your machine is too small maybe 3 or 4 batches but no need to create small batches like this, I think. Again it depends on the size of your machine.

Some additional information:
- The increasing indexation time for each batch is expected: for each document you add, MeiliSearch has to re-order them into the DB and the more documents there are, the more time it takes for each batch.
- The indexation phase is crucial: MeiliSearch processes a lot of calculations to make the search more performant and more relevant during the query time. So, yes sometimes, it might take time 🙂
- However, we understand this indexation time is not convenient for our users, and that's why we are working hard on it. The v0.22.0 release of MeiliSearch (released next week) will reduce the indexation time without losing the search performance and relevancy. But, the time still will increase for each batch added.

**Comment by curquiza** [comment]
Closing this. Feel free to ask for re-opening if someone need some clarification
