### ISSUE TITLE
Improve the way of handling analytics

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#1784]
We currently send the analytics directly to Amplitude.
The alternative we want to implement is to push our analytics into [Segment](https://segment.com/?ref=nav) instead so that any other analytics tools like Amplitude can be plugged.

@meilisearch/docs-team: thanks to @gmourier, this issue will be updated with the related changes introduced with this PR, for instance, the exhaustive list of the data we send to Segment.

@meilisearch/integration-team: the SDKs will now be able to send information via the `User-Agent` header.

**Comment by gmourier** [comment]
One of the major advantages is that we can control what happens with a vigilance layer to guarantee the privacy of ours users. That is, if someone makes a mistake one day and sends data deemed personal, we are alerted and we can purge this data very easily.

The processes put in place to decide and implement a new metric should prevent this from happening, but prevention is better than cure.

Moreover, if a user decides to delete the data that we could have collected because he didn't deactivate the analytics, he will just have to provide us with his unique identifier generated at the first launch of the binary, so that we dispatch the deletions automatically from Segment and thus being confident that the data have been deleted in addition to ease this operation.

We are also working on a tracking plan that will allow us to instantly visualize everything that is tracked at a given time. We will remove metrics over time that have allowed us to improve the product and that are no longer useful.

**Comment by curquiza** [comment]
Here is the current re-work of the spec related to this issue: https://github.com/meilisearch/specifications/pull/84/files
