### ISSUE TITLE
Not-expected loss of performance during indexation (between v0.22.0 and v0.23.0)

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#1804]
Following: https://github.com/meilisearch/MeiliSearch/issues/1798

Seems like there is a loss of performance during indexation between v0.22.0 and v0.23.0

We need to investigate and fix this
@MarinPostma already started a first investigation about the part he updated between v0.22.0 and v0.23.0: https://github.com/meilisearch/MeiliSearch/issues/1798#issuecomment-941014601

**Comment by curquiza** [comment]
Hello @VinceG! This is not normal it takes that amount of time of 100K records
Do you push your documents one by one?

We always recommend pushing your documents to MeiliSearch by batch and not one by one. The maximum payload size of MeiliSearch is 100Mb and [can be optionally increased](https://docs.meilisearch.com/reference/features/configuration.html#payload-limit-size). It means most of the dataset can be pushed with one call to the API.

**Comment by VinceG** [comment]
@curquiza we have more, but right now we just tried to index 100K and its still going.

we use Laravel, and Laravel Scout
https://laravel.com/docs/8.x/scout#batch-import

it seems like it does batching but since we only have 550 updates enqueued

it does send over 200 records at a time but i don't think it reaches 100MB 

any idea what i can do to troubleshoot? 

thank you.

**Comment by bb** [comment]
Thanks for transferring this here, @curquiza.

Looking at the comments above, there seem to be multiple discussions ongoing. I think the primary goal here is preventing regressions, i.e. making sure that in newer versions, things stay at least as fast as they were in an older version.

Here's some overview from my data. It's not really comparable except within a row due specific machines, OS, etc... and in general due to small sample size.

<table>
<tr>
	<th>
	<th>0.19.0
	<th>0.20.0
	<th>0.21.1
	<th>0.22.0
	<th>0.23.1
<tr>
	<td>~ 6k records, 19MB JSON, Docker Mac<br>some settings regarding filterable attributes
	<td>
	<td>
	<td>
	<td>~ 3 s
	<td>~ 34 s
<tr>
	<td>~ 6k records, 19MB JSON, Docker Mac<br>default settings (nothing specified)
	<td>
	<td>
	<td>
	<td>~ 37 s
	<td>~ 180 s
<tr>
	<td>~ 6k records, 19MB JSON, Docker Linux<br>default settings (nothing specified)
	<td>~ 6.1 s
	<td>~ 5.7 s
	<td>~ 26.7 s
	<td>~ 20.8 s
	<td>~ 16.1 s
<tr>
	<td>~ 800k records, Docker Linux
	<td>~ 518 s
	<td>~ 396 s
	<td>~ 551 s
	<td>~ 480 s
	<td>~ 350 s
</table>

So, there's a clear jump between 0.20 and 0.21, especially on small data sets. However, OTOH the service became much more responsive during indexing in 0.21+.

On Linux Meilisearch is getting faster and faster, but on Docker for Mac (which is actually Linux running in a VM) it gets worse from 0.22 to 0.23, at least for rather small data sets.

The observation which lead to this ticket is the jump from 0.22 to 0.23 which I observe in Docker for Mac but not on Linux. Maybe it's related to Docker for Mac's poor disk IO performance? Maybe it's too little RAM (or even swapping) - Docker Desktop is configured to 6GB) or too few cores (configured 5) where the same test on the Linux host has plenty of RAM and 12 cores.
Any hints what I could look further or what to try?

**Comment by bb** [comment]
I just provided @ManyTheFish with my test dataset and my settings via Slack.

The test is a fresh db folder, Meilisearch running in Docker for Mac and three calls:

1. settings
2. delete_all_documents
3. add_documents (all at once)

In the last runs comparing 0.22.0 vs 0.23.1, I had on this specific dataset, I had 14 times slower indexing (1.6 s → 22.7 s) and 3x slower uploads (5 s → 17s). 

The indexing time can be observed by looking at the `duration` field of the `DocumentsAddtion` request.
The uploading time can be seen by looking at the difference of `enqueuedAt` between `ClearAll` and `DocumentsAddition`. The calls are directly one after the other in a ruby script where the documents were already a prepared array of hashes which just needed to be serialized.

### 0.22.0 status updates

(note: updateIDs are higher here because I had same settings call multiple before)

```json
  {
        "status": "processed",
        "updateId": 5,
        "type": {
            "name": "ClearAll"
        },
        "duration": 0.015,
        "enqueuedAt": "2021-10-13T20:24:41.363020307Z",
        "processedAt": "2021-10-13T20:24:41.386188054Z"
    },
    {
        "status": "processed",
        "updateId": 6,
        "type": {
            "name": "DocumentsAddition",
            "number": 5942
        },
        "duration": 1.605,
        "enqueuedAt": "2021-10-13T20:24:46.195683759Z",
        "processedAt": "2021-10-13T20:24:47.810306346Z"
    }
```

### 0.23.1 status updates
```json
    {
        "status": "processed",
        "updateId": 1,
        "type": {
            "name": "ClearAll"
        },
        "duration": 0.005,
        "enqueuedAt": "2021-10-13T20:26:25.268266946Z",
        "processedAt": "2021-10-13T20:26:25.277046910Z"
    },
    {
        "status": "processed",
        "updateId": 2,
        "type": {
            "name": "DocumentsAddition",
            "number": 5942
        },
        "duration": 22.701999999999998,
        "enqueuedAt": "2021-10-13T20:26:42.306488448Z",
        "processedAt": "2021-10-13T20:27:05.022123113Z"
    }
```

**Comment by mgralikowski** [comment]
The same observation with 0.24.0 and DigitalOcean droplet.

First new documents take less than a second. Batch inserts take ~3 seconds. When we have more data like 100+ every next insert takes more and more time. For now, it is more than 1 minute :( Any updates about it? In this situation, we will be forced to change a search driver, because users can't wait minutes to see their records.

No difference between the 2 or 4 CPU DO droplets.

**Comment by curquiza** [comment]
Hello everyone reading this issue.

The issue regarding the loss of performance between v0.22.0 and v0.23.0 has been fixed. Since it's the specific purpose of this issue, I close it.

However, for anyone having issues in general with indexation performance, please, refer to [this discussion](https://github.com/meilisearch/meilisearch/discussions/2131). Your feedback will be really appreciated 🙂
