### ISSUE TITLE
Meilisearch on 20 million records

### ISSUE THREAD

**Issue by foremtehan** [meilisearch/MeiliSearch#1820]
Hi there, I'm using your wonderful app with laravel scout, I imported 20 million records to test it out and i faced some issues.

My table contains transcript lines, The problem is it doesnt scan the whole table to get the appropriated results.

For example i searched for `Leela kicked` which is inserted in the end of the table:

![image](https://user-images.githubusercontent.com/53290883/137588905-5c7490a4-9dc8-4971-aa83-31b8e6aaac7c.png)

```php
Title::search('Leela kicked')->get();
```

results:

```json
{
  "hits": [
    {
      "id": 227325,
      "line": "Leila",
      "start_at": 1508
    },
    {
      "id": 248415,
      "line": "Leila, why isn't your face covered?",
      "start_at": 4179
    },
    {
      "id": 248420,
      "line": "Leila! Stop it",
      "start_at": 4211
    },
    {
      "id": 335126,
      "line": "Leila is going to be very happy",
      "start_at": 592
    },
    {
      "id": 335699,
      "line": "I never wanted to kill Leila",
      "start_at": 4470
    },
    {
      "id": 248410,
      "line": "Are you going to work here with Leila?",
      "start_at": 4158
    },
    {
      "id": 248213,
      "line": "Hello, Leila!",
      "start_at": 2638
    },
    {
      "id": 596443,
      "line": "Hadil, Leila, come take Miral",
      "start_at": 2367
    },
    {
      "id": 248038,
      "line": "I'm so sorry, Leila. I really am",
      "start_at": 1397
    },
    {
      "id": 248543,
      "line": "Hello? Hi, Aunt Leila",
      "start_at": 5259
    },
    {
      "id": 248234,
      "line": "I don't like it, but it's OK. Leila!",
      "start_at": 2743
    }
  ],
  "nbHits": 11,
  "exhaustiveNbHits": false,
  "query": "Leela kicked",
  "limit": 20,
  "offset": 0,
  "processingTimeMs": 5
}
```

As you can see it didnt find the record `Leela kicked me out`, it looks like it only scan records up to 1million, So am i missing something ? or maybe it didint import all the documents ? how can i ensure that the engine has all the 20 million records ?

**Comment by curquiza** [comment]
Hello @foremtehan 
The upload of documents into MeiliSearch leads to a complex indexation that might take time.
When adding your documents into MeiliSearch you get an `updateId` related to your action. This [answer in the FAQ](https://docs.meilisearch.com/faq.html#i-did-a-call-to-an-api-route-and-i-only-got-an-updateid-as-a-response-what-does-it-mean) can make you better understand.

However, 20M of documents is a LOT in MeiliSearch:
- The more there are documents, the less the engine is performant and relevant. Are you sure you want to add all your documents to MeiliSeach? Only the documents you want to retrieve should be added.
- This huge amount of documents might take time to be indexed, here is an [answer in the FAQ](https://docs.meilisearch.com/faq.html#i-did-a-call-to-an-api-route-and-i-only-got-an-updateid-as-a-response-what-does-it-mean) that might help you speed up the indexation

**Comment by mech** [comment]
But after the indexing has finished after those hours, is the search query performance up to your mark? Like within a few millisecond? I am in the process if indexing just 1 million records and the search query already took 3 seconds to return 🤔

**Comment by curquiza** [comment]
Hello @mech 
which version of Meilisearch do you use?

**Comment by mech** [comment]
Hi I am using meilisearch:v0.30.5 Docker.

When I import around 60,000 records using the new pagination strategy, the page=1 will take around 3 seconds to complete.

Although my document is quite heavy to be honest. It is a candidate documents where I index their educations, experiences and skill sets.

Does a heavily indexed documents like this not advisable to use Meilisearch. Is there any best practice to a single document's size that we need to stay close within in order for a million record to still be comfortably query?

**Comment by mech** [comment]
Yes I did. Using the following Ruby code:

```ruby
CandidateProfile.search(
    query: "",
    page: 1,
    hits_per_page: 30,
    facets: ["degree", "generation"],
)
```

The query initially is empty string for me to take advantage of placeholder search.

**Comment by curquiza** [comment]
Sorry for the delay @mech!

It's really slow because you increased A LOT `maxTotalHits`. Default one is `1000`.

See the [API reference](https://docs.meilisearch.com/reference/api/settings.html#update-pagination-settings) and our [guide about numbered page selector pagination](https://docs.meilisearch.com/learn/advanced/pagination.html#numbered-page-selectors)  

<img width="917" alt="Capture d’écran 2023-02-07 à 18 00 14" src="https://user-images.githubusercontent.com/20380692/217312540-3e4db35a-6279-4e81-b1b5-811092e72c5e.png">

[Contrary to Algolia](https://www.algolia.com/doc/api-reference/api-parameters/paginationLimitedTo/#usage-notes), we don't want to set a maximum limit for this setting to let people do what they want (some people are ok with slowness, and prefer exhaustive results).

Why is it slow?
When you use `page`, you ask Meilisearch to sort ALL your documents, and not the first most relevant one. Since in your case, there are half a million documents to sort, this leads to this latency. 

My question is: do you really need to let your users access the last result of the search? I'm asking because maybe your need can be solved differently with another Meilisearch feature (like the [sort](https://docs.meilisearch.com/learn/advanced/sorting.html#sorting)?)

I recommend 
- you decrease `maxTotalHits`
- or you don't use `page` but `offset`/`limit` instead. However, you will not be able to access directly to the last page. I think you are using our rails integration for meilisearch ([meilisearch-rails](https://github.com/meilisearch/meilisearch-rails)), so you can use them with `MyModel.search('query', limit: xx, offset: xx)`

Here is a guide in [our documentation about pagination](https://docs.meilisearch.com/learn/advanced/pagination.html#search-result-pagination).

Hope it will help you

**Comment by mech** [comment]
Yup understand the page vs relevancy part. I will look for another solution to it. Currently I am doing SQL query on the very initial first page=1. Then only when there's query will I make use of Meilisearch to display the relevant results. I think this approach might be the best for both world.
