### ISSUE TITLE
Import dumps in docker instance got os error 16

### ISSUE THREAD

**Issue by OathMoon** [meilisearch/MeiliSearch#1833]
**Describe the bug**
when use MeiliSearch docker instance with data volumes to import dumps get os error 16:
```bash
docker run -d --name meilisearch -p 7700:7700 -v /root/meilisearch/data:/data -v /root/meilisearch/dumps:/dumps getmeili/meilisearch:v0.23.1 ./meilisearch --db-path /data --import-dump /dumps/20211020-04504144.dump
```

and if without data volumes is works well:
```
docker run -d --name meilisearch -p 7700:7700 -v /root/meilisearch/dumps:/dumps getmeili/meilisearch:v0.23.1 ./meilisearch --import-dump /dumps/20211020-04504144.dump
```
but it is not convenient to direct import dump to db path while db path is a volume, needs docker cp data to local directory.

is this just as designed?

**MeiliSearch version:** [v0.23.1]

**Comment by OathMoon** [comment]
Hi @curquiza 
`-v /Users/curquiza/Documents/MeiliSearch/data.ms:/data.ms` mount host path `data.ms` for container and arguments `--db-path /data` makes `/data` as db path, the db path is still in container, and host path did not used for importing, is this the different can not reproduce issue?

**Comment by curquiza** [comment]
Hello again @OathMoon 
I realized I might have missed the right command, I should have typed `--db-path /data.ms` instead of `--db-path /data`, sorry for that.

Now I get:

```bash
docker run --rm -p 7700:7700 -v /Users/curquiza/Documents/MeiliSearch/data.ms:/data.ms -v /Users/curquiza/Documents/MeiliSearch/dumps:/dumps getmeili/meilisearch:v0.23.1 ./meilisearch --db-path /data.ms --import-dump /dumps/20211102-191118178.dump

[2021-11-02T19:12:22Z INFO  meilisearch_lib::index_controller::dump_actor] Loading dump from 2021-11-02 19:11:18.178619 UTC, dump database version: 0.23.1, dump version: V3
[2021-11-02T19:12:22Z INFO  meilisearch_lib::index_controller::dump_actor::loaders::v3] Loading dump from 2021-11-02 19:11:18.178619 UTC, dump database version: 0.23.1, dump version: V3
[2021-11-02T19:12:22Z INFO  meilisearch_lib::index_controller::dump_actor::loaders::v3] Loading indexes.
[2021-11-02T19:12:22Z WARN  meilisearch_lib::index_controller::dump_actor] Overwriting database at /data.ms
Error: Resource busy (os error 16)
```

Do you have the same error?

**Comment by mhhakim** [comment]
I am having the same issue in container. I imported the dump in the host machine successfully then used than data to create container.

**Comment by OathMoon** [comment]
@curquiza Yes, the same error.

**Comment by curquiza** [comment]
Hello @mhhakim and @OathMoon 
This is indeed not expected, we are investigating on it. SOrry for the issue.

What is the machine on which you are using docker? Is it MacOs?

**Comment by mhhakim** [comment]
@curquiza mine is Linux arm64

**Comment by irevoire** [comment]
Sorry I've been quite slow to introspect this bug.

Basically, what causes the bug is these lines:
https://github.com/meilisearch/MeiliSearch/blob/f56989e46e939077dcff18a07f957f30eb8adb20/meilisearch-lib/src/index_controller/dump_actor/mod.rs#L228-L235

When meilisearch notices you already have a `data.ms` directory, it tries to delete it, but since it's the root of your docker volume, we can't delete it.

I implemented a first fix that delete the inside of the `data.ms` instead of deleting the directory directly, but now I have another issue. Since we are trying to move a file between your docker volume and your host partition we are trying to move something between two partitions and this is not allowed.

I'll continue to work on this tomorrow.
