### ISSUE TITLE
MeiliSearch removes indexes when `data.ms` is not compatible

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#1840]
Steps to reproduce
- Start MeiliSearch v0.22.0
- Add documents
- Stop MeiliSearch v0.22.0 and run MeiliSearch v0.23.0 using the same `data.ms`

-> MeiliSearch starts without any error, but should not, and remove the indexes in `data.ms`

MeiliSearch should display the following error
```
Cannot open database, expected MeiliSearch engine version: X.X.X, current engine version Y.Y.Y
```
at it was before, and should not start if data.ms is not compatible without removing the indexes

**Comment by jaydrogers** [comment]
Wanted to share this experience (which might be related):

### Our environment
* Running Meilisearch on Ubuntu 20.04 with Docker using the "latest" image tag (`getmeili/meilisearch`)
* Our `data.ms` database is mounted via Docker Volumes

### What happened
* We originally built indexes on `v0.23.1`
* Everything worked great
* Our Meilisearch instance automatically updated to `v0.24.0`
* All of our indexes disappeared

### How we were able to get our indexes back
* We forced our image to go back to **v0.23.1**

I am also going to cc @danpastori on this issue since I am the sysadmin and he is the developer who helped me troubleshoot this 😁

Any additional information on this, please let me know!
