### ISSUE TITLE
Windows: MeiliSearch tries to allocate 100Gb of disk space

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#1871]
Following https://github.com/meilisearch/MeiliSearch/discussions/1869

This bug should have been removed since v0.21.0 which works with the version of lmdb that should remove this hard memory allocation.

@Kerollmops can you check the correct version of lmdb is used?

Is there anyone having the same issue with a MeiliSearch version >= v0.21.0?

**Comment by Kerollmops** [comment]
I checked the versions of LMDB we use in both MeiliSearch and milli, [we use the v0.12.1 of heed](https://github.com/meilisearch/MeiliSearch/blob/c32f13a9091afe0b6de6cc8fc063ca806dcd976f/meilisearch-http/Cargo.toml#L42) which [uses the version 0.9.70 of LMDB](https://github.com/meilisearch/lmdb/blob/780761f5c0fee69ef4a91c96d0fe2b8cd9e90b3b/libraries/liblmdb/lmdb.h#L227-L232). The issue with [the way LMDB grows the file on windows](https://bugs.openldap.org/show_bug.cgi?id=8324) should [have been fixed in version 0.9.17](https://bugs.openldap.org/show_activity.cgi?id=8324) and we use 0.9.70, so we are way ahead of the patch.

I am absolutely not sure why this bug continues to exist.

**Comment by curquiza** [comment]
Thanks @Kerollmops 
I let the issue open in case someone has the same issue with Windows. I will close it after some time if we don't get any other feedback

**Comment by curquiza** [comment]
Due to lack of feedback regarding this issue, I close it

Feel free to ask to reopen if needed
