### ISSUE TITLE
Windows: error on adding documents to MeiliSearch

### ISSUE THREAD

**Issue by monaheinz** [meilisearch/meilisearch#1899]
**Describe the bug**
On document creation the error `'tokio-runtime-worker' panicked at 'the allocator is unable to allocate that much memory'` occurs. 
```
[2021-11-12T10:40:49Z TRACE meilisearch_lib::index::updates] performing document addition
[2021-11-12T10:40:49Z thread 'TRACEtokio-runtime-worker actix_server::worker' panicked at ']the allocator is unable to allocate that much memory
```

**To Reproduce**
1. make sure that more than 1/3 of your total memory is used
2. run meilisearch v0.22.0 or 0.23.1 on windows (I used `--max-index-size 2684354560 --max-udb-size 2684354560 --db-path ".\meilisearch.ms" --log-level "TRACE"` as options)
3. add a document via the API
4. the error should occur in the log

**Idea how to fix**
I found out, that the max Memory for the indexer is set to 2/3 of the total memory of the machine. But this memory wasn't available in my case (total memory: 10GB, available memory: ~4GB, max memory used by MeiliSearch: ~7GB). 
I am true beginner to Rust but that is how I was able to fixe it:
* add new `structopt` to be able to pass a max memory option
```rust
//option.rs
pub struct Opt {
    /* more options */
    #[structopt(long, env = "MEILI__MAX_MEMORY", default_value = "1342177280")]
    pub max_memory: String,
}
```
* set that value to `IndexerOpts`
```rust
//main.rs
#[actix_web::main]
async fn main() -> anyhow::Result<()> {
    let mut opt = Opt::from_args();

    let env_maxmemory = &(opt.max_memory);
    opt.indexer_options.max_memory = MaxMemory::from_str(env_maxmemory).expect("expected max memory param");

    /* ... */
}
```

**MeiliSearch version:** [v0.22.0] [v0.23.1]

**Additional context**
OS: Windows

**Comment by curquiza** [comment]
Hello @monaheinz 

Thanks for the report and the investigation

I just opened a ticket on the product's side to take your feature request into account, I mean, adding a new setting to set the maximum memory allocated, see https://github.com/meilisearch/product/discussions/306

Here are some current workaround since you cannot use MeiliSearch perfectly on Windows:
- use Docker, see [this link](https://docs.meilisearch.com/learn/getting_started/installation.html#download-and-launch) with "Docker" tab
- We have [one-click deploy for DigitalOcean](https://docs.meilisearch.com/create/how_to/digitalocean_droplet.html) and we provide also other easy ways to deploy MeiliSearch using several cloud providers, see [this list of our guides](https://docs.meilisearch.com/create/how_to/).

Sorry again for the inconvenience!

**Comment by curquiza** [comment]
Closed by https://github.com/meilisearch/meilisearch/pull/2267, will be released in v0.27.0 :)

**Comment by dzcpy** [comment]
Can you please release 0.27.0? Need to use it on Windows but it doesn't work. Many thanks! @curquiza

**Comment by curquiza** [comment]
Hello @dzcpy!

v0.27.0 is planned for May 9th. In the meantime, you can test our RC (release candidates) -> https://github.com/meilisearch/MeiliSearch/releases

**Comment by dzcpy** [comment]
@curquiza Ah, thanks very much for your reply!
