### ISSUE TITLE
Stack overflow error with huge list of filters

### ISSUE THREAD

**Issue by G3z** [meilisearch/meilisearch#1967]
**Describe the bug**
meili 0.24.0 in docker crashes with stack overflow error
biggest index has 2k documents locally and 56k on AWS

**Expected behavior**

**Screenshots**
```meili_1      | [2021-12-03T13:44:55Z INFO  actix_server::builder] Starting 4 workers
meili_1      | [2021-12-03T13:44:55Z INFO  actix_server::builder] Starting "actix-web-service-0.0.0.0:7700" service on 0.0.0.0:7700
meili_1      | [2021-12-03T13:47:29Z INFO  actix_web::middleware::logger] 172.18.0.8:42056 "POST /indexes/contents/search HTTP/1.1" 200 109 "-" "GuzzleHttp/7" 0.034277
meili_1      | [2021-12-03T13:47:29Z INFO  actix_web::middleware::logger] 172.18.0.8:42056 "POST /indexes/downloads/search HTTP/1.1" 200 108 "-" "GuzzleHttp/7" 0.001068
meili_1      | 
meili_1      | thread 'tokio-runtime-worker' has overflowed its stack
meili_1      | fatal runtime error: stack overflow
```

**MeiliSearch version:** [v0.24.0]

**Additional context**
this happens on docker mac (8gb of ram assigned to docker)
and on AWS on docker (8gb of ram) but it's resolved when using a 16gb instance

----

EDIT from @curquiza

Steps to add a limit to the `filter` parameter (2000 of depth)

- [x] Merge PR this PR adding a limit: https://github.com/meilisearch/milli/pull/421
- [ ] Release milli
- [ ] Integrate the new version of milli into MeiliSearch

**Comment by G3z** [comment]
i set MEILI_LOG_LEVEL to DEBUG
and I found out that my query has 14361 filters like `OR account_ids=xxx` (`account_ids` is an array of ids)
I use this to filter out the documents a user does not have access to, but if they have a lot of them i think it crashes

the full log is here:
https://gist.github.com/G3z/932a372be6bdf7cd1122bcb3e7bdb7c7

**Comment by Kerollmops** [comment]
Hey @G3z,

Thank you for the report, while I am debugging that and will surely add a limit to the number of filters we accept you can make your request work by rewriting it and [use filter ranges](https://docs.meilisearch.com/reference/features/filtering_and_faceted_search.html#creating-filter-expressions-with-strings) i.e. `account_ids 1 TO 14361`.

**Comment by G3z** [comment]
I get that this is an edge case.
Filter ranges can be useful but since those are ids i don't think i can group them together safely.
Multi-tenancy doesn't seems useful since every user would have different sets of account-ids and I would need a tenant for every user.

**Comment by Kerollmops** [comment]
> Filter ranges can be useful but since those are ids i don't think i can group them together safely.

I understand but if you try your best you will be able to query the engine without it to stack overflow and answer your query instead. Another possibility would be to increase the stack size but that can make the program slower and I don't know much about the exact size the stack should be to answer your query. I didn't try that so not sure it works.

To reduce the size of your filter you could sort your `account_ids` and then group them while they are in a row by using the `TO` operator, once the runs break, start a new `TO` operation, and so on. The query you tried with 14361 operations would be reduced to just one `TO` operation.

> Multi-tenancy doesn't seem useful since every user would have different sets of account-ids and I would need a tenant for every user.

I'm not sure how we can help you with your use case. Do you have any idea?

**Comment by gmourier** [comment]
Hi @G3z

FYI, we designed the tenant token feature so that you can issue specific tokens per end user.

For example on the backend when the user logs into your system (this is an example) you will be able to generate a specific token with forced filters.

For user 1: you could define forced filters like `account_ids = 1 and account_ids = 2`.

For user X: you can define forced filters like `account_ids = 5`.

The advantage is that you won't have to overload each end-user search query on your side by making an additional exchange before serving search results from MeiliSearch.

Here the user has access to a lot of accounts actually. Shouldn't we group all these accounts_ids by a less sparse value to avoid exceeding the limit? Like adding a company_id for example in your documents that already contain accounts_ids? This is just an example and an idea.

Translated with www.DeepL.com/Translator (free version)

**Comment by G3z** [comment]
thanks both for the answers, I wanted to report this but I noticed this problem only for one edge case, I'll work around that while waiting for multi tenancy: now that you explained the reasoning behind it, it makes sense.
TY

**Comment by curquiza** [comment]
Hello @G3z 
Multitenancy should solve your issue, and should be released during Q1 of 2022! We are currently working on it!

Thanks for your report, we plan to put limit to our `filter` parameter to avoid this panick again

**Comment by curquiza** [comment]
FYI, I've updated the issue description with the needed steps @Kerollmops

**Comment by OathMoon** [comment]
I meet the same issue and `Multitenancy` looks good. TY

**Comment by gmourier** [comment]
Thank you! I don't think that multi-tenancy token as such will solve the intrinsic problem of having so many filters for a query.

There are some solutions we could consider: 

- Have an operator that allows you to reduce the number of filters to be expressed for the same filter rule and thus reduce the depth of the syntax tree.
- Develop an optimizer that does this automatically?

**Comment by curquiza** [comment]
Fixed by https://github.com/meilisearch/meilisearch/pull/2005 that bump the milli dependency to [milli v0.22.0](https://github.com/meilisearch/milli/releases/tag/v0.22.0) containing the fix of this issue 🙂

The bug fix will be released in Meilisearch v0.26.0.

**Comment by guimachiavelli** [comment]
@curquiza: if I follow this and the [milli PR](https://github.com/meilisearch/milli/pull/421/files#diff-a1253bb15ffe3a75231197ec3f7905987e24a10458dd5255f5fd4a75fbafe192R19) correctly, part of the fix is introducing a limit of 2000 filters on the same query, right? 

If that is the case, the @meilisearch/docs-team would like to document this on our "Known limitations" article.

**Comment by curquiza** [comment]
Oh yes! Sorry I forgot this page!
Thank you gui for the report, I add the label immediately and I ping you @meilisearch/docs-team
