### ISSUE TITLE
Auto-batching documents

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#1985]
Related to this spec: https://github.com/meilisearch/specifications/pull/96
The spec is still a WIP

The goal of this internal feature is to gather the small batches of the user's documents in one batch to decrease the indexation time.

**Comment by curquiza** [comment]
This might impact the @meilisearch/docs-team, depending on the impacts we will notice. This issue will keep you informed about the improvements.

**Comment by curquiza** [comment]
Fixed by #2005 🎉 

More information here in this dedicated discussion: https://github.com/meilisearch/meilisearch/discussions/2070

**Comment by guimachiavelli** [comment]
Is there any significant difference between the spec and the dedicated discussion? Can we use both when writing the documentation for this experimental feature?

**Comment by MarinPostma** [comment]
@curquiza I thought we'd wait a bit before documenting this?

**Comment by curquiza** [comment]
@gmourier knows better than me what we should document regarding this experimental feature.
But yes for me, as far as I understand, no need to document this since it's completely experimental. Only a link to the discussion would be welcome in the documentation :)
@gmourier, can you confirm? Maybe there were some changes regarding this.

**Comment by gmourier** [comment]
Hi 👋

This is an ongoing [discussion](https://github.com/meilisearch/documentation/discussions/1365#discussioncomment-1955095)! I think we should keep it very simple by using the Github discussion links since it's experimental but the chosen format belongs to the documentation team.

@guimachiavelli, the two are almost identical in my opinion. The discussion may be easier to read.

**Comment by guimachiavelli** [comment]
The @meilisearch/docs-team is still discussing whether/how/when to include this into the docs, so my question for the moment was mostly so I could establish up-to-date sources.

After discussing a bit with the team, I realised I wasn't sure about the schedule for this feature. Do we call it experimental because it's on the pre-release but might not be on the official release? Or is it possible we include it on v0.26 and keep its experimental status?

**Comment by gmourier** [comment]
It will be in v0.26.0 release with the experimental flag. Experimental is mostly to say that it could evolve strongly to a non-experimental implementation or even be removed in a future version.

**Comment by guimachiavelli** [comment]
We have decided we want to provide some documentation on the docs site. Our goal is to acknowledge the existence of this experimental feature, and give users of the docs a quick intro and instructions on how to activate it.

This mini-guide will also include a very explicit link inviting users to check #2070 so they know where to go next in case they experience issues, want more in-depth info, or want to give us feedback.
