### ISSUE TITLE
_geoPoint sorting ignores ranking rules

### ISSUE THREAD

**Issue by ahmedelhori** [meilisearch/MeiliSearch#2081]
**Describe the bug**
when i sort with _geoPoint and for example 2 locations have the exact same coordinates, the ranking rules i set are ignored

**To Reproduce**
I use Laravel with the Scout package and i have the following ranking rule:

`["sort", "words", "typo", "proximity", "attribute", "exactness"]`

And the following request:
```
curl -X POST 'http://localhost:7700/indexes/something/search' \
  -H 'Content-type:application/json' \
  --data-binary '{ "sort": ["_geoPoint(48.8583701,2.2922926):asc", "published_at:desc"] }'
```

**Expected behavior**
I expect that if coordinates are the same, "published_at:desc" should be used next for the ranking

**MeiliSearch version:**
v0.24.0

**Additional context**
Running on Debian with docker.

I also tried adding the "published_at:desc" attribute after "sort" in the ranking rules, but to no avail.

I'm not sure if this is a bug, a feature missing or if i'm doing something wrong.

**Comment by curquiza** [comment]
Hello @ahmedelhori 

This is a known issue with the geosearch. We already opened a ticket on the product side https://github.com/meilisearch/product/discussions/264
I close this issue then in favor of this discussion. We need to add a setting to MeiliSearch, and not make them as default behavior, since this is not a behavior that all the users want.

Sorry for the inconvenience. You might want to try to not put the `sort` criterion at first to avoid this behavior.
