### ISSUE TITLE
Error: Version file is missing or the previous MeiliSearch engine version was below 0.24.0. Use a dump to update MeiliSearch.

### ISSUE THREAD

**Issue by mohsenMJ** [meilisearch/meilisearch#2127]
**Describe the bug**
Just installed meilisearch on my ubuntu 20.04 machine and this error happend. 

**To Reproduce**
echo "deb [trusted=yes] https://apt.fury.io/meilisearch/ /" | sudo tee /etc/apt/sources.list.d/meilisearch.list
sudo apt update
sudo apt install -y meilisearch-http
meilisearch --version
sudo nano /etc/systemd/system/meilisearch.service
# paste this information in file 
[Unit]
Description=MeiliSearch search engine
After=network.target
 
[Service]
ExecStart=/usr/bin/meilisearch --http-addr 0.0.0.0:7700 --env production --master-key pwd123
Restart=always
 
[Install]
WantedBy=multi-user.target
--------------------------------------------
sudo service meilisearch start

at this point it shows failed to start with the following message : 
Error: Version file is missing or the previous MeiliSearch engine version was below 0.24.0. Use a dump to update MeiliSearch.

**Expected behavior**
Activate Meilisearch as expected

**Meilisearch version:** 0.25.2

please help !

**Comment by Kerollmops** [comment]
Hey @mohsenMJ,

Was there another version of Meilisearch running on your machine?

If so, please follow [this guide to migrate](https://docs.meilisearch.com/learn/advanced/updating.html#update-to-the-latest-meilisearch-version) your previous version of the engine.

If not, or if you don't care about the previous content and want to upload all of the documents again, please delete the content at the database path i.e. default is `data.ms`.

**Comment by mohsenMJ** [comment]
Thank you so much

 
Yes, I already had an older version of meilisearch so I followed your link and tried to install version 0.24.0 and bingo , it was the same as before and ran successful. 

apt-get install meilisearch-http=0.24.0

You saved Me ...

**Comment by curquiza** [comment]
Hello @mohsenMJ!
Sorry for the inconvenience, I close the issue then. Tell me if we need to re-open :)

**Comment by dungnh** [comment]
Hi @curquiza,

I got exactly this issue when reinstalling MeiliSearch 0.25.0 on Linux/Ubuntu 20.04 (LTS) x64.

```
meilisearch.service - Meilisearch
     Loaded: loaded (/etc/systemd/system/meilisearch.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-03-10 09:21:22 UTC; 5s ago
    Process: 295624 ExecStart=/usr/bin/meilisearch --http-addr 127.0.0.1:7700 --env production --master-key 1234567890 (code=exited, status=1/FAILURE)
   Main PID: 295624 (code=exited, status=1/FAILURE)

systemd[1]: Started Meilisearch.
meilisearch[295624]: Error: Version file is missing or the previous MeiliSearch engine version was below 0.24.0. Use a dump to update MeiliSearch.
systemd[1]: meilisearch.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: meilisearch.service: Failed with result 'exit-code'.
```

Even I did remove the old version and delete the data.ms. Then make a fresh install with the latest version and I cannot run it as a service. I'm able to run it manually only. 

Could you please help?

**Comment by dungnh** [comment]
Thanks @curquiza 

I have checked the data.ms on my server and deleted all of them. So now it works fine. 
Thank you a lot.

**Comment by warmwhisky** [comment]
I have same issue, but I need to use `0.27.2` but it says `Expected Meilisearch engine version: 0.29.1`

I am using docker and cannot find where the `data.ms` file resides? Any ideas?

**Comment by curquiza** [comment]
Hello @warmwhisky

We will answer you in this discussion instead -> https://github.com/meilisearch/meilisearch/discussions/2958

**Comment by kokoshneta** [comment]
I installed Meilisearch on my localhost via Homebrew, and then forgot that I’d installed it through Homebrew. I recently did did a `brew upgrade`, which accidentally upgraded Meilisearch from 0.28.1 to 0.29.2.

That means when I attempt to start Meilisearch, I get this error message:

> Error: Expected Meilisearch engine version: 0.28.1, current engine version: 0.29.2. To update Meilisearch use a dump.

I can’t really “use a dump” as suggested, since making a dump requires being able to run Meilisearch in the first place… bit of a catch-22.

On the other hand, I don’t have any particular need for 0.29, so I’d be perfectly happy to just downgrade to 0.28 again. Trouble is I don’t seem to be able to in any reasonably easy manner:

- [only 0.29.2 is available on Homebrew](https://formulae.brew.sh/formula/meilisearch#default)
- the cURL install option in the Meilisearch docs only relates to the latest stable version and doesn’t say anything about how one might install earlier versions
- downloading the macOS file from [the release assets](https://github.com/meilisearch/meilisearch/releases/tag/v0.28.1) just gets me a file with no extension that macOS thinks is a text file – whatever it actually is (binary?), it’s seemingly not an executable

The only way I’ve managed to find that enabled me to access my indexed data is to uninstall the Homebrew version, clone the Git repo, use `git describe` to get the readable name of the commit for release v0.28.1, checkout that commit, install Rustup and then build Meilisearch from source.

That’s not exactly user-friendly. Surely there must be some easier way of not losing all your indexed material if you accidentally update Meilisearch?

It would be useful if the documentation could mention how to install earlier versions without compiling from source (assuming that isn't the only way, of course) – or at the very least include a warning that if you install it via a package manager like Homebrew, you should make sure to `brew pin meilisearch` as well, so accidental auto-updates won’t happen.

**Comment by curquiza** [comment]
Hello @warmwhisky 

Thanks for your feedback this is really appreciated

I've opened an issue on our side to provide multiple versions Meilisearch with Homebrew: https://github.com/meilisearch/meilisearch/issues/3120

I've also opened an issue on the documentation side to let them know about your need: https://github.com/meilisearch/documentation/issues/2015

For your information, until we provide multiple versions with Homebrew, here are the current solutions
- compile from source: git checkout to the tag and compile -> you already know this possibility
- download the binary directly from [the GitHub assets](https://github.com/meilisearch/meilisearch/releases)
- use docker and specify the specific tag instead of `latest`

Thanks again for your feedback

**Comment by kokoshneta** [comment]
Thanks for the reply! Good to know it’s not just me being dumb, at least. :-)

> * download the binary directly from [the GitHub assets](https://github.com/meilisearch/meilisearch/releases)

This would have been my preferred option – in fact, I _did_ download the Mac binary – but (probably just due to my own ignorance) I couldn’t figure out what to actually do with that binary. I tried `chmod 755`-ing it to make it executable, but that just gave me the error message `zsh: killed     meilisearch` when I ran it, so I figured I’d need to do something else to make it an actually executable Meilisearch program file.

How would I turn the binary into an executable?

**Comment by curquiza** [comment]
The files we provide are already executable files.

Are you sure you have downloaded the right binary? I don't have this kind of issue on my side, and none of my team does either.

Can you try to use `file` command on the file?

```
$ file meilisearch-macos-amd64
meilisearch-macos-amd64: Mach-O 64-bit executable x86_64
```

**Comment by kokoshneta** [comment]
That’s very odd…

- When I download the [macOS AMD64](https://github.com/meilisearch/meilisearch/releases/download/v0.28.1/meilisearch-macos-amd64) binary and do `file meilisearch-macos-amd64`, I get the same result as you.
- If I try to execute it, I get `permission denied` because it gets downloaded with permissions 644.
- Chmodding it to 755 and executing it again, I get a popup that macOS won’t allow me to run it because it’s from the Internet, blah-blah.
- Going into System Preferences → Security and Privacy and clicking “Allow anyway”, then executing again, I get a popup asking if I’m sure I want to run this untrusted program (yes, dammit, I _know_ it’s from the Internet!)
- Clicking “Open”, I now get `Error: No such file or directory (os error 2)`

I can’t force the `zsh: killed meilisearch` to appear today like it did yesterday; I wonder how I managed to get that…

The “No such file or directory” error seems to be related to where the file is located. I get it if I try to execute it from the Downloads folder, but if I move the executable to `/usr/local/bin` (which is in my $PATH), then lo and behold, it starts! I could have sworn I did that last night as well, but perhaps I didn’t.

Thanks for the help in getting me to persist and dig deeper!
