### ISSUE TITLE
Bad performance or crash during indexation

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2132]
Hello everyone!

If you are here it means you probably got some issues during your indexation with Meilisearch: the document addition might be really slow or even has led to a crash due to memory consumption.

The whole Meilisearch team is really sorry for this inconvenience. Be sure we are always working on making our search engine better regarding these points.

We really want to help you get through this, but before writing anything, please:
- Go to [the related discussion](https://github.com/meilisearch/meilisearch/discussions/2131)
- Read carefully the description
- Detail your problem in the discussion we link, **not in this current issue**

❓ We blocked the comments in this issue: it has to be done in [this discussion](https://github.com/meilisearch/meilisearch/discussions/2131). Indeed, the threads present in the GitHub Discussions (and not in the GitHub Issues at the moment) allow us to better handle each case.
The purpose of this issue is only to be a tracking issue for the core-team. The support for the users is done on the discussion side.

Thanks for reading this.
See you there 👋

----

### 02/02/2022

We have currently identified 3 types of issues during indexation:
- The users want to add a LOT of documents and this takes a lot of time
- The users want to quickly add/update documents to an already existing huge database into Meilisearch. This indexation time increases with the size of the database. 
- The users try to add or update documents, and Meilisearch crashes.

----

###  10/03/2022

Planned for v0.27.0: improvement regarding the prefix databases, see https://github.com/meilisearch/meilisearch/issues/2203

----

### 24/08/2022

We plan to release v0.29.0 in October, that will contain a lot of indexing improvements.
The main ones are:
- Introduce the [soft delete document](https://github.com/meilisearch/meilisearch/issues/2583)
- [Skip the indexation of already-existing documents](https://github.com/meilisearch/meilisearch/issues/2600) (the exact same one)
- Make the [auto-batching feature by default](https://github.com/meilisearch/meilisearch/issues/2582)

PRs in Meilisaerch:
- #2689
- #2690 -> Reverted because incompatible with aarch architechtures

PRs in [Milli](https://github.com/meilisearch/milli):
- https://github.com/meilisearch/milli/pull/579
- https://github.com/meilisearch/milli/pull/606)
- https://github.com/meilisearch/milli/pull/602
- https://github.com/meilisearch/milli/pull/590
- https://github.com/meilisearch/milli/pull/587
- https://github.com/meilisearch/milli/pull/561

We don't have official benchmarks for concrete use cases yet, but here is what we have now for indexing movies.json on my MacOs (not M1)
- v0.29.0: 16sec
- v0.28.1: 21sec

---

### 25/10/2022

In v0.30.0, the following changes will be applied to improve indexing speed
- meilisearch/milli#639
- meilisearch/milli#619

**Comment by MarinPostma** [comment]
I have explored multiple potential optimizations, but they have not been fruitful, I'll list them here:
- I had noticed that we had a majority of 8bytes writes, so I tried to make use of buffered writes instead to optimize writes. I was successful in mitigating the 8bytes write and reducing the number of write operations, but it somehow ended slower than before.
- I noticed that a significant time was spent dumping grenad DB into  lmbd. After looking further into it, I noticed that it was mostly due to iterating over a cursor and calling `put`. My hypothesis was that inserting directly from the cursor, instead of dropping the cursor to make an insert would bring performance improvements, but the changes were NS/slightly slower.
- A lot of time is spent in the grenad sorter sorting entries, I experimented with using a heap rather than sorting in the sorter, but it resulted in a big slow down.

That being said, I have doubts about the statistical significance of our benchmarks. The datasets we are using a very big, and therefore only a few samples are made. As further work, I think it would be interesting to benchmark the indexing of smaller datasets such that the number of samples is greater, and the benchmarking faster. The right size of such a dataset is TBD: I should be big enough to outline the indexing process while hiding latency costs. I also think more targeted benchmarks of the specific indexing phases could help us fine-tune the different parts of the process, and ease the profiling of each part of the indexer independently.

I have also tried to hook up coz and tracy to milli in the hope to be able to make more hypotheses, but this work is still ongoing.

**Comment by curquiza** [comment]
I've updated the issue description with the incoming changes in v0.29.0, this is a big positive step 🔥

**Comment by Kerollmops** [comment]
I have tested small machines to see how memory mapping would behave when a small amount of memory is available to the OS.

In the following test, I run the below command with different randomly-filled memory buffers. What [the _run_ program](https://github.com/Kerollmops/mmap-and-malloc) does is allocate a buffer of size _MA_ before opening and iterating on an LMDB database (using heed). The database is generated by the _prepare_ command, is of _4GiB_, and contains incremental _u64_ keys associated with random values.

The test machine has 2GiB of memory, and the baseline RES memory allocated by the already running programs is about 78.1MB.

```bash
# Generate the random database once
./target/release/prepare --size 4GiB

# Run the tests
./target/release/run --fetch-method iterative --allocate ${MA}GiB
```

| Memory Allocated (MA) | Time Taken | Status    |
|-----------------:|-----------:|-----------|
|            0 GiB |    129.20s | Succeeded |
|            1 GiB |    131.29s | Succeeded |
|          1.5 GiB |    137.90s | Succeeded |
|         1.66 GiB |    158.80s | Succeeded |
|         1.69 GiB |    219.26s | Succeeded |
|         1.70 GiB |    307.56s | Succeeded |
|        1.702 GiB |    284.26s | Succeeded |
|        1.704 GiB |    286.21s | Succeeded |
|        1.705 GiB | 14m18.844s | Killed    |
|         1.75 GiB |  4m54.509s | Killed    |
|          1.9 GiB |   0m2.720s | Killed    |

**Comment by curquiza** [comment]
I close this old and outdated issue in favor of feedback we punctually have on diverse platform, and also thanks to the client we have on the cloud
