### ISSUE TITLE
Weird highlight results with non-ascii

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [meilisearch/meilisearch#2144]
**Describe the bug**
Meilisearch is giving weird results compared to algolia and typesense.

To be honest I don't know if the software is built to behave in this way, or the language I use is unsupported. I wanted to report this in any case. I there is a settings toggle for it to become strict, I'd like to know. I also uploaded the data to http://search.staging.academicpositions.com/ for you to try. (Not sure who owns the website though.)

**To Reproduce**
1. Go to meillisearch dashboard
2. Search for `"Müəllimlərin İşə Qəbulu - Təsviri İncəsənət"` or `"Təsviri İncəsənət"`
3. See the weird results

**Expected behavior**
Should show correct results as algolia and typesense.

**Screenshots**
Check out the video where I explain the results. Don't forget to enable audio.

https://user-images.githubusercontent.com/15037839/152649267-56b590cf-7093-457d-a167-339e4983fa61.mp4

if you want, here is youtube link https://www.youtube.com/watch?v=kumI6XbjnUA

**Meilisearch version:** v0.22.0, v0.25.2

**Comment by OrkhanAlikhanov** [comment]
With ascii-only it seems more correct, but I still would like to get single result in both cases

(Make sure to enable audio)

https://user-images.githubusercontent.com/15037839/152649679-2c330ace-5477-425d-be2a-6ab069d28a7c.mov

**Comment by Kerollmops** [comment]
Hey @OrkhanAlikhanov,

Thank you very much for your issue and detailed explanation!
This bug seems to be highly related to the default Meilisearch tokenizer, Algolia uses a Unicode segmentation algorithm, and Typesense, IIRC, uses a basic split by whitespace system. We use a custom algorithm and it seems like it is the source of the issue here.

However, we plan to improve the tokenizer we use and we will probably expose a Unicode segmentation system too. @ManyTheFish plan to work on this for future releases. We will also expose parameters to disable the remove-words-at-the-end-of-the-query for when there are not enough documents to fulfill the 20 results.

**Comment by OrkhanAlikhanov** [comment]
Hey! Thank you for the detailed answer. How can one contribute to this. Is it easy to update tokenizer function or? Any directions if I want to mess around to workaround this issue?

**Comment by curquiza** [comment]
I put this issue in v0.28.0. The new tokenizer might be fix this, nothing sure, we need to test once the first RC is done

**Comment by ManyTheFish** [comment]
Hello @curquiza, after some tests I'm confident that the new tokenizer will fix this issue. 😄

**Comment by curquiza** [comment]
So this issue will be fixed when https://github.com/meilisearch/meilisearch/issues/2375 will be fixed 🚀
