### ISSUE TITLE
Long search time

### ISSUE THREAD

**Issue by vprelovac** [meilisearch/meilisearch#2256]
**Describe the bug**
Meili searches 1.6M documents in 2.5 seconds when search phrase is something like 'what to do in life'. It is fast when search is one-two words of containing less used words. 

Elastic search does it in <50ms.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Meilisearch version:** [e.g. v0.20.0]
0.26.1

**Additional context**

I started noticing this after upgrade to 0.26.1, not sure if it is related to it.

**Comment by curquiza** [comment]
Hello @vprelovac 

Thanks for this report and testing Meilisearch!

Could you send us more information so that we can reproduce the issue? We already tested on datasets with several millions of documents and we did not get this issue yet.

We would need:
- the settings you applied
- and most of all, the dataset, otherwise it's complicated to reproduce. We would understand you cannot share it publically, however, you can send it privately by email. Be sure we will delete it right after our tests. This is something we have already done with some of our users.
- the exact query you sent. With filter? With highlight?

Thanks in advance and sorry for the inconvenience 🙂

**Comment by vprelovac** [comment]
Unfortunately I decided to give up on meilie and continue using typsense.

There were just too many problems like:
- database incompatibility between releases
- slow indexing
- poor quality of results
- slow responses like this one

Wish you the best for the project and I will check it when you are at v1.0

**Comment by MarinPostma** [comment]
Thank you for your feedback, too bad that you can't provide us with more information that would help us understand the issue. Good luck with your project!

**Comment by gmourier** [comment]
Hi @vprelovac 

Sorry to hear that. Indeed, we are doing a lot to solve indexing speed and reduce breaking changes in the future. We are stabilizing the APIs as we go along.

Can you share with us details about the **poor quality of results**? Would love to have some materials to think about. 

Thanks!
