### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by eskombro** [meilisearch/meilisearch#2283]
**Describe the bug**
A link is broken in the README.md

**To Reproduce**
1. Open the README.md
2. Go to line 168
3. Click on the link
4. Nothing happens :)

**Additional context**
https://github.com/meilisearch/meilisearch/blob/main/README.md?plain=1#L168

**Comment by lucas-cauhe** [comment]
It seems like there is no target to link to for #demo 

In order to fix it you can either tweak line 31 by adding a name attribute to the <p> tag, so it would look like this:

`<p align="center" name="demo">`

Or you could also set a "demo" header above the trumen-show gif (aka line 30)

**Comment by lucas-cauhe** [comment]
that's "p" tag on the end of the second, I've wrote so that it  models it, jaja sorry

**Comment by curquiza** [comment]
Thanks @eskombro and @lucas-cauhe 😄 
Related to https://github.com/meilisearch/meilisearch/issues/2266

**Comment by curquiza** [comment]
Hello @lucas-cauhe I tried your fix here but it did not work: https://github.com/meilisearch/meilisearch/pull/2504/files

I might understand something! If you have time to go to the PR, your review is more than welcome ❤️ 

In any case, I close this issue since it's not something we really consider as a bug regarding the Meilisearch repo: we will add the link to the official demo once it's officially released!
The link is not broken, there is just no link to share at the moment.
