### ISSUE TITLE
How to send single quote(') in search query?

### ISSUE THREAD

**Issue by alphatownsman** [meilisearch/meilisearch#2288]
**Describe the bug**

**To Reproduce**
add `'filter' : ["tags = 'a\'b'"]` in search query, got error
```
MeiliSearchApiError. Error code: invalid_filter. Error message: Found unexpected characters at the end of the filter: `b\'`. You probably forgot an `OR` or an `AND` rule.
12:14 tags = 'a\'b' Error documentation: https://docs.meilisearch.com/errors#invalid_filter Error type: invalid_request
```

**Expected behavior**
return result with `a'b` as tag

**Meilisearch version:** v0.25 but assume impact all versions

**Comment by irevoire** [comment]
Same as https://github.com/meilisearch/meilisearch/issues/1653
Already fixed by https://github.com/meilisearch/meilisearch/pull/2005

Hello sorry for this bug, it has been fixed in the v0.26.
If you don’t want to upgrade and know you will only ever have the single quote to escape you could write your filter like that: `["tags = \"a'b'\"]` I think 🤔 

If you still encounter the issue on the v0.26 please re-open the issue!
