### ISSUE TITLE
numberic search in alphanumeric string

### ISSUE THREAD

**Issue by mjm918** [meilisearch/meilisearch#2387]
**Describe the bug**
Tried to search numeric in alphanumeric value but no result found

**To Reproduce**

Searched in Mini-Dashboard and also using the client SDK but same output

**Expected behavior**

**Screenshots**
<img width="990" alt="Screenshot 2022-05-11 at 3 21 47 PM" src="https://user-images.githubusercontent.com/17846525/167807201-1f24e306-6dc2-44e7-9d36-b52c2c38f404.png">
<img width="990" alt="Screenshot 2022-05-11 at 3 21 55 PM" src="https://user-images.githubusercontent.com/17846525/167807222-c64a938a-95f6-447d-aeb3-82c9e86cb7d3.png">

**Meilisearch version:** Package version:	"0.26.1"

**Additional context**

**Comment by oluademola** [comment]
Hello @mjm918 👋

Indeed this is the expected behavior and not a bug. This is because Meilisearch follows the philosophy of [prefix search](https://docs.meilisearch.com/learn/advanced/prefix.html#prefix-search) which is required to provide a fast search-as-you-type experience. What this means is when you search for a query Meilisearch starts by comparing the search query against the beginning of each word in your dataset, this is because Meilisearch considers each query as a word you want to retrieve in the documents and not a subset of the word. What this means for your use case is that Meilisearch will retrieve results for "nike7055" but it is not designed to provide results for "7055".

Here is a similar [issue](https://github.com/meilisearch/MeiliSearch/issues/1248) where our CTO @Kerollmops explained the drawbacks of providing this type of search feature as well as a possible workaround that could help you achieve your desired result.

Hope this helps. Thank you 🙂

**Comment by mjm918** [comment]
Hi @oluademola thank you so much for your fast response.

I'm referring to this [comment](https://github.com/meilisearch/MeiliSearch/issues/1248#issuecomment-1009850502). Correct me if i'm wrong.

> The solution to your problem would simply be to split the words at interesting points and put them in a new document field that the engine can use to prefix-search and find our document.

Is this the workaround right now? If yes, tokenising the text `NIKE7055AF-001 55" ` into `["nike", "7055", "AF", "001", "55"]` is text quite difficult. 

Please suggest me if there is any better solution. Thank you

**Comment by oluademola** [comment]
Hello @mjm918 

In Meilisearch the first word is the most important and it starts by comparing your search term against the beginning of each word in your dataset, what this means for your use case is you'll need to split the string or word such that `7055` begins as a word in a new document field that way the engine can use prefix-search to retrieve the document. For more information, you can have a look at our dedicated documentation about [prefix search](https://docs.meilisearch.com/learn/advanced/prefix.html#prefix-search) and [word match](https://docs.meilisearch.com/learn/configuration/typo_tolerance.html#configuring-typo-tolerance).

I hope this clarifies things for you. Thank you very much 🙂
