### ISSUE TITLE
Inconsistencies hard limit of 1000 with `nbHits`

### ISSUE THREAD

**Issue by jordyw-exsited** [meilisearch/meilisearch#2436]
**Describe the bug**
Since the hard limit of 1000 documents per query has been introduced we start having inconcistencies when using nbHits for pagination purposes. For example I've got a query matching 1568 results in nbHits. Paginating these results 24 per page gives us 66 pages of results. However since the hard limit of 1000 documents we stop getting results after page 42 (1000 results). Is it necessary to have the hard limit being applied before the offset parameter gets taken into account? This makes the nbHits kind of obsolete when a resultset contains more than 1000 matches, since you can never retrieve the results above an offset of 1000. 

**To Reproduce**
1. Go to https://verthus.be/categorieen/elektro-accessoires
2. You will see when the page is loaded I get 0 - 24 of 1568 (The total when writing this issue). We are on the very first page here.
3. Scroll down to the pagination and click on the last page link (66 when writing this issue).
4. You'll see no results will be returned although we are still within the total hits range. 
5. You can navigate through the pagination to see that on page 42 you'll see that the offset works 'till 1000. 

**Expected behavior**
I would expect to be able to move through the entire range of found matches for my query. I know in my use case it is most unlikely that the results won't be funneled down using the sidebar filters, but still I believe it is important to be able to go to the last page of the search results.

**Screenshots**
![Screenshot 2022-05-30 at 10 04 36](https://user-images.githubusercontent.com/58294781/170946761-121c8391-c7f1-47f4-bff3-8b1987011b08.png)

**Meilisearch version:** [e.g. v0.20.0]
v0.27.0

**Additional context**
I'm aware a lot of api calls to Meilisearch are being made in favor of the facet counts of the filters. But currently I see no other way of making it possible to get the distinct counts for each possible filter group.

**Comment by MarinPostma** [comment]
Maybe we can clip nbhits to 1000? ping @gmourier

**Comment by jordyw-exsited** [comment]
@MarinPostma This would mean facet distribution counts would also have to be calculated from these 1000 results if this is not already the case. Or we will have inconcistencies there.

**Comment by gmourier** [comment]
Hey @jordyw-exsited 👋

Would it be an acceptable solution for you to have `nbHits` limited to `1000`? Or is the problem to be able to access the results further than 1000?

**Comment by jordyw-exsited** [comment]
@gmourier Ideally I should be able to access results further than 1000. But I assume there is a reason the hard limit was introduced? I started using Meilisearch a couple of weeks ago so I'm not aware of the history and reasons behind the limit.

**Comment by curquiza** [comment]
Hello @jordyw-exsited 
Here is the related issue when we introduced this limit: https://github.com/meilisearch/meilisearch/issues/2133
Sorry, the explanation and the motivations are not really clear on this issue.

The reason is mostly security. Since the search endpoint is accessible to everyone
- we don't want to let people make requests that could lead to a server crash.
- we don't want to let external people scrap the whole DB. As the Meilisearch maintainer, if you want to retrieve your whole DB you have the `/documents` endpoint

Sorry again for the previous lack of clarity

**Comment by jordyw-exsited** [comment]
@curquiza Thanks for the clarity, it makes sense now. I must say a customizable setting would be an ideal solution, however I'm ofcourse reflecting it on my particular case only.

**Comment by thijndehaas** [comment]
Is it possible to make a setting of this where an own value can be set and a limit of 0 gives unlimited results? We already use Meilisearch in 6 different projects on dozens of websites.

We have already taken care of or are considering the security disadvantages and we would like Search engines to be able to scan all results. Also with the knowledge that a sitemap can return those results. For example, Google would not directly be able to fetch all incoming urls for a product page.

For now, unfortunately, we have downgraded all projects to work around this problem.

**Comment by curquiza** [comment]
@thijndehaas and @jordyw-exsited for any feature request, could you please open a discussion in [this repository](https://github.com/meilisearch/product/discussions)? It would be really helpful for the product team to have your need and your usecase! 😇 
Indeed feature requests are not managed in this repository, see the [Meilisearch's README](https://github.com/meilisearch/meilisearch#feature-request).

I let this issue open to solve the "bugged" behavior regarding `nbHits` and `facetsDistribution`. @gmourier and @meilisearch/core-team what would be the best behavior to adopt here?

**Comment by gmourier** [comment]
@thijndehaas 

> Also with the knowledge that a sitemap can return those results. For example, Google would not directly be able to fetch all incoming urls for a product page.

Can you elaborate on this please? I'm not sure to understand. Also, do you use Meilisearch as your primary datastore?

**Comment by thijndehaas** [comment]
@gmourier 

For example if a product detail page has incoming links from category pages we think it is better for ranking positions.
We think Google also finds the url in the category pages and gives it more priority as a page that is only in the sitemap, because of the amount of incoming links.

**Categories > Insurances > [Product]**
Gives the product more relevance to insurances and the product page has more incoming links.

**Categories > Insurances > Car insurances > [Product]**
Gives the product also more relevance to car insurances and generates even more incoming links.


> Also, do you use Meilisearch as your primary datastore?

We use a MySQL database with Laravel but we sync all to Meilisearch items when a created/updated/deleted event occurs in Laravel. After updating Meilisearch or changing config we run a command that can refill Meilisearch.

**Comment by curquiza** [comment]
I discussed with @gmourier, we don't know yet what we want to do with the `nbHits` inconsistency. Looks like this is more a pagination experience issue.

Also, even if it's not obvious, and we are sorry for the confusion, we don't encourage using `nbHits` for the pagination, see why in [this discussion](https://github.com/meilisearch/product/discussions/467)

If, as a user, you need to access the last page (and not only the next one) you can open a discussion in [the product repository](https://github.com/meilisearch/product/discussions) so that we can know your usage: why you need to access the last results, in which context...? etc
We are indeed thinking about improving the pagination experience and we need all our user feedback regarding this!

**Comment by ManyTheFish** [comment]
Hello @jordyw-exsited!
We are working on improving pagination in Meilisearch and we just released a first prototype that makes creating numbered pagination way easier! 🔥
It would be super helpful if you could let us know if this helps with your issue.
To know more about the prototype and how to use it, take a look at https://github.com/meilisearch/meilisearch/discussions/2635.

**Comment by jordyw-exsited** [comment]
Pagination seems to work fine since v0.30.2. Closing this one.
Thanks to all of you for the provided solutions.
