### ISSUE TITLE
Rework the `NOT` filter keyword

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#2486]
When writing filters, every operator is implicitly prefixed with an `EXIST` operator.

Consider the following set of documents:
```json
{ "id": 1, "product": "T-shirt", "price": 20, "color": "yellow" }
{ "id": 2, "product": "T-shirt", "color": "red" }
```

Today if I write `price != 20` I won't get the second document because what is computed by meilisearch is actually `price EXIST AND price != 20`.
That was a nice feature because we didn't have the `EXIST` operator before, but now, since we can explicitly ask for a field to exist, we want to remove this implicit exist and let the user decide what they want to do.

The `!=` should return all the documents that are not matched by the `=`.
And in general, when an operator is prefixed by a `NOT` we should return all the documents that do not match this operator.
For example:
- `NOT price < 10` should match `[1, 2]`
- `NOT price < 30` should match `[2]`
- `NOT price = 20` should match `[2]`

**Comment by curquiza** [comment]
For people following this issue, we have already published a docker tag to test the feature

```bash
docker run -it --rm \
    -p 7700:7700 \
    getmeili/meilisearch:v0.29.0-filter.beta.0
```

Or you can compile the source code on the `filter/field-in` branch on this repo

All the information about the new addition is detailed [here](https://github.com/meilisearch/product/discussions/407#discussioncomment-3084053)

Any feedback are more than welcome!! ❤️

**Comment by brunoocasali** [comment]
@curquiza I'm creating the integrations team issue for v0.29, and I'm questioning myself about whether this issue is a breaking change or not for us. 

But I think it is breaking since this behavior changed, do you agree with that?

**Comment by curquiza** [comment]
It's a change regarding the original behavior but will not break the code of the user using the `NOT`. The final `hits` returned will not be the same but the code will not break. In the changelogs, I wrote this under the "behavior changes ⚠️" section

**Comment by brunoocasali** [comment]
It will not be a compile-time-breaking change indeed, but if someone wants to keep the behavior (the same `hits` returned), they will have to change their query. 
For the Meilisearch engine side, I think this is ok since you are compliant with semver, but for us, I think we will have to release as breaking-change. What do you think?

**Comment by curquiza** [comment]
Sorry I forgot to mention something I should have mentioned first haha, sorry I answered too quickly and I forgot my old main reason.
The main reason why I’m not sure I want to consider this as a real breaking is: the PM, some users (and me) consider this change as a bug since it did not take ALL the documents before (see the example that conter-intuitive for some users).
I hesitated to put the `bug` label on the issue and to write the change in the `Bug` section in the release. However, I was afraid the users missed it, so I would rather make it in the “Behavior changes ⚠️" section. But actually, it's more a bug.

> I think we will have to release as breaking-change

What do you mean exactly? I can update the section by “behavior breaking change” if the warning is not clear enough, WDYT? However, for us it's not really a breaking but a fix.
I also will ask the devrel team to make it clear in the blog post.

Do you have something else in mind I forgot?

----

However, I like the discussion about these breaking/non-breaking changes. I would love (and need!) to discuss this with you in the future because this is something we will soon need to define as a rule when working with Meilisearch v1 and later 😁

In the meantime, I put some of my research about breaking changes here.

Let’s forget this specific change could be considered as a bug by the users.
In this case, I understand your point of view about “breaking”, but I’m mitigated about this question. To be honest, I 75% agree with you 😁 25% remaining because I don't really know what to do haha

I did some research, and it’s not always consistent and easy to interpret.

[SemVer](https://semver.org/): “MAJOR version when you make incompatible API changes” → it’s vague we cannot say the `NOT` change is fully incompatible. Plus, you can use `EXISTS` and `IN` to reproduce the old behavior.
But same in Semver: "MINOR version when you add functionality in a backwards compatible manner" -> not really the `NOT` change.

[Wiktionary](https://en.wiktionary.org/wiki/breaking_change): “A change in one part of a software system that potentially causes other components to fail” → the `NOT` change is not breaking, it does not make the code fail, or Meilisearch impossible to start.

[Stackoverflow](https://stackoverflow.com/questions/21703216/what-is-a-breaking-change-in-software): “if you cannot take the previous version of the product and swap *just* the module with the change in, then it is a breaking one” → again it’s not totally true, you can change your query to make it work as before with `EXISTS` and `IN`. 

I understand we have to make our own rules. We plan to do it with core team, and other dev team will review it.

A requirement we have: we need to allow the core team to do "breaking" on default search, otherwise it's really HARD to work on improving the search engine, for example, changing the placeholder order or changing the cropping algorithm.
But what is about the search breaking that impacts the search (so don't break the code) but involves the user changing their code to have the old behavior? For example, changing the `IN` behavior (but not a bug), or changing the default `matchingStrategy` value. This is where we have to decide if it's minor or major.

Sorry for the long comment, just my current thoughts here. The final decision about the rules will be done by every developer, not just me.

**Comment by brunoocasali** [comment]
Since we discussed that privately, I'll just say that I agree with your decision. Deciding between breaking is not easy.

I'll be happy to help thinking about that, and maybe the integrations team can help mitigate some of them. In any case, since the semver is not explicitly what should be done in that case, let's come up with our interpretation of that rule.
