### ISSUE TITLE
Can't search '简单'

### ISSUE THREAD

**Issue by hello--world** [meilisearch/meilisearch#2499]
### Discussed in https://github.com/meilisearch/meilisearch/discussions/2492

<div type='discussions-op-text'>

<sup>Originally posted by **hello--world** June  8, 2022</sup>
```python
documents = [
      { 'id': 9, 'title': '安装简单，没有复杂的配置：省心', 'genres': ['Adventure', 'Drama'] }
]
# index.add_documents(documents)

r = index.search('简单')
print(r)
# ----
{'hits': [], 'nbHits': 0, 'exhaustiveNbHits': False, 'query': '简单', 'limit': 20, 'offset': 0, 'processingTimeMs': 1}

```

<img width="885" alt="image" src="https://user-images.githubusercontent.com/9261185/172869015-291a935e-8e65-4bc2-8d81-b4b0691b61cc.png">

<img width="967" alt="image" src="https://user-images.githubusercontent.com/9261185/172662565-c1679095-7caa-478b-b685-872bb78d6fa6.png">

</div>

**Comment by ManyTheFish** [comment]
Hello @hello--world!

Currently, we are using jieba to segment Chinese texts in words, and your title will be segmented as  `["安装简单", "，", "没有", "复杂", "的", "配置", "：", "省心"]`.
Because your search query `简单` corresponds to the end of the first word and because Meilisearch only supports prefix search, therefore Meilisearch will not find your documents.

I hope my explanation was clear enough. Don't hesitate to ask more questions if you need them!

Thanks for your interest in the project!

**Comment by chenbimo** [comment]
yes it is.but how to resolve it?

**Comment by curquiza** [comment]
Hello @chenbimo 
Since we use Jieba, there is no way to solve this exact problem.

You can help us by reading [this discussion](https://github.com/meilisearch/product/discussions/503), especially the "Contribute" section where you will know how to help us. Since we are not Chinese it's not easy for us to know the different alternatives and to make the best decision. You already found the discussion but I write this for traceability.

Thank you!
