### ISSUE TITLE
Abnormally high CPU usage compared to RAM

### ISSUE THREAD

**Issue by antonhedling** [meilisearch/meilisearch#2581]
**Describe the bug**
Running a production server on AWS using a m6g.xlarge instance. CPU load average between 3-8 (depending on traffic) whilst memory usage is only hovers around 1GB (out of 16GB). Dataset about 1.5GB. Indexing works fine, this is during "regular" usage.

**To Reproduce**
This is obviously hard to reproduce, but I'm more looking for some feedback if this is normal. Some notes on how we use Meilisearch:

- We only have a few thousand documents but each document contains a lot of data. We run a multi-language sites which means we index every translation. A document can for example have categories attached to them, this means we index each category with all its translations so that it's searchable.
- We use facetDistributions on many places
- We have 14 filterable attributes
- We have 8 searchable attributes including a description (which can be up to 2000 characters).
- The VPS is running ARM
- Doing some testing locally it doesn't look like the searches themselves are slow. Some sample search times (in seconds):
![image](https://user-images.githubusercontent.com/19333210/177333434-3c693a8a-125c-42a4-9efa-191c3a2fb70d.png)

**Expected behavior**
According to the docs and my own logic we should see a lot more RAM usage and less CPU usage during regular operations. Screenshots taken below is when the server is not indexing. We have a lot of requests mind you, but the resource usage looks abnormal to me.

**Screenshots**
![image](https://user-images.githubusercontent.com/19333210/177328436-89b8754d-4478-4c84-b0be-d4330aa71369.png)

![image](https://user-images.githubusercontent.com/19333210/177328528-6c1f31fa-831f-4afe-96d2-132394e8d54c.png)

(Some of this structure was built before nested attributes existed)

**Meilisearch version:**
0.27.1

**Comment by irevoire** [comment]
Hello @antonhedling, a huge CPU usage usually happens because meilisearch is indexing (that’s a good sign, it means meilisearch is able to use 100% of your resource).
And for your RAM usage, the ram consumption is actually quite big.
<img width="594" alt="image" src="https://user-images.githubusercontent.com/7032172/177522197-adc3c217-5f3d-4cf1-baed-8dbfe4ac3fc3.png">
As you can see in the help of htop, the yellow bar is related to the RAM cache usage.
But this is not unused RAM, especially for meilisearch, which is [memory mapped](https://docs.meilisearch.com/learn/advanced/storage.html#lmdb).
A memory-mapped program relies on the cache a lot and lets the kernel decide when we can free or not the memory page.

So what you see is actually quite ordinary. The CPU usage is high, as well as the RAM usage.

**Comment by antonhedling** [comment]
> Hello @antonhedling, a huge CPU usage usually happens because meilisearch is indexing (that’s a good sign, it means meilisearch is able to use 100% of your resource). And for your RAM usage, the ram consumption is actually quite big. <img alt="image" width="594" src="https://user-images.githubusercontent.com/7032172/177522197-adc3c217-5f3d-4cf1-baed-8dbfe4ac3fc3.png"> As you can see in the help of htop, the yellow bar is related to the RAM cache usage. But this is not unused RAM, especially for meilisearch, which is [memory mapped](https://docs.meilisearch.com/learn/advanced/storage.html#lmdb). A memory-mapped program relies on the cache a lot and lets the kernel decide when we can free or not the memory page.
> 
> So what you see is actually quite ordinary. The CPU usage is high, as well as the RAM usage.

Thank you. I guess I missed that part in the documentation, and now I've also learned a bit more about memory usage. I'll simply upgrade the server. Closing this issue.
