### ISSUE TITLE
Improve indexation speed: introduce the soft document deletion

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2583]
We notice our document deletion time during indexation is quite slow. Plus, when updating (partially or not) a document, what the search engine does is "delete the document" + "create the document". Knowing this, we introduced the soft document deletion.
This is completely transparent for the users (nothing to activate) and will keep their documents on disk until a threshold is reached.

Even if we cannot say exactly the real impact of this change since we don't have real use cases to measure, I ping @meilisearch/devrel-team to inform you the search engine should be faster in v0.29.0
Maybe @irevoire can share some metrics even if we cannot ensure there are linked to official use cases.

Related to
- https://github.com/meilisearch/milli/issues/482
- https://github.com/meilisearch/milli/issues/571
- https://github.com/meilisearch/milli/issues/570

Spec: https://github.com/meilisearch/specifications/pull/168

**Comment by finalgamer** [comment]
Will this only effect the document replacement or also partial update?

**Comment by curquiza** [comment]
Hello @finalgamer 
Yes, it will impact any document update, partial or not 😄

**Comment by gmourier** [comment]
Hey everyone,

We met with @irevoire and myself to discuss the progress of this optimization for v0.29.  

[It was brought up some time ago that there were criticisms about the implementation based on the number of documents](https://github.com/meilisearch/milli/issues/570). Indeed, this way of doing things could be problematic in some cases; here are the drawbacks we have determined and wanted to share with you.

- Given a small disk capacity, where the occupied space is already really close to its maximum limit, it could prevent new documents from being added if soft deleted are never hard deleted (in that case, never reaching `10,000` soft-deletion).
- In a use-case with a huge throughput of document updates, on a very large disk, this `10,000` const could slow down indexing speeds by triggering the actual hard delete function too often and thus miss the optimization we are initially aiming for.

Several solutions have been suggested to better adapt to machine constraints and to the use-case of each one, based on the exact knowledge of the physical space taken on disk by the LMDB files.

- **Solution 1**: When the soft deleted documents represent a certain % of the total disk space, the hard delete is triggered.
- **Solution 2**: Up to a certain disk size used, documents are marked as soft deletable; when the limit is reached, they are hard deleted.

### Problem

To implement this type of solution, we need to know the size taken on the disk. However, the information displayed by the filesystem is not trusted because LMDB keeps virtual space displayed as used by the fs and thus never shrinks. [More information here](https://github.com/meilisearch/milli/issues/570#issuecomment-1180573645).

#### Exploring a way to have a trustable occupied space by the database

@irevoire will see if it's possible to get accurate information in a short amount of time and effort this week.

#### What will happen next?

Given the @irevoire technical exploration result, multiple tracks are offered.

If we can find a way to know the precise occupied space on a disk, we'll be able to choose a more elegant solution than relying on a document number, and we will elaborate on it in this case. (See Solution 1 / Solution 2). One good addition to that is that we could give a proper number on the `/stats` endpoint; thus, the @meilisearch/cloud-team will be able to display a trustable number regarding the used disk space of a project.

If we don't find a proper solution to the problem (Reminding that we initially wanted to release this optimization for v0.29), we may keep the method using a number of documents, but we'll provide a configuration option so that everyone can configure this number at his convenience and thus be able to take advantage of this optimization. In this case, we must remember that we can iterate on it later and implement a more elegant solution in the future (It will probably break the CLI).

We have also considered the possibility of providing an API to trigger the removal of "artifacts," but ideally, we would like it to be automatic so that the user does not have to worry about it or need to implement automation on his side to trigger it.

We could also decide to delay that optimization until we can implement an elegant solution that fits everyone.

**Comment by curquiza** [comment]
The spec is available here: https://github.com/meilisearch/specifications/pull/168

**Comment by curquiza** [comment]
Some clarification following questions I got internally
- When doing a dump: soft-deleted documents are not included, so if you import the dump, the soft-deleted documents will not be present in the DB
- When we are talking about "checking the available space before definitely removing the soft-deleted documents": we look at the [index size](https://docs.meilisearch.com/learn/configuration/instance_options.html#max-index-size) (configurable with the `--max-index-size` flag)

**Comment by guimachiavelli** [comment]
FYI, we have discussed this internally in the @meilisearch/docs-team and felt it was good to mention it somewhere in the docs as it might have implications for applications that need to be GDPR-compliant.

**Comment by curquiza** [comment]
Until we don't detail how it works exactly since we can break it at every moment, I'm not against this decision. People know what "soft-deletion" is since it's really common.
