### ISSUE TITLE
Unable to Search by last characters of the string

### ISSUE THREAD

**Issue by faisalalidev** [meilisearch/meilisearch#2612]
**Describe the bug**
I have a field name `vin_number` and I want to search by the last 4 digits but Its unable to search Its only return records based on the first set of digits that match the `vin_number`.
It should have return records by matching last digits of `vin_number`.

**Comment by MathiasWeisheit** [comment]
I have the same problem. "businessconsulting" will not be found with the search word "consulting".
I had implemented a dual search. One with meilisearch and one with "database-like-search". And then I combine the results.
But it will be much better, if meilisearch can do this.

**Comment by curquiza** [comment]
Hello @MathiasWeisheit and @faisalalidev 

This behavior is expected. Indeed Meilisearch is designed currently to perform a search-as-you-type experience, so using the prefix-search.
More information about the [prefix search](https://docs.meilisearch.com/learn/advanced/prefix.html#prefix-search) in our documentation

However, we have opened a [discussion in our product repo](https://github.com/meilisearch/product/discussions/492) to gather user feedback regarding this need. It would be really appreciated if you take the time to describe why your usecase in detail in this discussion, it would be definitely helpful.

The workaround currently, if possible, is to put a space between your digits. Same, write `business consulting` instead of `businessconsulting`.

I've already added this issue to the discussion description, so I close this issue in favor of https://github.com/meilisearch/product/discussions/492
