### ISSUE TITLE
paging affects faceting

### ISSUE THREAD

**Issue by krisztianpinter** [meilisearch/meilisearch#2673]
it appears that _limit_ and _offset_ parameters affect the facet counting.

the following results are in my (not public) database, but just to get the point across:

SEARCH: {"q": "...", "facets":["flags.gluten.code"], "limit":30}
RESPONSE: "estimatedTotalHits":30, "facetDistribution":{"flags.gluten.code":{"BAD":27,"GOOD":3}}

SEARCH: {"q": "...", "facets":["flags.gluten.code"], "limit":31}
RESPONSE: "estimatedTotalHits":35, "facetDistribution":{"flags.gluten.code":{"BAD":27,"GOOD":8}}

SEARCH:{"q": "...", "facets":["flags.gluten.code"], "filter":"flags.gluten.code = GOOD"}
RESPONSE: "estimatedTotalHits":8, "facetDistribution":{"flags.gluten.code":{"GOOD":8}}

since limit/offset is used for paging (as per documentation), it is unexpected to see the result being dependent on it.

the first result is returned for all queries from limit 0 to 30, and the second is returned 31 or above.

the database is relatively small with 5000 records, and 14MB indexed size.

Meilisearch version: v0.28.0  windows 2022-07-11T12:41:15Z

this issue seems to be similar, but is closed long ago
https://github.com/meilisearch/meilisearch/issues/1576

**Comment by ManyTheFish** [comment]
Hello @krisztianpinter!
Your issue is due to the fact that Meilisearch lazily computes the ranking algorithms in order to return the best results as fast as possible, the drawback is that Meilisearch will not compute exhaustively all the candidates and will only return estimations that will be more and more precise if you force Meilisearch to dig deeper in the results.

However, we are working on improving pagination in Meilisearch and we just released a first prototype that makes creating numbered pagination way easier! :fire:
It would be super helpful if you could let us know if this helps with your issue.
To know more about the prototype and how to use it, take a look at [the dedicated discussion](https://github.com/meilisearch/meilisearch/discussions/2635).
