### ISSUE TITLE
400 bad request

### ISSUE THREAD

**Issue by sabamohammadali** [meilisearch/meilisearch#2675]
Hi,

I am using meilisearch and I am getting an error: 
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'http://dc6cgw.qc.bell.ca:7700/indexes/gk/search'

The version I have installed on pycharm is 0.19.1 and on the server it is v0.26.1

How can I fix this issue? As my search API is working on the browser but from the code it is giving a 400 bad request.

Thank you.

**Comment by oluademola** [comment]
Hello @sabamohammadali 

This is because your Python SDK package is incompatible with v0.26.1. The meilisearch-python SDK v0.19.1 only guarantees compatibility with the latest version of meilisearch (v0.28). The issue could be resolved by using a compatible version. 

I hope this helps. Many thanks 🙂

**Comment by sabamohammadali** [comment]
Thank you :) It worked. I installed meilisearch_python_async version 0.23.1 which works with the version on the server v0.26.1, any version above this is not compatible and the API doesn't work
