### ISSUE TITLE
Filters should not accept unquoted reserved keywords as field names/values 

### ISSUE THREAD

**Issue by loiclec** [meilisearch/meilisearch#2679]
Currently, the following filters are valid:
```
x = AND
AND = x
```
because the `AND` is interpreted as a field name or the value of a field.
This can confuse Meilisearch's filter parser in its effort to return helpful error messages, and I also personally find it confusing to read. For example, the following filter is difficult to understand:
```
NOT OR EXISTS AND EXISTS NOT EXISTS
```
We should disallow all filter keywords to be used as field name/value and instead require that they be quoted or double quoted, like this:
```
NOT "OR" EXISTS AND "EXISTS" NOT EXISTS
```

**Comment by gmourier** [comment]
Thanks, @loiclec!

> We should disallow all filter keywords to be used as field name/value and instead require that they be quoted or double quoted, like this:

I directly see this as a drawback when expressing filters. I believe it may negatively impacts the user experience, and from my personal exp I find it weird to have to quote operators. 

It's also a significant breaking change without being sure of the final gain. 

Today, users don't necessarily complain about a query being not understood. I suspect that most of the user's queries are understandable by the filter parser because they are less convoluted.

Instead of forcing users to use quotes, isn't there a way to make the parser more "smart" for that case?

**Comment by loiclec** [comment]
Hi @gmourier ,

My guess is that, at the moment, there is almost zero user using a keyword as a field name, so that fixing this issue would not impact anybody. And even then:

1. In the case where someone did use filters such as `AND = 2`, then we can return an error message saying "`AND` is a keyword and thus must be quoted to be used as a field name or a value".
2. In the case where someone writes the filters programmatically, then it is a good practice to *always* quote the field names/values anyway. This is already necessary when the value contains spaces or quotes for example.

**Comment by irevoire** [comment]
> I suspect that most of the user's queries are understandable by the filter parser because expressed queries are less convoluted.

I suspect that no one actually uses `AND`, `OR`, or `TO` as their field name, and that’s why we never had any issue 😂 

Also, I’m not sure but I _think_ you misunderstood something here;
> and from my exp I find it weird to have to quote operators

It's the opposite, the operators are not quoted; what is quoted is the field name **in the case** your field name is the same as an operator 🤔 
You can still write `color = blue AND price < 20`, but when you write `color = AND price < 20` you get a way better error.
And in case you _really_ wanted to write something like that; `color = blue AND operator = AND` you have a breaking change and now you need to write `color = blue AND operator = "AND"`.

**Comment by gmourier** [comment]
Sorry!  I misunderstood it. My bad 🥲 It's much more clear with your explanations.

**Comment by curquiza** [comment]
Just something to add: enforcing the users to add quotes when using filters is a huge breaking, something we want to avoid before v2 (so I don't know when yet).
However, we can maybe prevent the users from doing it by improving the error message, for example, if possible.
I let this issue open because this is indeed a limit to Meilisearch, but we will not accept breaking PRs 😇

**Comment by curquiza** [comment]
Fixed in milli https://github.com/meilisearch/milli/pull/596
Needs to be integrated to meilisearch so I let this issue opened until we merged the new version of Milli
