### ISSUE TITLE
“灯”not works，but "大灯" works.

### ISSUE THREAD

**Issue by chenbimo** [meilisearch/meilisearch#2687]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/33003566/186084243-44468c42-012f-45da-ae4a-d3c623ce56ee.png)

![image](https://user-images.githubusercontent.com/33003566/186084341-25b9e66e-6c25-4fe6-8704-93bb02487bf9.png)

**Meilisearch version:** [e.g. v0.20.0]

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

**Comment by ManyTheFish** [comment]
Hello @chenbimo,
As you saw, there is a dedicated discussion about [Chinese Language support](https://github.com/meilisearch/product/discussions/503), could you explain your problem in this discussion instead? Add some examples of what is relevant in your point of view, and if you can, some search engine example that has better support.

This will help me to centralize all the feedback in order to enhance your experience with Meilisearch.

I will close this issue in favor of the product discussion related to Chinese Language support.

Thank you a lot for your feedback!
