### ISSUE TITLE
Benchmark some usecases and find a way to measure the team's performance

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2754]
_This implementation is only for our internal usage and does not impact the users._

Following this issue: https://github.com/meilisearch/devrel/issues/334

We need to implement benchmark tools to be able to measure our performance improvements. Currently, we have benchmarks on the [milli library](https://github.com/meilisearch/milli/actions/workflows/manual_benchmarks.yml), but it does not correspond to the reality of the user scenarios.

We want to measure some of these scenarios automatically and compare them between two versions.

**Comment by ManyTheFish** [comment]
Since the beginning of the work, the needs changed.
The main goal of these benchmarks is to challenge the limits of Meilisearch in the Cloud infrastructure.
This way, we want to know about each new version, several usage metrics, and limits on several sizes of instances proposed by Meilisearch-cloud and with several datasets.
The Metrics we want to gather are:
- Database size evolution depending on:
  - the number of indexed documents
  - the byte size of indexed documents
- average Indexing time depending on:
  - the number of documents per batch
  - the byte size per batch
- Indexing time evolution depending on:
  - the number of indexed document
  - the Database size

The Limits we want to gather are:
- The biggest batch of documents that Meilisearh can index depending on:
  - the number of documents in the batch
  - the byte size of the batch
- The total number of documents that Meilisearch can index
- The total byte size of documents that Meilisearch can index
- The number of concurrent searches that Meilisearch can handle with 95% of the response time under 80ms depending on:
  - the number of indexed document
  - the Database size
  
Therefore, we want to compute all of these metrics on each type of instance proposed by the cloud team.

**Comment by ferdi05** [comment]
> Since the beginning of the work, the needs changed. The main goal of these benchmarks is to challenge the limits of Meilisearch in the Cloud infrastructure.

On the DevRel side the need did not change much. We're still willing to compare us to other solutions for our marketing communications.

**Comment by ManyTheFish** [comment]
Hello,
a small update about search performance benchmarks, I haven't implemented anything so far.
However, I've tried to exhaustively list all the important variables that could impact the search performance:

- the dataset
  - the structure of the dataset's documents (number of attributes, size of each document)
    - [ ] songs: a lot of small documents with a small number of attributes
    - [ ] wiki: big documents with a small number of attributes
    - [ ] ecomerce: documents with a big number of attributes
  - [ ] the size of the dataset
  - [ ] the Language used in the dataset

- the settings
  - [ ] rankingRules
  - [ ] searchableAttributes
  - [ ] distinctAttribute
  - [ ] typoTolerance
  - [ ] synonyms
  - [ ] stopWords

- the search parameters
  - the query
    - [ ] the number of words in the query
    - [ ] the frequency of each word in the query
  - [ ] offset/limit
  - [ ] exhaustive pagination using `page`
  - [ ] filter
  - [ ] facets
  - [ ] matchingStrategy

- the concurrency
  - [ ] several searches at the same time
  - [ ] searches during indexing

- the size of the virtual machine (defined by the Cloud team)
  - [ ] 16Gb RAM / 4vCPU / 160Gb storage
  - [ ] 4Gb RAM / 1vCPU / 50Gb storage
  - [ ] a smaller one? (TBD @nicolasvienot)
  
  As we can see there are already a lot of variables to play with, and it wouldn't be possible to make a test that computes exhaustively all the possible scenarios.
  However, we could focus on the "most important" variables:
 -  we could focus on the most used settings, like the 3 more used `rankingRules` order. (@ferdi05 or @gmourier?)
 -  the number of words in the query should have a repartition similar to the real usage (how many queries with 1 word for the number of queries with 2, or should we benchmark 10 words?)

**Comment by ferdi05** [comment]
Can we match this `rankingRules` order with use cases (e-commerce, SaaS,..) ? and try to have realistic scenarios?

**Comment by ManyTheFish** [comment]
Hello @ferdi05, Sorry for the delays, unfortunately I don't know how to match this, moreover, search scenarios are really hard to find, and the few ones we have are hard to match with our dream scenario 😬

**Comment by curquiza** [comment]
Closing this
Future issue will come about our benchmark improvements, following this issue
