### ISSUE TITLE
synonyms behavior strange with chinese

### ISSUE THREAD

**Issue by LevyDeng** [meilisearch/meilisearch#2756]
**Describe the bug**
Just find this amazing search egine, but I found an issue when adding chinese synonyms, seems meilisearch automaticly add spaces to words:

**To Reproduce**
```
cli = meilisearch.Client("http://127.0.0.1:7700")

cli.index('test').update_synonyms({
  '推进之王': ['王维娜']
})

print(cli.index('test').get_synonyms())
```
`{'推进 之王': ['王维 娜']}`
**Expected behavior**
should not have spaces between words.

**Meilisearch version:** 
0.28.1

**Comment by ManyTheFish** [comment]
Hello @LevyDeng,

This behavior only occurs when displaying the synonyms, internally, due to the segmentation your synonyms are stored as:
```java
{["推进", "之王"]: [["王维", "娜"]]}
```
Because we can't have an array as a key in json, we chose to format it with spaces.

We should store the original version of the synonyms in addition of the internal representation 🤔 

However, this should not impact the relevancy of the search.

Thank you for your feedback!

**Comment by LevyDeng** [comment]
@ManyTheFish Thank you and I just find that the real problem is I need to reverse the synonyms key:value, because I want to search for '推进之王' with '王维娜', and it doesn't work at first. Maybe I haven't read the docs carefully and sorry for that.
Anyway thank you again and I'll close this issue.
