### ISSUE TITLE
Meilisearch tasks instance is frozen - Stuck on a single document

### ISSUE THREAD

**Issue by jeremylynch** [meilisearch/meilisearch#2781]
My meilisearch instance is "stuck" processing a single document. Over the last 24 hours the queue has built up to ~ 500,000 tasks. I cannot find any way to "reset" the tasks list or deal with this issue except for completely re-configuring Meilisearch. Any suggestions? 

I was able to solve this issue only by completely re-launching meilisearch. Hopefully in future there might be an easier way to achieve this.

**Comment by curquiza** [comment]
Hello @jeremylynch 

Thanks for using Meilisearch

Can you provide more information so that we can help you? 😊

- What is your Meilisearch version?
- Is your CPU working, and how?
- Can you check your [task list](https://docs.meilisearch.com/reference/api/tasks.html#get-tasks), and check the exact same task is processing for 24h or not? It can indeed be long to achieve all the tasks, but Meilisearch is not stuck on one single document.

Also, indeed, we plan to add a feature to cancel the tasks in v0.30.0, see the issue: https://github.com/meilisearch/meilisearch/issues/2749

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊

**Comment by curquiza** [comment]
Hello @alejandro 
You cannot cancel or delete any task by using v0.28.1, you need to use at least v0.30.0 😊
