### ISSUE TITLE
Update the "internal" CLI Meilisearch documentation

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#2810]
The current "internal" documentation of Meilisearch (when doing `cargo run -- --help`) is not always accurate. We would like to make it up-to-date with the official Meilisearch documentation.

Using this [link](https://docs.meilisearch.com/learn/configuration/instance_options.html#all-instance-options), update the comments in the following lines to make them correspond to the documentation description.

https://github.com/meilisearch/meilisearch/blob/2827ff7957675c3deb261d582168d1ca4cf6fe11/meilisearch-http/src/option.rs#L23-L169

Once #2745 is merged, you should update the comments in it as well to stay in sync between the cli and the default config file.

**Comment by ishani-1255** [comment]
Hi , If this issue is open I would love to work on it.

**Comment by irevoire** [comment]
Hello @ishani-1255,

Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!
If everything goes well, we're going to merge #2745 on Monday, it would be nice if you could sync the comments between the default config file and the cli. I'll update the issue to mention it.

Our contributing guidelines are available [here](../blob/main/CONTRIBUTING.md) and will guide you through your contribution.  If you have any questions, you can also ask them here!

FYI, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 😊
