### ISSUE TITLE
Broken Link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by AnirudhDaya** [meilisearch/meilisearch#2840]
**Describe the bug**
A broken link to the hacktoberfest contributing guidelines.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [contributing.md](https://github.com/meilisearch/meilisearch/blob/main/CONTRIBUTING.md#hacktoberfest-2022)
2. Click on the hyperlink 'website'
3. See error.

**Expected behaviour**
Should redirect to I suppose this [website](https://hacktoberfest.com/participation/)

**Screenshots**
<img width="938" alt="image" src="https://user-images.githubusercontent.com/94374523/193618041-915feabf-6239-422f-aa14-68850b23bade.png">

**Meilisearch version:** 0.29.0

**Additional context**
OS- Windows
Browser- Brave

**Comment by AnirudhDaya** [comment]
If this is valid can you assign this issue to me?

**Comment by curquiza** [comment]
Hello, yes you can fix it 👍 thank you very much

**Comment by AnirudhDaya** [comment]
Hey, @curquiza I have a few questions:
1. Is [this](https://hacktoberfest.com/participation/) the correct website the link should be redirected to?
2. Is this a valid contribution towards hacktober fest 2022? If yes could you add the corresponding label?
3.  Could you please assign this issue to me?

**Comment by curquiza** [comment]
1. Here is the [correct link](https://hacktoberfest.com/participation/#spam) we want. Thanks for asking
2. Yes it's valid. No need to add any label since the repo has the `hacktoberfest` topic on it: any merged PR in the repo is considered as valid, see the [Hacktoberfest rules](https://hacktoberfest.com/participation/#pr-mr-details)
3. we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 😊
