### ISSUE TITLE
Internal Error : Failed to fill whole buffer 

### ISSUE THREAD

**Issue by leottk** [meilisearch/meilisearch#2870]
**Describe the bug**
Hello,

I got this errors when indexing with Meillisearch v0.25.2 

```json
{"uid":2865,"indexUid":"immobilier","status":"failed","type":"documentAddition","details":{"receivedDocuments":18112,"indexedDocuments":0},"error":{"message":"failed to fill whole buffer","code":"internal","type":"internal","link":"https://docs.meilisearch.com/errors#internal"},"duration":"PT1559.222072714S","enqueuedAt":"2022-08-12T23:02:18.444815872Z","startedAt":"2022-08-13T03:17:56.964523522Z","finishedAt":"2022-08-13T03:43:56.186596236Z"}


```

**To Reproduce**

This is the first time i use Meilisearch so i don't know how to reproduce, i just checked the Meilisearch documentation to see the Error code and open this issue. 

 Pls help me to resolve this bug. 

**Meilisearch version:** [v0.25.2]

**Comment by oluademola** [comment]
Hello @leottk 

Again, sorry for the inconvenience and thank you for using Meilisearch! While the error message appears to be different it seems it's also related to #2871  due to the fact that you are not able to successfully index your data to Meilisearch. Once again, I'd like to confirm if the format of your dataset is a valid JSON, CSV, or NDJSON.

Looking forward to your response. Thanks 🙂

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
