### ISSUE TITLE
Search query with some special characters returns all from index

### ISSUE THREAD

**Issue by devAndrejM** [meilisearch/meilisearch#2872]
Meilisearch plugin with Strapi 

Bug occurs when search query consist of some special characters like * + - / # etc. The result of search will return everything within the index that is searched but for example when search query has % it won't happen.

**Comment by oluademola** [comment]
Hello @devAndrejM 

I am not sure I completely understand your question. It'd be fantastic if you could provide examples of your search queries and results for more context. However, Meilisearch might ignore or convert some special characters in your search queries to whitespace. You can find the list of affected characters [here](https://docs.meilisearch.com/learn/advanced/datatypes.html#string). Also, I think you might find this [discussion](https://github.com/meilisearch/product/discussions/160) helpful. Please let me know otherwise. 

Thanks

**Comment by devAndrejM** [comment]
That's it. Didn't know about the list of affected characters. Thank you for the reply. I'll close the issue
