### ISSUE TITLE
Bringing milli into the Meilisearch repository

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#2901]
We talked about bringing milli into the Meilisearch repository, this has different implications, good and bad effects.

First thing first, should we keep the name of _milli_? Shouldn't it be more explicit in what it does? As is: managing one single index at a time. If we publish it on crates.io one day, shouldn't it be prefixed by _meilisearch_, like _meilisearch-index_? We haven't done that for _charabia_ after all.

About the pros, bringing milli into the Meilisearch repository would reduce the synchronization cost. Right now, we need to publish a new GitHub release associated with a tag and update Meilisearch with the latest published tag. It is cumbersome and could bring bugs as git tags are not immutable. A simple `push --force` could break the releases.

## Publishing milli and Meilisearch on crates.io

This is why I want to talk about publishing milli to crates.io. This is the official crate registry that we should use. Publishing to it would force us to be more mature as we expose our work to the world, and more people would use this library. Once a release has been published to crates.io, it can't be deleted, only yanked. This system is here to be sure that builds are reproducible.

Publishing to crates.io will not bring the synchronization complexity we have right now. We can continue to work [with `path = "../milli"` and `version = "0.32.0"` simultaneously](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations). Crates.io doesn't allow to publish crates that use a dependency specified only with a `path`. So to be sure that Meilisearch can be built in a reproducible way, we should also make sure that we publish it on crates.io too.

Another advantage of having Meilisearch on crates.io is that installing a specific version of the engine, or even the last one would be as easy as `cargo install meilisearch`. It is obviously easy for people who already have a Rust toolchain installed.

## Downsides of having a monorepos

Having everything in one single repository could make us less disciplined and makes the developers more prone to creating more inter-dependencies between the repositories in the same workspace. This is because synchronization no more exists it would be easier just to do whatever we want, when we want, without thinking about good encapsulation of the libraries. But I'll let @ManyTheFish talk about that!

**Comment by irevoire** [comment]
> Having everything in one single repository could make us let disciplined and makes the developers more prone to creating more inter-dependencies between the repositories in the same workspace.

But currently, if we want to share dependencies between `meilisearch` and `milli` like the `json-pointer-thingy` we wanted to use in milli or the `snapshot-thingy` of milli we wanted to use in meilisearch we either have to move everything to milli and then re-export it or publish it to crates.io and then sync it between the two repo (even if it's really tied to our use case).

In the end, to me, it's worse than anything.
If we keep milli in a different crate, we should be able to keep the same level of encapsulation and shares the few libs that we need in both crates.

Also, I think you forgot a BIG downside of merging the two repositories, we'll have to port the whole « custom » CI we currently have in milli to the meilisearch repository with the benchmarks (and I have no idea how it'll work out).
But maybe, if we wait till after the v1.0 that would be a good time to actually rewrite and clean everything and uses new tools like [rebench](https://github.com/smarr/ReBench)?

**Comment by ManyTheFish** [comment]
# Pros & Cons
## Pros
1) All the issues will be centralized in the same repository making issue management easier for us and clearer for the community
2) The release process will be easier and the CIs should be easier to mutualize and maintain
3) Sometimes, a feature in Meilisearch needs a small change in milli like implementing  `Debug` or `Serialize` on a struct, what a painful process today to do the changes.
4) We are doing more and more prototypes, forcing us to manage and keep synchronized 2 different branches on Meilisearch and on milli

## Cons
1) A mono repo allows us to have more inter-dependencies, and this could lead to the creation of a new "meilisearch-lib" if we are not enough disciplined
2) As Tamo said, the merge could have unexpected hidden costs, like having to rewrite the whole CI, which could make the task more painful than we forecasted
3) how do we manage releases https://github.com/meilisearch/meilisearch/releases should we only consider the final binary?

# My personal choice

Despite some cons, I'd choose to merge milli in Meilisearch, but, not before Q1.

**Comment by curquiza** [comment]
To complete this issue, if we decide to migrate milli into Meilisearch, here is some migration work I see:
- We need to define if Milli will keep the same version as Meilisearch or not: if not, it will complexify our workflow, but it's not impossible -> I guess milli would not the only crate concerned by this discussion.
- About [the CIs files](https://github.com/meilisearch/milli/tree/main/.github/workflows)
  - every workflow starting by `push_benchmark...` currently are triggered when there is a new commit on `main` -> this is something we will need to change, only trigger them when there is a change in the `milli` folder. It can be easily done [with this](https://stackoverflow.com/questions/63822219/how-to-run-github-actions-workflow-only-if-the-pushed-files-are-in-a-specific-fo?rq=1) if I'm correct.
  - `manual_benchmarks` can be moved without any issue
  - `enforce_label`, `release-drafter` and `update-cargo-toml-version` can be removed, or at least need to be re-work if we decide to have different version between Milli and Meilisearch
  - the `rust` CI, so our test, can be removed since all the milli's tests will be run in the [Meilisearch test CI](https://github.com/meilisearch/meilisearch/blob/main/.github/workflows/rust.yml). However, we need to be careful: currently Milli does not run Clippy, which is the case on the Meilisearch side. We can have some surprises during the migration, losing time by fixing Clippy issues.


I understand the point of Many saying we don't migrate before Q1, and I would even say before v1. However, I also think changing during v0.30.0 pre-release and v1 sprint could be a good opportunity because
- the v1 sprint is longer
- we are not supposed to change a lot of things on milli side for v1 because it can be too impactful for stability -> something we would like not to do, but not a guarantee yet!

-> I'm not saying I want to do it during Q4, I just showing the advantage of the opportunity, knowing how it's painful for the team currently to work in 2 separate repositories.

**Comment by Kerollmops** [comment]
For your information, [here is a tweet](https://twitter.com/bitvecto_rs/status/1594139280623906817) explaining how we can merge two unrelated repositories into a single one with git.
