### ISSUE TITLE
not change  filterable attributes.

### ISSUE THREAD

**Issue by fangaofeng** [meilisearch/meilisearch#2916]
python client:
![image](https://user-images.githubusercontent.com/15919475/196085703-9c67863a-99b1-48d2-bf84-3b3d13067855.png)

![1665979106376](https://user-images.githubusercontent.com/15919475/196086301-75795f19-9411-4cae-937e-57a4fc9bc987.png)
not change filterable attributes.

but when delete all documents  `client.index('photoes').delete_all_documents()`,it can change  filterable attributes.

**Meilisearch version:** [v0.29.1]
**Additional context**
Additional information that may be relevant to the issue.
window11

**Comment by oluademola** [comment]
Hello @fangaofeng 

Did you check the [task route](https://docs.meilisearch.com/reference/api/tasks.html#get-one-task) later to confirm the status of the `settingsUpdate` task? It appears the task is in `enqueued` status from the screenshot. The `settingsUpdate` task is [asynchronous](https://docs.meilisearch.com/learn/advanced/asynchronous_operations.html#asynchronous-operations) in Meilisearch, meaning they are not executed instantaneously. There is a great chance there are other tasks in the queue which might delay this particular task because Meilisearch processes tasks in the order they were received. 

There are four [status values](https://docs.meilisearch.com/learn/advanced/asynchronous_operations.html#task-status) as mentioned in the docs:
`enqueued`: the task request has been received and will be processed soon
`processing`: the task is being processed
`succeeded`: the task has been successfully processed
`failed`: a failure occurred when processing the task. No changes were made to the database

I'd recommend checking the status of the task once again to confirm the actual progress of the task. 

Hope this helps. Thank you.

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
