### ISSUE TITLE
`invalid_task_status` is never raised on `GET /tasks`

### ISSUE THREAD

**Issue by gmourier** [meilisearch/meilisearch#2940]
**Describe the bug**

Sending an inexistent status returns a `bad_request` error while it should be `invalid_task_status`.

**To reproduce**

`curl 'http://127.0.0.1:7700/tasks?status=1`

```json
{
    "message": "Query deserialize error: invalid task status `1`, expecting one of: enqueued, processing, succeeded, or failed",
    "code": "bad_request",
    "type": "invalid_request",
    "link": "https://docs.meilisearch.com/errors#bad_request"
}
```

**Expected behavior**
[A clear and concise description of what you expected to happen.](https://github.com/meilisearch/specifications/blob/main/text/0061-error-format-and-definitions.md#invalid_task_status)

```json
{
    "message": "Task status `:status` is invalid. Available task status are: `:taskStatuses`.",
    "code": "invalid_task_status",
    "type": "invalid_request",
    "link":"https://docs.meilisearch.com/errors#invalid_task_status"
}
```

**Meilisearch version:** [e.g. v0.29.1]

**Comment by shogohida** [comment]
@gmourier 
Can I work on this? I would like to tackle this with [another similar issue](https://github.com/meilisearch/meilisearch/issues/2939)

**Comment by curquiza** [comment]
Hello @shogohida 

Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!
I saw you already opened one, thank you for this 😊

For your information, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/CONTRIBUTING.md).

**Comment by curquiza** [comment]
Closed by https://github.com/meilisearch/meilisearch/pull/3023
