### ISSUE TITLE
Add the support of the dump v1 (Meilisearch v0.20.0 and before)

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#2985]
Currently, users using Meilisearch v0.20.0 and before need to do TWO migrations to upgrade Meilisearch to v0.30.0. [See the related documentation](https://docs.meilisearch.com/learn/advanced/updating.html#update-to-the-latest-meilisearch-version).

This is due to the fact we dropped the support of dump v1 some releases ago.

It means it will not be easy for all our users to pass from their current version to v1. This is something we would like to avoid because in the best-case scenario, all the Meilisearch users will use Meilisearch v1.0.0 and after.

We would like to re-introduce the dump v1 support of Meilisearch to ensure people using Meilisearch v0.20.0 and before can migrate to Meilisearch v1.0.0 in one migration and not two.

## Impacted teams

@meilisearch/docs-team @meilisearch/integration-team 

## TODO

edited by @dureuill

- [ ] Implement the changes and merge to the `main` branch => https://github.com/meilisearch/meilisearch/pull/3170
- [ ] Update the [related spec](https://github.com/meilisearch/specifications/blob/main/text/0105-dumps-api.md#34-dump-version-support) => https://github.com/meilisearch/specifications/pull/203

**Comment by dureuill** [comment]
Started work on this today, made a reader of dumps v1, am doing a compat layers with dumps v2

**Comment by dureuill** [comment]
Draft PR open: https://github.com/meilisearch/meilisearch/pull/3170

Need to fix the tests, add some more tests, add description and so on.

**Comment by dureuill** [comment]
PR is ready for review :fire:

**Comment by curquiza** [comment]
Thanks @dureuill 
Don't forget the step about updating the specification, I put the link of the related spec in the issue 😄

**Comment by dureuill** [comment]
spec PR here: https://github.com/meilisearch/specifications/pull/203

**Comment by dureuill** [comment]
While I'm at it, some of the current "quirks" of the import from the dumps v1, caused by the format being so much older than the current v6 dump format, and that the documentation might want to keep in mind when updating the documentation of the dump feature:

- Tasks that are in the "enqueued" (not "processed" or "failed") status in the exported dump will not be imported (they will be missing from the task log, and won't be restarted). Technically, this is because we don't have the required data to resume the task. The recommendation for users to avoid any data loss is to make sure that all tasks of their Meilisearch <v20.0 are fully processed before exporting the database to a dump.
- Processed tasks that are of the type "Customs" in the exported dump will not be imported (they will be missing from the task log). Technically, this is because we don't have a similar task type in dumps v2 and superior (Meilisearch 0.21 and superior). This has no bearing on the actual document data in the imported DB so there is no special recommendation for users.
- The number of documents that were deleted by a clearAll command is unavailable in the task logs of dumps v1. In the imported DB, the number of deleted documents for these tasks will read "0" instead of the correct number. This is only for the task log and has no bearing on the actual documents contained in the imported DB (which are the same as the documents that were contained in the exported DB).
- There is DB creation date available for dumps v1, so this information will be missing for databases imported from dumps that were exported from Meilisearch <=v0.20 (I'm unsure what it is used for atm though)
