### ISSUE TITLE
When the `lat` and `lng` are strings the wrong error message is returned

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#3007]
When both `lat` and `lng` are strings, the engine tries to parse them as floats. If it fails to convert them, the error message must return a message that talks about both fields, not the first one failing. [This function](https://github.com/meilisearch/milli/blob/365f44c39b2b2fe47b04c30aa7bca6e1669a2141/milli/src/update/index_documents/enrich.rs#L342-L363) must be the one that manages that.

**Comment by sunero4** [comment]
I would like to have a go at this one of the next days

**Comment by curquiza** [comment]
Hello @sunero4 

Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

For your information, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 😊

**Comment by sunero4** [comment]
@curquiza That is completely understandable :) Thanks for the response! I will have a look at the guidelines

**Comment by ahlner** [comment]
@curquiza I've opened a PR for this bug: https://github.com/meilisearch/milli/pull/763

**Comment by curquiza** [comment]
Thanks @ahlner we will check your PR as soon as possible :D

**Comment by irevoire** [comment]
Fixed by https://github.com/meilisearch/milli/pull/763

**Comment by curquiza** [comment]
@irevoire don't close the issue until it's not fixed on the Meilisearch side
If it's already fixed on the meilisearch side, please link the PR that imports the new version of Milli containing the fix 😄

**Comment by irevoire** [comment]
Closed by https://github.com/meilisearch/meilisearch/pull/3395
