### ISSUE TITLE
Update Aws Community AMI to 0.29.2

### ISSUE THREAD

**Issue by ozgurhangisi** [meilisearch/meilisearch#3054]
**Describe the bug**

Hello,
Document duplication bug is very critical for us. It seems like you solved the issue in 0.29.2. We use aws community AMIs. Is it possible to update community AMI version from 0.29.1 to 0.29.2
Thanks.

**To Reproduce**
1. Go to Aws Community AMIs
2. Search for MeiliSearch
3. No 0.29.2 exists.

**Expected behavior**
Latest version in AWS must be bug free.

**Screenshots**

**Meilisearch version:** [e.g. v0.20.0]

v0.29.1

**Additional context**
Additional information that may be relevant to the issue.
[e.g. architecture, device, OS, browser]

**Comment by curquiza** [comment]
Hello @ozgurhangisi 

We've just released v0.29.2, like 2 hours ago 😊 
The integration is in charge of updating the AWS image, and will do it in the coming weeks. It takes time, and they have a lot to do at the same time. They will do their best to do it before the end of this week, otherwise next week.
In the worst case scenario, end of November, but should be done before.

I close this issue since it's not related to any implementation on the Meilisearch repo.

Thanks for reaching us and using Meilisearch.
