### ISSUE TITLE
Order of words in query does matter when using matchingStrategy="all"

### ISSUE THREAD

**Issue by michaelKaefer** [meilisearch/meilisearch#3066]
**Describe the bug**
`q="Käse Bregenz"` does return a result while `q="Bregenz Käse"` does not when using `matchingStrategy="all"`. I would expect the same results no matter which order of words in query I use (or at least a hint in the docs why this is not the case).

**To Reproduce**
Create a document with a title `Käse Bregenzerwald` and try both searches when using `matchingStrategy="all"`.

**Expected behavior**
Either finding the document in both queries or not finding the document in both queries.

**Meilisearch version:**
v0.29.1

**Comment by ManyTheFish** [comment]
Hello @michaelKaefer,

Your issue comes from the fact that prefix search is only handled on the last query word.
If you try to search `q="Käse Bregenzerwald"`  and  `q="Bregenzerwald Käse"` instead of `q="Käse Bregenz"`  and  `q="Bregenz Käse"`, then you should find the same results.
If you want to avoid prefix search, you can add a space at the end of your query (`q="Käse Bregenz"` -> `q="Käse Bregenz "`), this way, both queries should return the same results.

#### How Meilisearch interprets your query
Searching for `q="Käse Bregenz"` means that you are searching for the exact word `Käse` and any word prefixed by `Bregenz`, however, in the second query: `q="Bregenz Käse"`, you are searching for the exact word `Bregenz` and any word prefixed by `Käse`, this behavior explains the difference you have between both queries.

#### About our relevancy choices
But why we chose to handle prefix search only on the last word?
1) it's faster, searching by prefix has a higher cost than searching exact words.
2) it's consistent with the way a query is typed, we search the last word as a prefix because the end user may not have finished typing it.

I hope I answered your issue and my explanations were clear enough,
If not, don't hesitate to ask for more details!

**Comment by michaelKaefer** [comment]
Thank you @ManyTheFish, I missed that [prefix search](https://docs.meilisearch.com/learn/advanced/prefix.html) is causing this behaviour.
