### ISSUE TITLE
About release 0.29.2

### ISSUE THREAD

**Issue by chenrui333** [meilisearch/meilisearch#3139]
👋 Just curious if [the 0.29.2 release](https://github.com/Homebrew/homebrew-core/pull/115813) got re-tagged? [Found the checksum mismatch](https://github.com/Homebrew/homebrew-core/pull/116480) when regression testing against rust 1.65.0 release, raising this issue to double confirm. Thanks!

cc @curquiz

**Comment by curquiza** [comment]
Hello @chenrui333 
Sorry for the inconvenience.
We indeed had an issue with v0.29.2 that involved us adding a commit and moving the tag. I completely forgot to let you know (Homebrew) about it, sorry.
We had an issue with the docker image, so the v0.29.2 you have is the same as ours, but without the Dockerfile fix.

Anyway, we will release v0.30.0 on Monday, you should not have the issue on your side anymore.

The problem we currently have with our process is the homebrew PR is created immediately after we create the release, via our Homebrew CI. Meaning if any failure is happening with our binary compilation or docker image creation, it's too late, and the PR is already done on your side
We need to change this and run the Homebrew CI once every other CI is passed and not trigger it at the same time as the other because way faster. I will open an issue soon for this!

Sorry again for the trouble!

**Comment by chenrui333** [comment]
> We need to change this and run the Homebrew CI once every other CI is passed and not trigger it at the same time as the other because way faster. I will open an issue soon for this!

yeah, I think it can be easily fixed by having homebrew bump step as last step (while having conditions to check all the previous steps passed). 

Another way, similar to the above idea is to have a separate workflow to be triggered when all the CI flows passed.

let me know if you need any help on that

**Comment by chenrui333** [comment]
Closing the issue as I got what I need :)

**Comment by curquiza** [comment]
Thanks for your input @chenrui333 
I definitely need to spend time refactoring our current CI to ensure I don't break anything.

Thanks for suggesting your help!
See you around 👋

**Comment by curquiza** [comment]
I've opened an issue about this and I realized it's not that easy to implement on our side. Maybe I'm wrong? See https://github.com/meilisearch/meilisearch/issues/3146

If anyone has any insight on this, it would be really appreciated 🙏
