### ISSUE TITLE
Make Attribute Ranking rule more fuzzy

### ISSUE THREAD

**Issue by ManyTheFish** [meilisearch/meilisearch#3222]
The current behavior of the Attribute ranking rule is to iterate over all possible word positions of each Attribute in order to sort documents.

## A criticizable relevancy
This strategy is highly relevant for the first word positions of each attribute but not for the deeper word positions.
For instance, we search for "**best friend**", It's relevant to make a difference between these two attribute contents below:
> 1) "**BEST FRIEND**s Forever"
> 2) "My **BEST FRIEND**s"

where (1) is more relevant than (2). However, it's no more accurate on the two following attribute contents:
> 3) "After painter Michael 'Mike' Sheldrake's failed suicide attempt, house-mate and one of his life-long **BEST FRIEND**s Peter Tremaine, an antiques shop owner, reminisces their common past, like Mike does in therapy."
> 4) "Catherine refuses to believe that her business partner, the unlikeable François, has a **BEST FRIEND**, so she challenges him to set up an introduction."

where (3) is considered more relevant than (4) by the Attribute ranking rule.
Moreover, this "over-sorting" limits the impact of the raking rules that follows the "Attribute" one. It would probably be more relevant to sort (3) and (4) differently depending on other aspects, for example, the fact that document (4) matches exactly the query whereas document (3) matches only by prefix.

## Possible improvement

Instead of storing all the possible positions in the database, we could store exhaustively only the `20` firsts position, then, for others positions, store them at a logarithmic position which will group more and more positions together when the spoken positions are deeper and deeper in the attributes.

for instance with the document (3), the position would be grouped as:
> 1) "After"
> 2) "painter"
> 3) "Michael"
> 4) "Mike"
> 5) "Sheldrake"
> 6) "s"
> 7) "failed"
> 8) "suicide"
> 9) "attempt"
> - hard separator = position+8
> 17) "house"
> 18) "mate"
> 19) "and"
> 20) "one"
> 12) "of his"
>   - (here we group 2 words at the same position)
> 13) "life-long **BEST FRIEND**s"
>   - (here we group 4 words at the same position)
> 14) "Peter Tremaine"
>   - (here we group only 2 words instead of 8 at the same position because of the hard separator)
> 15) "an antiques shop owner, reminisces their common past"
>   - (here we group 16 words at the same position [4 words + a hard separator + 4 words])
> 16) "like Mike does in therapy."

Let's now imagine that we have attributes that contain the maximum number of word positions: 64535 positions, we would have to store in the database and compute during the search a maximum of 36 groups of positions if we use a binary Logarithm (log2) and a maximum of 276 groups of positions if we use a square root (sqrt).

This could represent a gain in terms of disk usage of the database, a gain in terms of search time, and a gain in terms of relevancy.

### About the technical changes

the only change to do is on the database `word_position_docids` where we should store the positions using a logarithm.

**Comment by geoffreybr** [comment]
Exactly the issue I was looking for :smile: !

I would add that the statement "(1) is more relevant than (2)" is also criticizable.

In my use case it's a search in a news article database and the users mainly search for thematic, places or person and they are never typing the beginning of the title of the article. We need the 'attribute' ranking because when the terms are in the title of the article, it's more relevant than in the content. But if the query is in the title in two articles, the most relevant would probably be the newest (so the 'attribute' ranking should stand aside in favor of other ranking rules).

For example, if you search "twitter" among two articles:
> 1. "Twitter: Elon Musk cancels his offer" published on the 8th July 2022
> 2. "For 44 billion dollars, Elon Musk bought Twitter" published on the 27th Oct. 2022

(1) will appear before (2) which is not the most relevant in this case.

**Comment by loiclec** [comment]
Hi @geoffreybr,
Thanks for weighing in on this issue 😄 I mostly agree with you! 

I also suspect that, for some use cases, the positions of the query's words within the attribute still matter, such that the statement "(1) is more relevant than (2)" is sometimes true.

For context, we are currently working on meilisearch v1.0. Our goal for this release is to stabilise the API and make meilisearch more resilient. We are also avoiding very big changes to the codebase, so that the release goes as smoothly as possible. Given all this, I am scared to change the design of the `attribute` ranking rule too dramatically or too quickly.

But once v1 is released, we will be able to make larger changes to the search algorithms. When we get to it, I want to consider how we can also improve the relevancy of the search results for your use case without degrading it for other people. So I have bookmarked your comment and will make sure to get back to it 🌅 In the meantime, making the `attribute` ranking rule fuzzier is an easy change that should still somewhat improve the relevancy for you and speed up search requests.

I am also curious to hear more opinions on what the best behaviour for this ranking rule should be. We want to know what would work best for everyone (or at least most people) before making more changes to it 🙂

**Comment by geoffreybr** [comment]
Hi @loiclec!

Maybe one way would be to split it into two different ranking rules: `attribute` that sort not taking terms order into account, and `position` that order according to the position of the word in all attributes. But I suppose it's not the best for performance.

Or maybe create another ranking rule, or a kind of modifier like `attribute:no-position` which tweak the default behavior of the `attribute` rule (so existing users would not be affected by the change) to not use the terms position to calculate range.

Anyway, as you say, the resolution of this actual issue will indeed partially improve the relevancy so that's a good step for us.

**Comment by loiclec** [comment]
@geoffreybr The `attribute:no-position` solution was also one I had in mind, although I haven't talked about it with the rest of the team yet. I can also imagine someone might want to use a list of ranking rules like this one:
```sh
words
# only sort the results based on the rank of the attribute where the terms appear
attribute:no-position
typo
proximity   
# now take into consideration the position of the terms as well
attribute:position
# could also limit the rule above to a set of attributes (don't pay attention to the grammar yet)
attribute:position:{description, trivia, etc.}
exactness
```
Note that I haven't properly evaluated the feasibility of the performance impact of all this yet.

**Comment by gary02** [comment]
hi, meili,   are there any progress of 'attribute:no-position' feature?

**Comment by curquiza** [comment]
Hello @gary02 
We will globally work on search performance issues during Q1 and Q2 (at least).
This feature (`attribute:no-position`) will be part of the global investigation and possibilities we might improve. We always need to measure the impact on the product side before releasing, so we cannot guarantee this exact feature will be present. Plus, the whole process can take time due to the investigation + the huge implementation 😊

**Comment by loiclec** [comment]
The main issue of `make attribute ranking rule fuzzy` was fixed by https://github.com/meilisearch/meilisearch/pull/3542 . We are also now capable, technically, to implement ranking rules such as the ones I described above:
```
words
# only sort the results based on the rank of the attribute where the terms appear
attribute:no-position
typo
proximity   
# now take into consideration the position of the terms as well
attribute:position
# could also limit the rule above to a set of attributes (don't pay attention to the grammar yet)
attribute:position:{description, trivia, etc.}
exactness
```
I will close this issue, but I opened a [product discussion to determine what those new ranking rules should look like exactly](https://github.com/meilisearch/product/discussions/653) :)
