### ISSUE TITLE
Document log format

### ISSUE THREAD

**Issue by gajus** [meilisearch/meilisearch#3225]
I couldn't find any documentation about the log format produced by Meili

I made educated guesses, but would be nice to document this somewhere

https://regex101.com/r/OjjADp/1

```regex
\[(?<time>[^ ]*)\s+(?<severity>[^ ]*)\s+(?<namespace>[^ ]*)\]\s+(?<remote>[^ ]*)\s+"(?<method>[^ ]*)\s+(?<path>[^ ]*)\s+(?<protocol>[^ ]*)"\s+(?<status>[^ ]*)\s+(?<responseSize>[^ ]*)\s+(?<host>[^ ]*)\s+"(?<userAgent>.*?)"\s+(?<responseTime>\d.\d+)
```

```log
[2022-12-09T13:50:54Z INFO  actix_web::middleware::logger] 10.12.0.153 "POST /indexes/contractors/search HTTP/1.1" 200 148023 "https://contra.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0" 0.035923
[2022-12-09T13:53:16Z INFO  actix_web::middleware::logger] 10.12.18.160 "POST /indexes/organizations/search HTTP/1.1" 200 388 "-" "undici" 0.013515
```

**Comment by dureuill** [comment]
Hello @gajus :wave:

Thanks for opening the issue; indeed, our log format is currently undocumented.

Your regex is correct for the parts between brackets, but the part afterward (the message) is free-form (although some log messages might punctually adopt a more constrained format). We are not enforcing a particular format for this part at the moment.

Internally, we're using the [Rust library env_logger](https://docs.rs/env_logger/latest/env_logger/) with the default settings to display the logs. It looks like they are not documenting their default format themselves, but the documentation and their source code might offer further required precisions.

Feel free to share If you have a use case for the logs to be in a known format.  For instance, if you're parsing them for some purpose? At the moment, parsing the message part is going to be unreliable due to us not enforcing any specific format for that part.

**Comment by gajus** [comment]
> Internally, we're using the [Rust library env_logger](https://docs.rs/env_logger/latest/env_logger/) [..]

Any chance we can toggle output format? e.g. convert it to JSON

> Feel free to share If you have a use case for the logs to be in a known format. For instance, if you're parsing them for some purpose?

Yes, for setting auto alerts based on matching log patterns/attributes.

**Comment by dureuill** [comment]
> Any chance we can toggle output format? e.g. convert it to JSON

Not that I know at the moment, we'd need to switch to a different logger crate for that, I think. Also, to have the message part of the log to be structured, we'd have to change the logging framework we use internally to [slog](https://lib.rs/crates/slog) or [tracing](https://lib.rs/crates/tracing).

> Yes, for setting auto alerts based on matching log patterns/attributes.

Please note that the output of our logs is not part of our [versioning policy](https://github.com/meilisearch/engine-team/blob/main/resources/versioning-policy.md) for the upcoming Meilisearch v1 and later. This means that the output could change in future 1.x versions. Should that happen, we would strive to tell users in the changelog, though.

At the moment, we don't intend to change this point of the policy. Still, if you have a use case of getting auto alerts based on some events happening, I encourage you to open a discussion in the [products repository](https://github.com/meilisearch/product/discussions/categories/feedback-feature-proposal), for maybe we can help you :-).

**Comment by curquiza** [comment]
I close this issue then. Feel free to ask to re-open if needed 😊
