### ISSUE TITLE
sort by is incorrect for accented characters

### ISSUE THREAD

**Issue by Karman40** [meilisearch/meilisearch#3260]
## Describe the bug
According to the Hungarian ABC, certain vowels have accented pairs. For example: a-á, e-é, i-í, ü-ű, o-ó ...
When I sort the index based on text, the accented characters are always the last.

## Version
- Meilisearch engine: `0.30.4`

## Screenshots
The value of the `sortBy.` field can be 1 or 2, number type.
![image](https://user-images.githubusercontent.com/32225709/208169983-b681b50e-b55c-4ffe-bcf3-33ecbe972c54.png)
![image](https://user-images.githubusercontent.com/32225709/208170232-e40e2743-b24a-4f4d-85b6-106f064a8109.png)

The letter é should be between the letters e and f.
![image](https://user-images.githubusercontent.com/32225709/208170336-0ae6f346-0f37-4fa8-8457-e791e58ff209.png)

## Additional context
https://en.wikipedia.org/wiki/Hungarian_alphabet

**Comment by oluademola** [comment]
Hello @Karman40,

Following a discussion with the team. Unfortunately, the engine currently cannot achieve your use case because strings are sorted in lexicographic order by their byte values in Meilisearch. This means the accented characters will be sorted after ASCII characters because they have a higher byte or Unicode value. For example, `á` has a value of 225, while `a` has a value of 97, and `z` has a value of 122. Because sorting is based on byte values, `á` will be sorted after `z`.

I hope you find this helpful.

Thanks.

**Comment by Kerollmops** [comment]
Hey @Karman40,

One thing that you can do could be to create a normalized version of the field and sort by it, this way accented and non-accented values will be near each other. The normalized field can be used to sort and can be hidden to the user.

Have a nice day 😊

**Comment by Karman40** [comment]
Thank you for your answers.

This way I understand how the system currently works. What do you think, will there be official support for accented characters in the future? I'll try to arrange it based on the latinased version.

**Comment by oluademola** [comment]
Hello @Karman40,

Very sorry for the delayed response. Changes to the engine as regards this is something that is currently not planned. However, since this is more of a feature request than an issue with the engine, I'd encourage you to start a discussion on the [product repo](https://github.com/meilisearch/product/discussions/).

Thanks.
