### ISSUE TITLE
Introduce more error `types`

### ISSUE THREAD

**Issue by irevoire** [meilisearch/meilisearch#3271]
Currently, we only have 3 error types:

- `invalid_request`
- `internal`
- `auth`

And thus, by default, when something isn’t an `invalid_request` or an `auth` request we mark it as an `internal` which is not clear at all.
Or, when we want to remove the `internal` type to a request we have to choose one of the two other category which seems quite wrong.

I would like to introduce a new type called `setup` for all the error related to your configuration. Like, not enough space available, too many open files and probably others.

**Comment by dureuill** [comment]
> I would like to introduce a new type called `setup` for all the error related to your configuration.

Fully agree with the idea, except the name. To me this is more generally an `environment` issue, because the configuration could be correct initially and then later usage/change could result in a condition. IO errors could also occur due to hardware failures. So I'd like us to go with the `environment` name.

Another name that is often used (but might be too generic) is `runtime`.

**Comment by curquiza** [comment]
I closed this issue in favor of https://github.com/meilisearch/meilisearch/issues/3095 that links the central spec that describes the exhaustive changes: https://github.com/meilisearch/specifications/pull/212
