### ISSUE TITLE
Some data are not added to the index

### ISSUE THREAD

**Issue by beshkenadze** [meilisearch/meilisearch#3282]
**Meilisearch version:** 
0.29.1
**Env:** 
AWS/k8s

**Describe the bug**

We have ~60k records that we add in 350 chunks. There are ~171 records appearing in the task queue with the action of documentAdditionOrUpdate. After this, a settingsUpdate occurs, which updates the search settings.

**Problem:**

The index count shows ~40k records instead of ~60k and some data are missing. There are no errors appearing in the logs.

What could be the problem? How can I debug it?

Thanks,

**Comment by oluademola** [comment]
Hello @beshkenadze 

This could be because of a recent bug that was fixed in [version 0.30.5](https://github.com/meilisearch/meilisearch/releases/tag/v0.30.5). I would recommend that you upgrade to the most recent version and reindex your data from scratch. Furthermore, the number of documents displayed by the stats route could be an [issue](https://github.com/meilisearch/meilisearch/issues/2909). As a result, I recommend searching [exhaustively](https://docs.meilisearch.com/reference/api/search.html#exhaustive-and-estimated-total-number-of-search-results) or querying the [get documents route](https://docs.meilisearch.com/reference/api/documents.html#get-documents) to find the correct number of documents in the index.

Please let me know if this helps.

Thanks

**Comment by beshkenadze** [comment]
@oluademola Thank you for your answer, but nothing has changed after updating to version 0.30.5.
We decided to try switching to Elasticsearch, so I close this issue.
