### ISSUE TITLE
filter  null field and get result 

### ISSUE THREAD

**Issue by khantanvir** [meilisearch/meilisearch#3431]
When search I want to check field is null or not ... I need also null row return. Please give some suggestion how can I do this? Sample code:   $filter[] = 'branch_id = '.$null.' OR branch_id = '.$auth_branch_id;
Thank you

**Comment by oluademola** [comment]
Hello @khantanvir,

As I've explained in our conversation via Instant messaging, we consider this a product limitation and not a bug because it is currently impossible to filter on null values. I would encourage you once again to share the details of your use case in this [discussion](https://github.com/meilisearch/product/discussions/539) in the product repo. It will be very helpful to the product team.

Thank you.
