### ISSUE TITLE
Placeholder or Browse Search

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliSearch#346]
Allow users to request `/search` without `?q` parameter (or with an empty string). 

The general idea behind this PR, is to create a kind of placeholder when the end-user has not yet done any search. 

It will also use the power of filters, facets filters and custom rankings rules to show the most relevant responses without query.

**Comment by unknownhasher** [comment]
This is very usefull!

**Comment by unknownhasher** [comment]
I found a workaround for this problem. You can add a column to your index for each document on where you can match when you have no q / search string. 

for example i've added a column named 'salt' and i fill him with '^^'. When i want to search with filters but without a search string i can search on '^^' and i get all of the results. 

note: you have to use a string in your salt that is not used when you have a search string because otherwise every record will match when you dont want to.

**Comment by jiminy-billy-bob** [comment]
This would be immensely useful!

**Comment by Kerollmops** [comment]
Hey,

I am closing this issue in favor of the new #729 tracking issue.
You can follow the tracking issue now!
