### ISSUE TITLE
Search Relevancy & Performance Improvements 

### ISSUE THREAD

**Issue by loiclec** [meilisearch/meilisearch#3547]
spec: https://github.com/meilisearch/specifications/pull/233

This issue is meant to track future improvements to the search algorithms, especially those that are made possible by PR https://github.com/meilisearch/meilisearch/pull/3542. I added tags next to each issue to categorise them. The tags are:
- `performance`: reduces latency
- `product`: user-facing, requires some discussion with the product team and Meilisearch users
- `indexing`: affects the indexing logic, mostly speeding it up
- `relevancy`: impacts the quality of search results or provide an additional way to tweak them
- `correctness`: fixes a bug or remove a source of bugs
- `uncertain`: still at the "idea" stage, needs to be evaluated

---

- In general, every search performance issue:  #3123, #3124, #2202 , #2966 , #3378 (`performance`)
- #3356 (`performance`, `correctness`)
- #3424 (`product`, `relevancy`)
- [Return the output of the ranking rules for each search result](https://github.com/meilisearch/product/discussions/594) (`product`, `relevancy`)
- [New ranking rule: words in [attribute set]](https://github.com/meilisearch/product/discussions/595) (also linked to #3222) (`product`, `relevancy`, `performance`, `indexing`)
- #3425 ([`product`](https://github.com/meilisearch/product/discussions/593), not dependent on the search refactor)
- #3410 (`correctness`)
- #3545 (`uncertain`, `performance`, `indexing`, `relevancy`)
- #3546 (`uncertain`, `correctness`)

---

### Changes pertaining to relevancy

- High impact
  - [exactness_synonyms](https://github.com/meilisearch/meilisearch/issues/3547#issuecomment-1521922468)
  - ~~[exactness_words](https://github.com/meilisearch/meilisearch/issues/3547#issuecomment-1521922699)~~
- Low impact
  - [exactness_bucketed](https://github.com/meilisearch/meilisearch/issues/3547#issuecomment-1521921259)
  - [exactness_separate_checks](https://github.com/meilisearch/meilisearch/issues/3547#issuecomment-1521922148)
  - [limit_derivations](https://github.com/meilisearch/meilisearch/issues/3547#issuecomment-1521922927)
  - [limit_synonyms](https://github.com/meilisearch/meilisearch/issues/3547#issuecomment-1521923091)
 - No impact
   - [exactness_phrase_value](https://github.com/meilisearch/meilisearch/issues/3547#issuecomment-1521921690)

**Comment by dureuill** [comment]
# Relevancy change: imprecise far positions

- short name: exactness_bucketed
- Perceived impact: Niche edge cases, impacts search engine implementers
- Needs specs: No?
- Involved ranking rules if applicable: exactness
- Implementation status: Implemented

## Example

### Affected query



- Let the ranking rule `exactness` be present in settings.
- Let the search query contain a sentence with more than 16 words.
- Let there be documents containing words from the sentence after position 16 in the sentence and slightly "out-of-order". Let such documents be "out-of-order documents".

### Behavior prior to the refactor



- "Out-of-order documents" are not exact matches for the exactness ranking rule.


### Behavior after the refactor



- "Out-of-order documents" are exact matches for the exactness ranking rule.

## Rationale



- Performance: the positions of words in attributes are no longer stored as exact after position 16, but rather "bucketed" so that close exact positions are mapped to the same "bucketed position" in a logarithmic fashion (the further the word in the attribute, the more imprecise its position). This reduces the space taken in the DB by these records.
- The loss of relevancy is arguably minimal.

## Test cases



TBC

**Comment by dureuill** [comment]
# Relevancy change: Bigger value for matching a phrase

- short name: exactness_phrase_value
- Perceived impact: End-user facing
- Needs specs: Yes?
- Involved ranking rules if applicable: exactness
- Implementation status: Pending

## Example

### Affected query



- Let the ranking rule `exactness` be present in settings.
- Let a query contains both a phrase and two word terms: `"This is an example phrase" word terms`.
- Let a document containing the exact phrase `"This is an example phrase"` ("phrase document") and a **different** document containing the two word terms `word terms` ("word document").

### Behavior prior to the refactor



- The word document is matched first, because the number of terms matched by this document is bigger than in the phrase document (2 versus 1).

### Behavior after the refactor



- The phrase document is matched first, because the number of words matched in this document is bigger than in the word document (5 versus 2).

## Rationale



- Relevancy: Exactness favors proximity with the query as typed by the user, so counting the number of words rather than the terms make more sense.
- Relevancy: The intent when using a phrase is to boost results containing the phrase, and this is better achieved with the new heuristics.

## Test cases



TBC

**Comment by dureuill** [comment]
# Relevancy change: Separate checks that all words are in the same attributes and their position is correct

- short name: exactness_separate_checks
- Perceived impact: Niche edge cases, for search engine implementers
- Needs specs: No
- Involved ranking rules if applicable: Exactness
- Implementation status: Implemented

## Example

### Affected query



- Let the ranking rule `exactness` be present in settings.
- Let the search query contain multiple words.
- Let there be a document such that:
  - all words in the query do **not** appear in the query order in the same attribute
  - each word of the query appears in some attribute at the correct position
  - there exists an attribute that contains all the words from the query in the incorrect order.

---

- Query: "All words in the world"
- Document:
  - Title: "All dogs in the world"
  - Description: "The words are missing"
  - Metadata: "In the world you can have all words".


### Behavior prior to the refactor



Such a document is **not** an exact match for the first strategy of the exactness ranking rule.

### Behavior after the refactor



Such a document **is** an exact match for the first strategy of the exactness ranking rule.

## Rationale



- Post refactor, the database containing the position of a word in a document was split into two databases: a database referencing the documents that contain a word at some position in any attribute, and a database that contains a word in some attribute. This change is motivated by the position + attributes ranking rules changes, but makes it very costly to perform the full check that a single attribute contains all the words in the correct order.

## Test cases



TBC

**Comment by dureuill** [comment]
# Relevancy change: synonyms are not exact matches

- short name: exactness_synonyms
- Perceived impact: Impacts end-users
- Needs specs: Yes
- Involved ranking rules if applicable: Exactness
- Implementation status: Implemented

## Example

### Affected query



- Let "New York" have 2 synonyms in settings: "NYC" and "New York City".
- Let the ranking rule `exactness` be present in settings.
- Let the request be `"q": "New York"`

### Behavior prior to the refactor



The exactness matching rule considers synonyms as exact matches if they are "single word synonyms", that is to say:

- Documents containing "New York" and "NYC" are matched by the exactness rule.
- Documents containing "New York City" are not matched by the exactness rule.

### Behavior after the refactor



The exactness matching rule never considers synonyms as exact matches, i.e.:

- Documents containing "New York" are matched by the exactness rule.
- Documents containing "NYC" and "New York City" are not matched by the exactness rule.

## Rationale



- Improves consistency between single words and multi-words synonyms: there was no user-facing reason for this demarcation
- Exactness is meant to favor **what the user typed**. Arguably this change improves relevancy by making a difference somewhere between synonyms and non-synonyms. Other ranking rules handle the synonyms, and if this behavior is not wanted users can remove the exactness ranking rule.
- Better performance as we don't have to look up at the synonyms for exactness.

## Test cases



TBC

**Comment by dureuill** [comment]
# Relevancy change: Limit the number of derivations

- short name: limit_derivations
- Perceived impact: Niche, engine implementers
- Needs specs: No
- Involved ranking rules if applicable: typo, words, proximity
- Implementation status: Implemented

## Example

### Affected query



- Let there be a dataset containing all words from `aaaaaaaa` to `zzzzzzzz` and the search query `aaaaaaaa`.
- For this query, the number of one-typo words is 7*25=175 and two-typo words is 25+(6*5*25)=775.


### Behavior prior to the refactor



All the derivations will be considered

### Behavior after the refactor



- Only 150 one-typo derivations will be considered
- Only 50 two-typo derivations will be considered
- The order of the considered derivations is unspecified

## Rationale



Performance: Not limiting the number of derivations to consider means that a query can take an arbitrary long amount of time and memory.

## Test cases



TBC

**Comment by dureuill** [comment]
# Relevancy change: Limit the number of synonyms

- short name: limit_synonyms
- Perceived impact: Niche, engine implementers
- Needs specs: No
- Involved ranking rules if applicable: typo, words, proximity
- Implementation status: Implemented

## Example

### Affected query



- Let there be a dataset containing all words from `aaaaaaaa` to `zzzzzzzz`.
- Let the synonyms be configured so that any derivation of `aaaaaaaa` is a synonym of `aaaaaaaa`
- Let the search query `aaaaaaaa`.


### Behavior prior to the refactor



All the synonyms of `aaaaaaaa` will be considered

### Behavior after the refactor



- Only 50 synonyms will be considered.
- If some synonyms are multi-word synonyms, only 100 synonym words will be considered.


## Rationale



Performance: Not limiting the number of synonyms to consider means that a query can take an arbitrary long amount of time and memory.

## Test cases



TBC

**Comment by curquiza** [comment]
Since the refactoring has been fully implemented, I close the tracking issue. The remaining issues we want to implement later are still opened

Well done team!
