### ISSUE TITLE
dont add document with key have id 

### ISSUE THREAD

**Issue by vahidalvandi** [meilisearch/meilisearch#3585]
meilisearch v1.0

in bellow sample dont work

```
[
    'id'=>1,
    'cat_id'=>2
]
```

because have **'cat_id'**  It has been commented that the word **id** is sensitive 

If we change cat_id to cat_idd, it will be correct

**Comment by oluademola** [comment]
Hello @vahidalvandi ,

This is true, and it is the expected behavior. There was a revamp of the primary key inference in v1.0, which means that _**If multiple attributes ending with id are detected, Meilisearch will ask you to specify the primary key instead of choosing the first found one**_. It was mentioned as a breaking change, and you can find more information about it in the release note [here](https://github.com/meilisearch/meilisearch/releases/tag/v1.0.0).

**Comment by vahidalvandi** [comment]
how i can solve this ? and do i can set 'id' for primary key ?

**Comment by oluademola** [comment]
Hello @vahidalvandi.  Yes, you need to specify the primary key manually using the `primaryKey` query parameter. For example, if you want id as the primary key your request request can be like this: `-X POST 'http://localhost:7700/indexes/books/documents?primaryKey=id'`

**Comment by curquiza** [comment]
I close this issue then. Feel free to ask to re-open if needed 😊
