### ISSUE TITLE
Incrementing the offset of a search increases the total number of results

### ISSUE THREAD

**Issue by pedrosilva57** [meilisearch/meilisearch#3657]
**Describe the bug**
When I search for the term "4fun", and then navigate to the seventh and last page (considering a limit of 12), with an offset of 72, the number of estimated total hits increases from 83 to 194. This bug seems to be related to issue #3656.

**To Reproduce**
1. To reproduce this bug, it is necessary to have at least 100 indexed documents,  that include the term "4fun" or part of this term.
2. Search for the term "4fun" with an offset of 0 (it's unnecessary to set a limit for this search), and observe the number of estimatedTotalHits returned.
3. Repeat the same, and increase the offset, until the number of **estimatedTotalHits** goes up. In my case was 72 because the page size considered was 12, so this was the offset for the last page.

**Expected behavior**
The number of **estimatedTotalHits** should always remain the same, no matter what offset is passed.

**Screenshots**
In this example, I've used Postman to do search in an index with a POST route:
<img width="100" alt="image" src="https://user-images.githubusercontent.com/11228114/230936809-12de07e2-1372-4ee1-9c4f-c6aa26320a58.png">
It has three attributes: the search query, the offset and the limit.
<img width="142" alt="image" src="https://user-images.githubusercontent.com/11228114/230937566-951dbc46-bc10-483b-a281-d5dc16fba403.png">
The estimated total hits is **83**.

If I then increase the offset from 0 to 72, simulating the navigation to the last page (page 7), considering a page size of 12,
<img width="99" alt="image" src="https://user-images.githubusercontent.com/11228114/230939677-0cd0e056-7abb-463a-b142-3cf4ed6ea84c.png">
the estimated total hits changes to **194**, 111 more results.
<img width="144" alt="image" src="https://user-images.githubusercontent.com/11228114/230939832-101833da-e425-43ac-97a6-cf685778b41e.png">

**Meilisearch version:**
v1.1.0

**Additional context**
- Meilisearch instance running in a Azure Web App
- Requests made in Postman

**Comment by oluademola** [comment]
Hello @pedrosilva57,

Thanks for the report. Indeed you may experience some inconsistencies with the `estimatedTotalHits` counts using different offsets. However, this is not a bug but rather the expected behavior; the search result count returned is just an **estimation** it is not **exhaustive**. As mentioned in the [docs](https://docs.meilisearch.com/reference/api/search.html#exhaustive-and-estimated-total-number-of-search-results): 

> By default, Meilisearch only returns an estimate of the total number of search results in a query: estimatedTotalHits. This happens because Meilisearch prioritizes relevancy and performance over providing an exhaustive number of search results.

 If you want an exhaustive number of search results, you should use the `hitsPerPage` and `page` search parameters in your query. You can find more information in the [dedicated documentation](https://docs.meilisearch.com/reference/api/search.html#exhaustive-and-estimated-total-number-of-search-results).
