### ISSUE TITLE
Update messages pointing to the docs website

### ISSUE THREAD

**Issue by guimachiavelli** [meilisearch/meilisearch#3668]
**Describe the bug**
The new documentation website changed its URL from https://docs.meilisearch.com to https://meilisearch.com/docs. Additionally, we have dropped `.html` extensions from all our links.

These two changes should be reflected in any messages referencing the docs site.

**To Reproduce**
For example, when a user launches `meilisearch`, the welcome message includes this paragraph:

`We collect anonymized analytics to improve our product and your experience. To learn more, including how to turn off analytics, visit our dedicated documentation page: https://docs.meilisearch.com/learn/what_is_meilisearch/telemetry.html`

I'm sure there are many others across the codebase that I'm not immediately aware of.

**Expected behavior**
The updated launch message should look something like this:

`We collect anonymized analytics to improve our product and your experience. To learn more, including how to turn off analytics, visit our dedicated documentation page: https://meilisearch.com/docs/learn/what_is_meilisearch/telemetry`

**Meilisearch version:**
NA

**Additional context**
If you prefer, you may want to use the `www` in the links: `https://www.meilisearch.com/docs` — the @meilisearch/docs-team has no preference.

Thanks ❤️

**Comment by harshmange44** [comment]
hey, I'd like to fix this

**Comment by curquiza** [comment]
Hello @harshmange44 

Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

For your information, we prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the volunteer contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/CONTRIBUTING.md).   

We are looking forward to reviewing your PR 😊

**Comment by roy9495** [comment]
Can someone please review this #3710
