### ISSUE TITLE
Korean synonyms included space

### ISSUE THREAD

**Issue by corean** [meilisearch/meilisearch#3669]
```
PUT http://localhost:7700/indexes/restaurants_index/settings/synonyms
Content-Type: application/json

{
  "퀸즈" : [
    "퀸스"
  ],
  "퀸스" : [
    "퀸즈"
  ]
}
```

```
GET http://localhost:7700/indexes/restaurants_index/settings/synonyms
Accept: application/json

# result
{
  "퀸 즈": [
    "퀸스"
  ],
  "퀸스": [
    "퀸 즈"
  ]
}
```
why included space ? 
퀸즈 > 퀸 즈

**Comment by ManyTheFish** [comment]
Hello @corean,

your issue seems highly related to https://github.com/meilisearch/meilisearch/issues/2760, Meilisearch prints the tokenized version of the synonym, it's a known issue but we didn't find the time to fix it so far, I am really sorry for this.

If your issue is related, please copy and paste your message into the other issue and close this one,

Thank you for your time!

**Comment by corean** [comment]
Thank you~  @ManyTheFish
