### ISSUE TITLE
AWS Meilisearch Allow Saving to EBS Volume

### ISSUE THREAD

**Issue by czabriskie** [meilisearch/meilisearch#3682]
I like the tool, but I don't like how data is stored on the EC2 instance in AWS and as far as I can tell can't be changed to live on an EBS volume that isn't the root instance.

Sorry not a bug, but there wasn't a place for this type really.

**Comment by dgsharpe** [comment]
You can use the `--db-path` argument to specify a path of your choosing for data storage.

**Comment by oluademola** [comment]
Hello @czabriskie. Thanks for the report. I don't have much context, but I'm curious to know what happens when you specify Meilisearch's db path to an EBS volume. My understanding from the docs [here](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volumes.html) is that the EBS volume is directly connected to EC2, so I see no reason why it wouldn't work.

**Comment by gillian-meilisearch** [comment]
I'll close this issue out due to inactivity. Thanks for the report to begin. Please feel free to re-open if there is additional information or response we can continue with.
