### ISSUE TITLE
Database not compatible upgrading from 1.0.2 to 1.1.0

### ISSUE THREAD

**Issue by Pablo-Aldana** [meilisearch/meilisearch#3711]
**Describe the bug**
When trying to upgrade from version 1.0.2 to version 1.1.0 Meilisearch won't start throwing the following message:

Error: Your database version (1.0.2) is incompatible with your current engine version (1.1.0).
To migrate data between Meilisearch versions, please follow our guide on https://docs.meilisearch.com/learn/update_and_migration/updating.html

If you got to this URL it just shown a 404 error and I can't find an upgrade guide from 1.0.2 to 1.1.0. For what I look into the release doc there shouldn't be any issue or special instruction for the migration.

I have also tried to version 1.1.1 but the same error is displayed and according to the notes it should be upgraded first from 1.1.0

**To Reproduce**
1. Stop the docker container
2. Run the container with the desired new version
```
run -ti -d --restart=always \
  -p 7700:7700 \
  -e MEILI_ENV=production \
  -e MEILI_MASTER_KEY="XXX"\
  -v /Users/pablo/psb/melisearch/meili_data:/meili_data \
  getmeili/meilisearch:v1.1.0 
```

**Expected behavior**
Meilisearch should start without issues.

**Meilisearch version:**
1.0.2 - 1.1.0 - 1.1.1

**Additional context**
Additional information that may be relevant to the issue.
Running on docker
Mac OS 13.2.1

Many thanks

**Comment by oluademola** [comment]
Hello @Pablo-Aldana. Sorry for the inconvenience. You should be able to access the documentation now. Regarding your issue, the error indicates that the problem is due to existing v1.0.2 `data.ms`, please keep in mind that at the moment, the `data.ms` is only compatible with the version of meilisearch used to create them. To backup your data, you can use the dump as mentioned in this [guide](https://www.meilisearch.com/docs/learn/update_and_migration/updating), and to resolve the error you need to delete the data.ms folder in `/Users/pablo/psb/melisearch/meili_data:/meili_data`
