### ISSUE TITLE
Recommended system requirements

### ISSUE THREAD

**Issue by nithinkashyapn** [meilisearch/MeiliSearch#374]
Hey,

This is one of the best open source search projects i have used. Thank you so much for making it FOSS.

What is the recommended system requirements to run this on a bare metal server for production environments? I saw your [blog post](https://blog.meilisearch.com/search-rust-crates-meili/) where you guys ran it on Heroku so i believe the memory consumption is negligible; but that being said what would be the ideal server specs?
 
Thank you!

**Comment by Kerollmops** [comment]
First of all thank you for these kind words,

We did not run the MeiliSearch server on Heroku, we run it on our internal DigitalOcean Kubernetes cluster, that is 8GB of RAM, 4vCPU an a good SSD. I have updated the blog post to avoid the confusion. The only thing that run on Heroku are the programs that update this MeiliSearch server.

If you want the ideal server specs I recommend you to buy the fastest SSD according to [the benchmarks done by intel with LMDB](http://www.lmdb.tech/bench/optanessd/imdt.html), it seems to be the Intel Optane.

And because we use LMDB we need enough ram to put the MeiliSearch database in it, this way we avoid disk lookups. I recommend you to read [the blog post to understand how it works](https://symas.com/understanding-lmdb-database-file-sizes-and-memory-utilization/).

Also, don't forget the CPU, because we make the search queries single threaded to avoid impacting concurrent queries, you will need the fastest single core CPU.

But if you want intermediate specs, It will entirely depends on the data you want to index, the number of times you inject data in the engine and the search throughput necessary.

As a simple answer: Buy an SSD, enough RAM to fit the database in it and a good enough CPU 😃 

Best regards,

**Comment by nithinkashyapn** [comment]
Thank you so much for the update.

Will create a testing environment on DO and then decide on the specs.

**Comment by Kerollmops** [comment]
Nice, comment on / reopen this issue if you have more questions about the specs!

**Comment by SorryGames** [comment]
Hello friends,
first of all you have developed and maintain a great tool, thank you all.

Besides I'm going to understand some performance questions.

**1) understanding how and when meilisearch use RAM & Disk.**
as you write [here](https://docs.meilisearch.com/learn/advanced/storage.html#memory-mapping) you use memory-mapped file to map virtual memory to physical memory (either RAM or Disk).
The questions is about how RAM & Disk is used by Meilisearch...
For example you have:
1) document (as JSON file)
2) search structure (like btree-based DB)
3) ... anything else I don't know about

As I know technologies like Algolia places search structure only in RAM so in order to index big dataset you have to install more RAM. 
In case of Meilisearch it can store search structure in RAM & Disk (if it has not enough RAM), can't it?

2) If my assumptions above are truth, then...
How can I understand does Meilisearch has enough RAM to store all search structures here?
I believe it's would be very useful to have some sort of API calls to print allocated memory (virtual memory), required RAM & Disk space like [here](https://docs.meilisearch.com/learn/advanced/storage.html#measured-disk-usage)? 


P.S. I found API call like `<url>/stats` that can be used to retrieve `databaseSize` in bytes. However I can't found this information  useful because I still do not understand how RAM I need to make my search as fast as possible.


Hope you are all fine,
Matvey
