### ISSUE TITLE
Do not enforce lat/long to be between -90/-180 and 90/180

### ISSUE THREAD

**Issue by rbozan** [meilisearch/meilisearch#3763]
**Description**
Whenever you currently want to use the geolocation feature like so:
```ts
		return index.search(searchInput, {
			sort: [`_geoPoint(${center.x}, ${center.y}):asc`]
		});

```

It tells you that the latitude must be between -90 and 90. While this does make sense for the "real world", this enforcement means you can not use MeiliSearch for searching something within a virtual world like a game where the lat/long could be way bigger than this.

**Basic example**
I'd like to not have this enforcement between values which make sense in the real world, or at least have a way to disable the warning.

**Other**
I'd like to know if there's any technical reason why this enforcement is made, or is it just that humans are not to always be trusted?

**Comment by irevoire** [comment]
Hey @rbozan.
Actually, the lat and lng only describe the angular degrees from the center of the earth to the surface.
It doesn't make sense to go over 90 or below -90 since these are angles (and I don't really see how this is an issue for you, tbh)

What is absolutely wrong, though, is the distance returned when computing a geo sort because that's the part that is tied to the size of the earth specifically!

The other issue you could have with Meilisearch is that it enforces the usage of a “round” planet. If your world is supposed to be flat, it doesn't work, either.

-----

We made it like that because that's what everyone was asking for 😅
Tbh you're the first one I've seen that try to use meilisearch with the geo search feature on something other than Earth

**Comment by rbozan** [comment]
> Hey @rbozan.
> Actually, the lat and lng only describe the angular degrees from the center of the earth to the surface.
> It doesn't make sense to go over 90 or below -90 since these are angles (and I don't really see how this is an issue for you, tbh)
> 
> What is absolutely wrong, though, is the distance returned when computing a geo sort because that's the part that is tied to the size of the earth specifically!
> 
> The other issue you could have with Meilisearch is that it enforces the usage of a “round” planet. If your world is supposed to be flat, it doesn't work, either.
> 
> -----
> 
> We made it like that because that's what everyone was asking for 😅
> Tbh you're the first one I've seen that try to use meilisearch with the geo search feature on something other than Earth

Haha it seems indeed my case is a bit of a nice. I just have a 2d world on a regular flat plane where I'd like to be able to search for things on the plane. It's indeed not lat/long but just x/y actually. But because these are unable to get a distance (I guess?) I'm trying with _geo instead.

**Comment by irevoire** [comment]
Yeah, that's what I thought.
Currently, I don't think we have any nice solution to handle that.
Which operation do you need?

**Comment by rbozan** [comment]
For my use case I basically want to sort the search results by distance from the center of the viewport of the game.

Just imagine you have objects with x+y coordinates and I'd want to do a search on these objects sorted by distance.

It's this operation according to the docs:


```
client.index('restaurants').search('', { sort: ['_geoPoint(48.8561446, 2.2978204):asc'], })
```

**Comment by curquiza** [comment]
Hello @rbozan and @irevoire 
Thank you for your feedback

Pinging our PMs @macraig and @gmourier for your information

**Comment by macraig** [comment]
Hi @rbozan , as this is currently a feature request I'll close this issue and I've opened a product discussion for it in our Product repo: https://github.com/meilisearch/product/discussions/676

Feel free to add more to that feature proposal issue!
