### ISSUE TITLE
bug:Issue with addDocuments not being applied in v1.1.1

### ISSUE THREAD

**Issue by sjy-dv** [meilisearch/meilisearch#3767]
This user used v0.28.0. There was no problem in the previous version, but the recent index update and tokenization proceeded very satisfactorily. Of course, the amount of data was not large, so I changed it as it is and put the data in batches, but some indexes are applied and the rest of the indexes are not.

I thought it would take some time to index, so I waited but it didn't take effect even after several hours. There are about 3000 data and about 20 columns, and sort and filter are applied as they are. did i do something wrong?

**Comment by oluademola** [comment]
Hello @sjy-dv. I don't think it's a bug; it might be due to the new primary key inference behavior introduced in v1. Can you please check the [taskObject](https://www.meilisearch.com/docs/reference/api/tasks#task-object) of the document addition task to get some context about the issue?

**Comment by oluademola** [comment]
Hello @sjy-dv. Thank you for your response. For sure, the primary key inference suggestion was a guess and a thing I thought you could check, as there wasn't much contextual info about the issue. Do you mean your issue is related to version compatibility? And updating the client fixes the issue? If not, have you checked the taskObject for the document addition task as previously mentioned? Could you please let me know what client you're using and its version?

**Comment by LatVAlY** [comment]
Same here at version 1.2 & Go package 0.25 the document creation was successful but nothing is in my index. (checked my index/ master key)

while creating a document using HTTP API it works but Golang doesn't.

any idea how to resolve this?

**Comment by oluademola** [comment]
Hello @LatVAlY. The document addition probably failed. Could you let me know how you confirmed it was successful? Did you double-check the [task endpoint](https://www.meilisearch.com/docs/reference/api/tasks)?

**Comment by gillian-meilisearch** [comment]
I'll close this issue out due to inactivity. Please feel free to re-open if there is additional information to move this forward again. Thanks!
