### ISSUE TITLE
Ranking of exactness in arrays

### ISSUE THREAD

**Issue by Koopzington** [meilisearch/MeiliSearch#3856]
**Describe the bug**
It seems that the ranking of the exactness isn't as high when the searched string is inside an array.

I've written a little tool that would help me map data from one website to data from another site.
For this i imported the data that should be searched from site A into Meili and then searched the index with the native title provided from site B. However as the data from site A didn't have any field only containing the main native title, i stored all titles for a work into an array (as seen in the screenshot). With some works' titles containing very few words the initially mentioned behaviour became noticeable.

As indicated by the scrollbar on the screenshot this resulted in absolute matches of the title not being on the very top of the results and instead some results where the search term was *part* of the title were on top.

I was asked to create this issue to discuss on whether this behaviour is actually a bug or working as intended.

**To Reproduce**
1. Build an index containing documents that have arrays of strings (ranging from one to several words)
2. Search the index for an exact match on one of those one-word strings
3. See the 100% match being ranked lower than results where searched term is only a part of the string

**Expected behavior**
Results that contain absolute matches in arrays should be ranked higher by default.

**Screenshots**
![image](https://github.com/meilisearch/meilisearch/assets/3015529/04e9b407-6f6e-453d-803c-b25aef5235df)

**Meilisearch version:**
v1.2.0

**Comment by oluademola** [comment]
Hello @Koopzington, thank you for the report. I'd like to ask if any changes have been made to your ranking rule settings. If there were any modifications, could you please share the details with me? Thanks in advance 🙏

**Comment by Koopzington** [comment]
Well i can confirm that with the default ranking rules the search is working as expected when the string i'm searching for is stored in a single field.
However when searching for a string that's stored together with other strings in an array field the initially described behaviour does still happen.

![image](https://github.com/meilisearch/meilisearch/assets/3015529/375a5a37-8ac3-4685-ac49-c58ad999b4c8)

For reference my current ranking rules are
```
[
  'native_title:asc',
  'other_titles:asc',         
  'words',
  'exactness',
  'typo',
]
```
and i'm still seeing the same behaviour.
Another observation i just made is that despite having `other_titles` ranked so high i'm still getting results based on other matches on top:
![image](https://github.com/meilisearch/meilisearch/assets/3015529/30c66811-8fd0-4e3d-ab4f-04f014a5f76b)
It seems like ranking rules don't apply to arrays at all and the order of the fields take priority instead.

**Comment by Koopzington** [comment]
i just confirmed the previously mentioned observation by recreating the index and putting the `native_title` and `other_titles` fields in front of the others and Meili does now indeed rank the results like i expected them be ranked.

![image](https://github.com/meilisearch/meilisearch/assets/3015529/d9af8465-92bb-48b0-bd72-5fdb09d8363c)

**Comment by oluademola** [comment]
Hello @Koopzington. Thank you for sharing your findings. AFAIK, It seems that the issue could be related to the default attribute ranking. By default, documents are ranked based on the order they appear, with matches in the "**native_title**" field ranked higher than those in "**other_title**" fields, and "**other_title**" fields ranked higher than the "**type**" field, and so on.

However, I'm not certain if you have kept the same ranking settings as before excluding the attribute criterion. Could you please confirm if you have followed the same ranking settings as previously?

Thanks in advance.

**Comment by Koopzington** [comment]
@oluademola yes, my ranking rules still don't include `attribute`

**Comment by gillian-meilisearch** [comment]
Hi @Koopzington - I'm just taking a look at your issue here and from what I can see it's the exactness ranking rule that's tipping things for you. I have used the new [scoreDetails feature in v1.3](https://github.com/meilisearch/meilisearch/releases/tag/v1.3.0-rc.1) to check out how the documents are being scored in your scenario. I'll give you the conclusion of what I've seen and then I'll tell you how I got there, it might be useful for your own further investigation and tweaking.

For the search where the term is a string ("native_title") the `exactness` score comes back as an `exactMatch` (score: 1.0). For the search where the term is a string that's inside an array ("other_title") the exactness score comes back as `matchesStart` (score: 0.6666666666666666). Which makes sense given it's part of an overall array and not an exactMatch as such. Given `exactness` is high on your ranking rules listing its likely what's causing what you see.

How I got there.. in v1.3 there is a new feature that will give you a breakdown of how documents are scored. You can try it out on the [most recent Release Candidate](https://github.com/meilisearch/meilisearch/releases/tag/v1.3.0-rc.3). You enable the feature by calling the `/experimental-feature` patching in `{"scoreDetails":true}`. And then when you do a search query pass in these additional parameters with your query: 
```bash
"showRankingScoreDetails": true,
"showRankingScore": true`
```

The returned result will show you a ranking score for the overall document  e.g.
` "_rankingScore": 0.9166666666666666,` as well as a breakdown per ranking rule e.g. 
```bash
  "_rankingScoreDetails": {
                "words": {
                    "order": 0,
                    "matchingWords": 8,
                    "maxMatchingWords": 8,
                    "score": 1.0
                },
                "exactness": {
                    "order": 1,
                    "matchType": "noExactMatch",
                    "matchingWords": 8,
                    "maxMatchingWords": 8,
                    "score": 0.3333333333333333
                },
                "native_title:asc": {
                    "order": 2,
                    "value": "the elven prophecy"
                },
                "other_titles:asc": {
                    "order": 3,
                    "value": "sword of destiny"
                },
                "typo": {
                    "order": 4,
                    "typoCount": 0,
                    "maxTypoCount": 5,
                    "score": 1.0
                }
            }
```

which I think will be super helpful for you to narrow down and tweak with.

Hopefully this helps!
