### ISSUE TITLE
meilisearch continuously eating resources on 10> millions records (infinite loop)

### ISSUE THREAD

**Issue by foremtehan** [meilisearch/meilisearch#3868]
Before I describe the issue, here is the information about my server and meilisearch version:

- Meilisearch v1.2
- Server: 4GB RAM (1gb swap), 2-core CPU (Ampere Arm64 architecture)
- Running on Docker

I didn't have any issues with 7 million documents; everything was fine. However, when I removed the docker volume to try indexing 15 million documents, everything appeared to be fine at first. The indexing was completed in approximately 20 minutes. But then I noticed that meilisearch continued to consume resources, even though there were no more documents left. I checked the size of the docker volume to see if it was increasing, but it wasn't.

If you look at the RAM usage over time 👇, it seems like meilisearch is stuck in an infinite loop:
This is after the indexing is done:

https://github.com/meilisearch/meilisearch/assets/53290883/20e6a4ae-001d-4ba4-af49-46df09d2e16d

https://github.com/meilisearch/meilisearch/assets/53290883/be73feb3-9c8f-42ec-a1a3-cf3ebe5bfcaf

I waited for about 1 hour, but meilisearch didn't stop consuming server resources.

The documents look like these simple dictionaries:

```
{"id":27391776,"line":"They were used in a ritual to summon a god from the depths","start_at":343}
{"id":27391777,"line":"And there's five of them. Here","start_at":346}
{"id":27391778,"line":"My grandfather's piece","start_at":349}
{"id":27391779,"line":"and the one from Martín's bracelet. Give me your pendant","start_at":351}
{"id":27391780,"line":"Your pendant is the third","start_at":360}
```

If you want to reproduce this issue, i can only provide the documents (15m) https://anonfiles.com/edQ9rez0za

**Update**: Is it possible that Meilisearch needs more space, but it calculates the percentage of disk space under the hood and cannot decide what to do?

**Comment by oluademola** [comment]
Hello @foremtehan. Sorry for not getting back to you sooner. I don't have access to the dataset; however, from what I understand and mentioned above in your report, it seems to be related to virtual memory and not real memory. It is nothing to be worried about and is addressed in this [blog post](https://blog.meilisearch.com/dynamic-virtual-address-management/). Also, I'd like to clarify that meilisearch memory management is primarily concerned with allocating memory for indexing, which you can easily manage with the [--max-indexing-memory](https://www.meilisearch.com/docs/learn/configuration/instance_options#max-indexing-memory) parameter; the real memory is calculated and handled by the underlying operating system rather than being directly controlled by meilisearch.
