### ISSUE TITLE
Data persistence in Docker

### ISSUE THREAD

**Issue by francislavoie** [meilisearch/MeiliSearch#387]
Typically when running an app with docker, especially one that handles data storage, a volume is attached to make the data persist between restarts. 

I did find the default file path in the docs here: https://docs.meilisearch.com/advanced_guides/binary.html#environment-variables but I found this tricky to find for a first-time user.

I would recommend adding an option like `-v $(pwd)/data.ms:/data.ms` to the Docker examples so that it isn't forgotten. Don't want people to lose their data!

**Comment by tpayet** [comment]
Hey, thank you for your issue :)
I understand the confusion and I was wondering where in the documentation or the README could we precise the database default path? I understand that the environment variable is maybe quite hard to find for a first-time user
I think that adding this to the docker usage example would make it less readable in the quickstart.

**Comment by francislavoie** [comment]
> I think that adding this to the docker usage example would make it less readable in the quickstart.

True, but data persistence is still pretty important.

It could also be written like this:

```
docker run -it --rm \
    -p 7700:7700 \
    -v $(pwd)/data.ms:/data.ms \
    getmeili/meilisearch
```

**Comment by tpayet** [comment]
As you can see on the [Elastic documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode) or the [postgres one](https://hub.docker.com/_/postgres), the docker image examples do not show the volumes shared. People using docker knows that is is not persistent.

The problem is that MeiliSearch current documentation is not clear enough for first-time users, we should optimize for it. As you said it, you found it tricky to find the environment variables. I wonder where we should say what is the default database path and how to change it without the user having to search through the advanced guides.

**Comment by francislavoie** [comment]
On the same page, they also have this section a bit further down: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_always_bind_data_volumes and for postgres they have a "Where to Store Data" section. Something similar to that is definitely appropriate.

**Comment by tpayet** [comment]
You are right. We will update the appropriate documentation: [meilisearch/documentation#83](https://github.com/meilisearch/documentation/issues/83)

**Comment by yoDon** [comment]
For others who find this issue via google or by following the link from #83, the environment variable documentation mentioned by francoislavoie appears to have moved to https://docs.meilisearch.com/guides/advanced_guides/installation.html#environment-variables-and-flags
