### ISSUE TITLE
[API] Synonym composed of many words

### ISSUE THREAD

**Issue by curquiza** [meilisearch/MeiliSearch#389]
2 issues in [this route](https://docs.meilisearch.com/references/synonyms.html#delete-a-synonym), maybe linked:
- even if the synonym does not exist, it returns a `202 - Accepted` and an `updateId`, it sends it to the queue and marks it as `processed` -> ~~should return a `404` with a body error message.~~ OK
- if the synonym exists and is composed of many words, it sends it to the queue (expected behavior), marks it as `processed` but nothing happened.

### UPDATE:
I noticed that, in general, the routes do not work when the synonym is composed of many words.
These routes include: `get`, `update`, and `delete` for `/indexes/:uid/synonyms/:synonyms` and `:synonyms` is in two or more words.
- `get`: ~~crash, see this [issue](https://github.com/meilisearch/MeiliSearch/issues/386)~~ crash solved. But still does not work, see this [issue](https://github.com/meilisearch/MeiliSearch/issues/392)
- `update`: does not update and create a new synonym with the `%20` inside. (So, The update route doesn't only update, it can also create a new synonym, is this behavior expected?)
- `delete`: does not delete.

**Comment by Kerollmops** [comment]
First issue can partially fixed, we will not return a 404 because the update system is a queue it means that checking if a synonyms exists and returning a 404 if doesn't is wrong as it could have been sent in a previous update that will be processed and is currently enqeued.

However, the update is marked as processed even if no synonyms have been deleted, I think it can be improved a little bit. It has been done like that because it would be strange to mark an update as erroneous if only one synonym has been deleted because it doesn't exist. I would like to keep the responses as is for the moment.

Second issue, what do you mean by nothing happened? Do you mean that the synonym is ignored? Doesn't it appear in the synonyms list?

**Comment by curquiza** [comment]
Ok for the first point :)

For the second, the synonym is not deleted.

I've just noticed that the route Update does work either with synonyms composed of many words.
In general, the routes do not work when a synonym is composed of many words. I'm going to update my issue.
