### ISSUE TITLE
Compatibility issues.

### ISSUE THREAD

**Issue by cparkinsonMYCM** [meilisearch/meilisearch#3914]
**Describe the bug**
[V1.0 release](https://blog.meilisearch.com/whats-new-in-v1-0/) states
> We are proud to release a completely stable version of Meilisearch, which will guarantee compatibility with future versions of Meilisearch.

And yet I am receiving this:
`Your database version (1.1.1) is incompatible with your current engine version (1.2.0)`

Launching with Docker, via [DDEV](https://ddev.readthedocs.io/en/stable/).
I can't see how to find the volume to delete it to start fresh, but that shouldn't be the solution.

**Meilisearch version:**
[e.g. v1.2.0]

**Comment by oluademola** [comment]
Hello @cparkinsonMYCM,

Sorry for the confusion. I understand your concerns, and I'd like to provide further clarification regarding the statement you mentioned above because it is more than that.

The v1 release meant that there wouldn't be any breaking changes in future updates until v2. However, it doesn't imply that different versions of the database are now supported. To better understand what is considered a breaking change and to learn about the exceptions, I encourage you to refer to the versioning policy provided [here](https://github.com/meilisearch/engine-team/blob/main/resources/versioning-policy.md#db-incompatibilities-force-using-a-dump). I hope this clears up any misunderstandings.

As regards the error, the solution is to remove the volume, I believe you should be able to get the list of all your DDEV volumes in docker with `docker volume ls` and then remove it. 

Hope that helps. Thanks

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
