### ISSUE TITLE
JSON match weight is a lot lower than array match weight

### ISSUE THREAD

**Issue by Tarpsvo** [meilisearch/meilisearch#3939]
When searching for "4090" for example (ie in graphics card RTX 4090), it was matching a lot of SKU's containing 4090 over names containing "4090" when the name is a **key-value object** or as the Meilisearch UI calls it: JSON.

HOWEVER! This **does not happen** when the "name" attribute is a **string** or an **array**, it will bring the products with 4090 in their name as first. I encountered this in **1.3.0-RC2**.

I believe the objects should behave the same way as arrays and their keys shouldn't really be accounted for. This issue is easily fixable by me on my project's side as well, by just turning the "name" attribute into an array (and even filtering out duplicates, as many products have the same name no matter the language).

Search query: 4090

Config:
```
searchableAttributes: ['name', 'attributes', 'skus', 'eans']
rankingRules: ['sort', 'words',  'attribute', 'exactness', 'typo', 'stock:desc', 'proximity']
typoTolerance: [
  'disableOnAttributes' => ['skus', 'eans'],
  'minWordSizeForTypos' => [
    'oneTypo' => 6,
    'twoTypos' => 12,
  ],
]
```

Dataset:
https://gist.github.com/Tarpsvo/d45d1ca0e0312eeb13fab2e4ebddaeab

Results:
```
1:
Name: {
  "et": "Monitor 27 inches VA27EQSB IPS",
  "en": "Monitor 27 inches VA27EQSB IPS",
  "ru": "Monitor 27 inches VA27EQSB IPS"
}

Skus: ["409052", "90LM0559-B01170", "VA27EQSB"]

2:
Name: {
  "et": "Monitor ZenScreen Ink MB14AHD 14 inch MB14AHD",
  "en": "Monitor ZenScreen Ink MB14AHD 14 inch MB14AHD",
  "ru": "Monitor ZenScreen Ink MB14AHD 14 inch MB14AHD"
}

Skus: ["409051", "90LM063V-B01170", "MB14AHD"]

... 3-10 ...

11: // I expect this to be first, as it has a 100% match (4090) in its "name" attribute
Name: {
  "et": "Gigabyte GeForce RTX™ 4090 GAMING OC 24G DLSS",
  "en": "Gigabyte GeForce RTX™ 4090 GAMING OC 24G DLSS",
  "ru": "Gigabyte GeForce RTX™ 4090 GAMING OC 24G DLSS"
}

Skus: ["GV-N4090GAMINGOC-24GD", "RTX4090GAMINGOC24G"]
```

When the "name" attribute is an array or a string, the order of results is essentially flipped, moving the RTX 4090 to the first position and the SKU matches to the bottom positions.

**Comment by gillian-meilisearch** [comment]
Hi [Tarpsvo](https://github.com/Tarpsvo), thanks for the input. I have been looking into it a little here for you. I believe the reason is to do with how [objects are flattened in the background for indexing](https://www.meilisearch.com/docs/learn/advanced/datatypes#objects). So for example:

An object such as the below gets flattened during indexing from 
```
"name": {
  "et": "Gigabyte GeForce RTX™ 4090 GAMING OC 24G DLSS",
  "en": "Gigabyte GeForce RTX™ 4090 GAMING OC 24G DLSS",
  "ru": "Gigabyte GeForce RTX™ 4090 GAMING OC 24G DLSS"
}
```

into 

```
{
  "name.et": "Gigabyte GeForce RTX™ 4090 GAMING OC 24G DLSS",
  "name.en": "Gigabyte GeForce RTX™ 4090 GAMING OC 24G DLSS",
  "name.ru": "Gigabyte GeForce RTX™ 4090 GAMING OC 24G DLSS"
}
```

Whereas a string based field is treated as such:
`"name": "Gigabyte GeForce RTX™ 4090 GAMING OC 24G DLSS",`



When your searchable attributes only includes `name` :
`searchableAttributes: ["name", "attributes", "skus", "eans"]`
then `name.en`, `name.et` or `name.ru` are not calculated for in the same way.



You could potentially add `name.en`, `name.ru` and `name.et` to your searchable attributes order to try and tweak things further.


If you haven't looked into it already the new [scoring details feature](https://github.com/meilisearch/meilisearch/releases/tag/v1.3.0-rc.1) in v1.3 is fantastic for understanding how things are ranked and scored per ranking rule. It's worth checking out. 

You can try it out on the [most recent Release Candidate](https://github.com/meilisearch/meilisearch/releases/tag/v1.3.0-rc.3). You enable the feature by calling the `/experimental-feature` patching in `{"scoreDetails":true}`. And then when you do a search query pass in these additional parameters with your query: 
```bash
"showRankingScoreDetails": true,
"showRankingScore": true
```

The returned result will show you a ranking score for the overall document  e.g.
` "_rankingScore":  0.6893939393939394,` as well as a breakdown per ranking rule e.g. 
```bash
   "_rankingScoreDetails": {
       "words": {
           "order": 0,
           "matchingWords": 1,
           "maxMatchingWords": 1,
           "score": 1.0
       },
       "typo": {
           "order": 1,
           "typoCount": 0,
           "maxTypoCount": 1,
           "score": 1.0
       },
       "proximity": {
           "order": 2,
           "score": 1.0
       },
       "attribute": {
           "order": 3,
           "attribute_ranking_order_score": 0.5,
           "query_word_distance_score": 0.8181818181818182,
           "score": 0.4090909090909091
       },
       "exactness": {
           "order": 4,
           "matchType": "noExactMatch",
           "matchingWords": 1,
           "maxMatchingWords": 1,
           "score": 0.3333333333333333
       }
   }
```
You can test out the impact of your searchableAttributes changes, or other ranking rule changes there.

Hopefully this helps

**Comment by Tarpsvo** [comment]
Heya Gillian! Thank you very much for the response. The logic behind this actually does make sense. :) I will definitely look into the new scoring details function next time I encounter an anomaly.

Thanks again for your input and help!
