### ISSUE TITLE
*error when build source code  v1.2 on centos 7.5

### ISSUE THREAD

**Issue by unihon** [meilisearch/meilisearch#3943]
**error when build source code  v1.2 on centos 7.5 **

**To Reproduce**
1. clone code
2. git checkout latest
3. rustup update
4. cargo build --release
5. See error

**Expected behavior**
build from the source code on centos 7.5, but is raise error when build lindera-unidic

```bash
error: failed to run custom build command for `lindera-unidic v0.25.0`
````

**Screenshots**
<img width="1920" alt="image" src="https://github.com/meilisearch/meilisearch/assets/42078581/2b76b35e-f20e-4701-ae8a-1e72d9493cda">

**Meilisearch version:**
[v1.2]

**Additional context**
 
OS: centos 7.5
gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)
rust: 1.71.0 (8ede3aae2 2023-07-12)

**Comment by gillian-meilisearch** [comment]
Hey @unihon sorry to see you're experiencing an issue building the project 😢 Looking at your error it seems to be suggesting a timed-out response on that package 🔍 

Some possibilities there include there being a network issue getting to the package, or issues with the cache in the package manager 🤔 Have you tried clearing the cache on Cargo already? Failing that, would you be aware of any networking problems or blockers to getting to the package? Otherwise, have you tried running it more than once to ensure it wasn't an availability issue on the package? 

These are some options to try out to begin, hopefully they can help. Do let us know how you get on. Thanks!

**Comment by LinHeLurking** [comment]
After reading source codes, I found that it comes from `lindera-unidic`. `lindera-unidic` will try to download [a large `.zip` file](https://drive.google.com/uc?export=download&confirm=yes&id=1LsYNZqw_ep1VJf3p49NZd9UTYaRq-V4p) if it cannot be found in local `/target/debug/build/lindera-unidicxxxx/out/` path.  If you have unstable connection to Google (which is a common case in China Mainland), you may download it through proxy. Unfortunately, to download files,  `lindera-unidic` utilizes `ureq`, which ignore `http_proxy` envrionment variable. You can try my [patched version of `ureq`](https://github.com/LinHeLurking/ureq/tree/proxy) and append these lines in `Cargo.toml` in `meilisearch`:

```
[patch.crates-io]
ureq = { git = "https://github.com/LinHeLurking/ureq.git", branch = "proxy" }
```

Then clean cargo cache, set `http_proxy` environment variable and build it again. You may need to run `cargo build` in terminal with proper `http_proxy` set. Because IDE (at least my CLion) might fail to pass such environment variables to sync procedure even though you explictly set it in IDE. 

Once correctly built in terminal, following builds in IDE will work as wished.

**Comment by unihon** [comment]
Thanks, guys, I solved the problem by updating a newer version of gcc
