### ISSUE TITLE
Investigate indexing performance issues

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#4032]
We noticed performance degradation recently, on the current commit on `main` (after v1.4.0-rc.0 release)
We need to investigate and open issues if necessary.
We suppose the issue was introduced in v1.3.X, since we added a lot in v1.3.0, and not in v1.4.0

- The geosearch became 10% slower (+5s on 50s)

![Untitled](https://github.com/meilisearch/meilisearch/assets/20380692/232c05a3-7194-4485-8dc4-3d25a9730fc2)

- The wiki became became 8% slower (+~50s on 570s)Both of these changes happened between 2023/06/18 and 2023/08/01 when the benchmarks were disabled thus we can’t link the change to a single commit or PR

![Untitled](https://github.com/meilisearch/meilisearch/assets/20380692/67789b8f-78a0-4717-a7ec-e0fdeab20676)

**Comment by ManyTheFish** [comment]
Hello,

After some investigations with @Kerollmops, we discovered that the performance regression's main part comes from #3866. This PR aimed to prepare the separator customization feature by implementing a new segmenter based on custom separators. This PR changed some behaviors in Meilisearch:
- `-` and `_` are considered separators by default
- `()`, `[]` are no more considered hard separators
- `,` and `.`  are no longer considered hard separators, but `, ` and `. ` (`comma + space` and `dot + space`) are.

These changes impact the indexing by raising the number of words to index (`bat-man` is now split into 2 words) and the proximities between words (`Paris (France)` are now considered near together).
More specifically on the `geosearch dataset`, it's not due to the geosearch but due to the searchable field contained in the dataset, I put below an example:
```json
{
    "geonameid": "3688689",
    "name": "Bogotá",
    "asciiname": "Bogota",
    "alternatenames": "BOG,Bagata,Bogot,Bogota,Bogoto,Bogotà,Bogotá,Boqota,Buoguota,Bógóta,Mponkota,Santa-Fe-de-Bogota,Santafe de Bogota,Santafe de Bogotá,Santafé de Bogotá,Wukuta,beageatta,bo ge da,bogota,bokota,bwghwta,bwgwta,bwgwth,bwjwta,pokotta,Μπογκοτά,Багата,Богота,Боґота,Санта-Фе-де-Богота,Բոգոտա,באגאטא,בוגוטה,بوجوتا,بوغوتا,بوگوتا,بگوٹا,بۆگۆتا,बोगोटा,बोगोता,বোগোতা,ਬੋਗੋਤਾ,ବୋଗୋଟା,பொகோட்டா,ಬೊಗೋಟ,ബൊഗോട്ട,โบโกตา,པོ་གོ་ཏ,ဘိုဂိုတာမြို့,ბოგოტა,ቦጎታ,ទីក្រុងបូកូតា,ボゴタ,波哥大,보고타",
    "_geo": {
        "lat": 4.60971,
        "lng": -74.08175
    },
    "country code": "CO",
    "population": 7674366,
    "timezone": "America/Bogota",
    "country": "Colombia"
}
```

In this dataset the fields `name`, `asciiname` and `alternatenames` are searchable.
As we can see the words in the field `alternatenames` are separated by `,` and not by `, ` (`comma + space`), this means that we are now considering that the words are near together which raises the time spent to compute the proximities.
We have tried to create a new dataset by replacing all the commas with comma+space and we reduce by around 12% the indexing time of the `geosearch dataset`.

**Comment by curquiza** [comment]
thank you @ManyTheFish for the update!

So the performance loss is not about geosearch or datasets with big fields, but more datasets containing a lot of punctuation.
This loss has been introduced in v1.3.0.

After discussing with @Kerollmops, we decided to close the issue.
- the loss of indexing speed is for a gain of relevancy
- for v1.5.0 we are working on indexing speed. So we plan to save more time with indexing and still having the relevancy improvements at the same time
