### ISSUE TITLE
Facet search and facets in search inconsistency

### ISSUE THREAD

**Issue by admirlju** [meilisearch/meilisearch#4060]
**Describe the bug**
In the facet search documentation and how it's implemented facets search can't be done on numerical values. But why if adding a facets parameter for attributes of numeric type in the search query body does it work?

**To Reproduce**
1. Create an index, with attributes of numerical type
2. Add the attributes to `filterableAttributes`
3. Populate the index
4. Using search add facets parameter containing attributes that are of numerical type. In response, you get populated `facetDistribution`
5. Using facet search (/facet-search), search for the same `facetName` as in the previous point and you'll get empty `facetHits`

**Expected behavior**
I'd expect either for it to be populated in both cases or empty in both cases.

**Meilisearch version:**
v1.3.1

**Comment by curquiza** [comment]
Hello @admirlju 

Sorry, so far, Meilisearch does not support face search for numbers, as written [here in our odcs](https://www.meilisearch.com/docs/reference/api/facet_search#perform-a-facet-search)

A workaround could be to convert your numerical values into strings.

If the workaround does not work for you, you can open [a discussion here](https://github.com/meilisearch/product/discussions) so that our product team can consider it and better know about your usecase. Please add as many details as you can so that we are sure to understand your specific need 😊 

Thank you!

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
