### ISSUE TITLE
Can't filter on attribute containing backslashes after upgrade

### ISSUE THREAD

**Issue by goldmerc** [meilisearch/meilisearch#4064]
**Describe the bug**
After upgrading to 1.3.4 from 1.3.1, filtering on an attribute which contains a backslash throws this error...

> Was expecting an operation '=', '!=', '>=', '>', '<=', '<', 'IN', 'NOT IN', 'TO', 'EXISTS', 'NOT EXISTS', 'IS NULL', 'IS NOT NULL', 'IS EMPTY', 'IS NOT EMPTY', '_geoRadius', or '_geoBoundingBox' at 'App\\\\Model\\\\Test = Foo'.\n1:21 App\\Model\\Test = Foo" 

**To Reproduce**
```
curl \
  -X POST 'http://localhost:7700/indexes' \
  -H 'Authorization: Bearer KEY' \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "uid": "test"
  }'

curl \
  -X PUT 'http://localhost:7700/indexes/test/settings/filterable-attributes' \
  -H 'Authorization: Bearer KEY' \
  -H 'Content-Type: application/json' \
  --data-binary '[
    "App\\Model\\Test"
  ]'

curl \
  -X POST 'http://localhost:7700/indexes/test/documents' \
  -H 'Authorization: Bearer KEY' \
  -H 'Content-Type: application/json' \
  --data-binary '[
    {
      "id": 1,
      "App\\Model\\Test": "Foo"
    },
    {
      "id": 2,
      "App\\Model\\Test": "Bar"
    }
  ]'  

curl \
  -X POST 'http://localhost:7700/indexes/test/search' \
  -H 'Authorization: Bearer KEY' \
  -H 'Content-Type: application/json' \
  --data-binary '{
    "q": "",
    "filter": "App\\Model\\Test = Foo"
  }'
```

**Expected behavior**
The search should work

**Meilisearch version:**
1.3.4

**Additional context**
Looking through the change log, my best guess is that this issue was introduced by #4038 
I haven't looked at the code though as I've never coded in RUST, so it's just a guess.

**Comment by Kerollmops** [comment]
Hello @goldmerc 👋

Thank you very much for the bug report. There is indeed a bug there. We will take a look this week and hope to fix it before the release of v1.4.0 next Monday 🤞 We need to correctly specify what we need to support, what needs to be escaped, and what the unescaped JSON sequences give to the filter parsing function.

**Comment by goldmerc** [comment]
@Kerollmops thanks for the update!

**Comment by irevoire** [comment]
Hey @goldmerc thanks for your report!
You're right, we failed you with this update sorry, we went too fast with this PR and didn't even realize that it was a breaking change 🙈 

We took the decision to:
1. Create a new patch release v1.3.6, that reverts this change back to its old behavior because people should never see their code break after a patch release. Sorry again for that 😖 
2. We’ll still include the fix for the v1.4 that should come out next week. Which means you'll need to be cautious when updating:
  * Now you must escape your `\` twice, once to be able to send them in a json string + once to be able to send them in a filter string. 
  * Your example would basically goes from `"\"App\\Model\\Test\" = Foo"` to `"\"App\\\\Model\\\\Test\" = Foo"`

**Comment by goldmerc** [comment]
Thanks for your help! Regarding the change in 1.4, I used curl as an example but my code is in PHP. So, I guess the 1.4 version of meilisearch-php will handle that change automatically?

**Comment by irevoire** [comment]
Hey, from what I understand, the SDK send your arguments as-is to meilisearch, thus you'll need to handle that yourself sorry 😬

**Comment by curquiza** [comment]
Fixed by #4069 
Will be released soon in v1.3.5

**Comment by goldmerc** [comment]
@irevoire - so, will the whole json payload need to be double escaped? Or just filters? What about facets?

**Comment by irevoire** [comment]
Just the filters, not the settings or anything else
