### ISSUE TITLE
There seems to be a problem with matching Chinese

### ISSUE THREAD

**Issue by qin-liang-dev** [meilisearch/meilisearch#4075]
In Chinese,"景点"and"经典"are two different words, but the pinyin is the same, so they are matched

![example](https://github.com/meilisearch/meilisearch/assets/64460070/7591aae3-cbc6-4fd8-9c39-cc89b7aa1b81)

use version:  1.3.4

Is my use wrong? or Not correct config.   i need your help , be deeply grateful

**Comment by qin-liang-dev** [comment]
i an sorry, I can't describe it clearly. "pinyin"  means  pronunciation.

**Comment by dianso** [comment]
指望白人懂分词，搞笑啊

**Comment by qin-liang-dev** [comment]
@dianso  兄弟你用过meilisearch嘛? 这种问题也太离谱了吧,星星都快40k了, 我感觉是我什么地方没设置对啊, 但是文档我也基本翻遍了, 没什么设置

**Comment by qin-liang-dev** [comment]
I found another issues, [issues 3655](https://github.com/meilisearch/meilisearch/issues/3655). In a Chinese language environment, this is a very serious problem and means that it is completely unusable.

**Comment by dianso** [comment]
> @dianso 兄弟你用过meilisearch嘛? 这种问题也太离谱了吧,星星都快40k了, 我感觉是我什么地方没设置对啊, 但是文档我也基本翻遍了, 没什么设置

我一直在用啊，就存在这个问题，联系过开发分词的，不理睬。

**Comment by qin-liang-dev** [comment]
@dianso 你是在生产环境中使用吗？，“景点”和“经典”是两个意思完全不同的词，而且汉语里面大部分同音词都是含义完全不同的，用户不会感到迷惑吗？我看到issues 3655，meilisearch的开发者说会修复

**Comment by dianso** [comment]
> @dianso 你是在生产环境中使用吗？，“景点”和“经典”是两个意思完全不同的词，而且汉语里面大部分同音词都是含义完全不同的，用户不会感到迷惑吗？我看到issues 3655，meilisearch的开发者说会修复

meili的中文分词用的是github.com/messense/jieba-rs

jingdian=景点和经典

**Comment by MustangZhong** [comment]
@curquiza  @qin-liang-dev  so this issue is fixed or not?

**Comment by qin-liang-dev** [comment]
@MustangZhong  至少我用的时候没有解决, 现在不知道

**Comment by ManyTheFish** [comment]
Hello @MustangZhong @qin-liang-dev and @dianso,
Please follow #3655 to know if the issue is solved,
honestly, I don't have any other quick fix than deactivating Pinyin normalization, but If you have anything else to suggest to enhance your experience with Meilisearch, don't hesitate to comment on #3655 or the official [Language support discussion](https://github.com/orgs/meilisearch/discussions/503).

Closed in favor of:
- #3655
- https://github.com/orgs/meilisearch/discussions/503
