### ISSUE TITLE
Database size huge after importing dump from another instance

### ISSUE THREAD

**Issue by cavnit** [meilisearch/MeiliSearch#4114]
**Describe the bug**
Importing a dump from another instance has increased the on disk database size from 54GB to 388GB

**To Reproduce**
1. Dump database on meilisearch
2. Delete data directory
3. Import dump
4. Database is no 6 times bigger

**Expected behavior**
Database should stay roughly the same size

**Screenshots**
Index on old server
<img width="678" alt="Index on old server" src="https://github.com/meilisearch/meilisearch/assets/19301182/d73a90e1-7dab-4198-b420-e03606d01e9a">

Index on new server

[e.g. architecture, device, OS, browser]
<img width="738" alt="Index on new Server" src="https://github.com/meilisearch/meilisearch/assets/19301182/3690a192-3124-4607-8d45-85dea6027fc7">

**Meilisearch version:**
1.4.0

**Additional context**

**OS Version**
Ubuntu Linux 22.04

**Comment by curquiza** [comment]
Hello @cavnit 

Are you migrating from a version to v1.4.0? Or just from one server to another?
In which version were you originally from?

I made some tests on v1.4.0 (not coming from other v1.X) and I get exactly the same size of data.ms

Is it possible to provide the datasets or part of it to reproduce the bug?

**Comment by curquiza** [comment]
Thank you @cavnit for your answer.

@meilisearch/engine-team do you have an idea about what could happen here?

**Comment by irevoire** [comment]
I don't, the dump is simply re-indexing the documents, so that's really strange 🤔 

@cavnit if you can't share your dump, could you maybe try to start a new empty instance and re-index all your documents at once and see the size of the database?

Also, could you share with us the size of everything in your `data.ms`?
You can run `tree -h data.ms` if you have the `tree` command.
What is the `data.mdb` you shared? 

Could you share your logs as well?
