### ISSUE TITLE
Meilisearch takes a lot of time to accept a file

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/meilisearch#4127]
Once a file has been sent to Meilisearch, it spends a lot of time accepting it, registering it in the queue, and returning the task ID. For example, sending a 26GiB file takes a minute and a half to upload, but Meilisearch takes 8 minutes to process it and return a task ID. Note that the file is a JSON Lines file, and the internal document updates files are ~also JSON Lines files~ OBKV Grenad files where the `FieldsIdsMap` is put at the end of the grenad file.

<img width="1031" alt="Capture d’écran 2023-10-16 à 11 33 20" src="https://github.com/meilisearch/meilisearch/assets/3610253/3aaa9ade-850d-409a-b5b0-f38d5a1c1571">
<img width="1029" alt="Capture d’écran 2023-10-16 à 11 41 53" src="https://github.com/meilisearch/meilisearch/assets/3610253/866f202f-7ea5-4eff-9213-cd5ad99d77a8">

https://github.com/meilisearch/meilisearch/blob/0913373a5e7e4c5df6f054e076891bffb0799c7c/milli/src/documents/builder.rs#L60-L81

**Comment by irevoire** [comment]
Hey, do you have an idea in mind?

Have you profiled what takes time? Personally, I think that writing the full file twice (once as jsonlines + once as obkv) is a terrible idea, and we should re-do the PR that @loiclec did a long time ago: https://github.com/meilisearch/milli/pull/576

Iirc, the performance wasn’t good, it wasn’t bad either; it basically didn’t change anything for a big codebase change.
But at the time, we didn’t measure how much time it took to register a task (plus, we rewrote this part entirely with the index-scheduler refactor).

The other thing I think we should do is compress the updated files on the fly; that should greatly reduce the number of IO operations we do + help a lot to reduce the disk consumption due to the unprocessed tasks.

**Comment by Kerollmops** [comment]
After investigating and measuring the time it takes without deserializing the objects of the NDJSON 26GiB file it was taking 6 minutes. So, Meilisearch is doing a pretty good job at handling 26GiB of JSON and storing them in the tasks queue.
