### ISSUE TITLE
When a Chinese document is indexed, a seemly Chinese query misses apparent Japanese documents.

### ISSUE THREAD

**Issue by lilydjwg** [meilisearch/meilisearch#4146]
**Describe the bug**
See title.

**To Reproduce**
1. `curl -X POST -H 'Content-Type: application/json' --data-binary '{"t": "関西国際空港限定トートバッグ", "id": 1}' http://127.0.0.1:7700/indexes/b/documents`
2. `curl -X POST -H 'Content-Type: application/json' http://127.0.0.1:7700/indexes/b/search --data-binary '{"q": "国際"}'`
3. `curl -X POST -H 'Content-Type: application/json' --data-binary '{"t": "关西国际机场", "id": 2}' http://127.0.0.1:7700/indexes/b/documents`
4. repeat step 2. Only document 2 is returned.

**Expected behavior**
Both documents are returned in step 4.

**Meilisearch version:**
1.4.0

**Additional context**
Arch Linux x86_64.

I haven't test more thoroughly, but if I'm not mistaken, this means:
* in a Chinese index, anyone who manages to insert some Japanese hiragana or katakana in a document will hide that document in Chinese queries.
* in a Japanese index, if by chance a document contains no hiragana or katakana but only kanji, all kanji queries will miss documents containing hiragana or katakana.

**Comment by ManyTheFish** [comment]
Hello @lilydjwg,
Unfortunately, Meilisearch cannot support Chinese and Japanese documents in the same index in the current versions due to the Language detection conflict on Kanjis. I highly suggest you separate your Japanese and Chinese documents into two different indexes and use [the multi-index search](https://www.meilisearch.com/docs/reference/api/multi_search) to fetch them.
If you can't separate your documents, I suggest using the [specialized Japanese docker image](https://github.com/meilisearch/meilisearch/pull/3882). This image will consider every text as Japanese, reducing the Chinese search relevancy, but the results will be more consistent for any search request.

Don't hesitate to ask more questions if you need them. Thank you for your report!

**Comment by ManyTheFish** [comment]
I close this issue because we didn't get any answer,
don't hesitate to reopen it if you need help,
see you :)
