### ISSUE TITLE
It is not necessary to reorder attributes at search time

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#429]
Allowing the user to reorder attributes at search time is a CPU consuming and unnecessary feature.

**Comment by bidoubiwa** [comment]
The re-ordering is gone, but it was only a perk of the `searchableAttribute` route, the main purpose being the possibility to choose which attribute to search in. 
Since `searchableAttribute` has been removed, does that mean the possibility to search for matches in a specific field is gone too? Or was it also an unnecessary feature ?
@qdequele @Kerollmops

**Comment by bidoubiwa** [comment]
Documentation : meilisearch/documentation#109
