### ISSUE TITLE
Updating Meilisearch breaks the service

### ISSUE THREAD

**Issue by binarweb** [meilisearch/meilisearch#4321]
**Describe the bug**
Every time I'm updating Meilisearch, something breaks. At this point, I'm afraid of updating it altogether.  
This time, the service stopped working after updating it from 1.3.x to 1.5.1.  
While the sysop jobs is to fix things, having a minor update in semantic versioning should never break things!  
If you guys do not use semantic versioning, please do. It will make the life of a lot of guys easier.
Btw, Meilisearch was installed via APT.  

**To Reproduce**
-

**Expected behavior**
A working Meilisearch update.

**Screenshots**
-

**Meilisearch version:**
1.5.1

**Additional context**

```
Error: Your database version (1.3.5) is incompatible with your current engine version (1.5.1).
To migrate data between Meilisearch versions, please follow our guide on https://www.meilisearch.com/docs/learn/update_and_migration/updating.
```

**Comment by curquiza** [comment]
Hello @binarweb 

As the error message indicates, to upgrade your Meilisearch version, you have to follow the steps in this guide: https://www.meilisearch.com/docs/learn/update_and_migration/updating#updating-a-local-or-deployed-meilisearch-instance

Indeed, Meilisearch behaves like a database and needs a dump to process big updates like you try to do. Your database version (v1.3.1) is not the same version as the engine running (v1.5.1). Using a dump will solve this.

I'm closing this issue since the problem has been identify 😊
