### ISSUE TITLE
.NET SDK CI is failing since v1.7.1

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch#4525]
Since we release v1.7.1, the .NET SDK CI is failing.

https://github.com/meilisearch/meilisearch/actions/runs/8378570359/job/22943427563

But did not fail with v1.7.0

https://github.com/meilisearch/meilisearch/actions/runs/8378435323/job/22942984013

I checked, it's not a random failure.

One of the failing tests is: https://github.com/meilisearch/meilisearch-dotnet/blob/b9b1ecbc62985b2d079bb5c0637fccd5d1c02539/tests/Meilisearch.Tests/SearchTests.cs#L462

**Comment by curquiza** [comment]
@Kerollmops since you made the change in v1.7.1

**Comment by sanders41** [comment]
This seems like a case sensitivity issue. All keys in the [json file](https://github.com/meilisearch/meilisearch-dotnet/blob/b9b1ecbc62985b2d079bb5c0637fccd5d1c02539/tests/Meilisearch.Tests/Datasets/movies_with_info.json) are pascal case, while the test uses camel case.

I tested this theory in Python. Matching the dotnet test returns document 10 first.

```py
import json

from meilisearch_python_sdk import Client


def main() -> int:
    with open("data.json") as f:  # data.json is the json from the dotnet test
        data = json.load(f)

    client = Client("http://127.0.0.1:7700", "masterKey")
    index = client.create_index("movies", primary_key="Id")
    task = index.update_searchable_attributes(["name", "info.comment"])
    client.wait_for_task(task.task_uid)
    task = index.update_sortable_attributes(["info.reviewNb"])
    client.wait_for_task(task.task_uid)
    task = index.add_documents(data)
    client.wait_for_task(task.task_uid)
    movies = index.search("", sort=["info.reviewNb:desc"])
    print(movies)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
```

Changing the case to match the json file returns 11 first (the expected value)

```py
import json

from meilisearch_python_sdk import Client


def main() -> int:
    with open("data.json") as f:
        data = json.load(f)

    client = Client("http://127.0.0.1:7700", "masterKey")
    index = client.create_index("movies", primary_key="Id")
    task = index.update_searchable_attributes(["name", "Info.Comment"])
    client.wait_for_task(task.task_uid)
    task = index.update_sortable_attributes(["Info.ReviewNb"])
    client.wait_for_task(task.task_uid)
    task = index.add_documents(data)
    client.wait_for_task(task.task_uid)
    movies = index.search("", sort=["Info.ReviewNb:desc"])
    print(movies)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
```

**Comment by curquiza** [comment]
Thank you @sanders41 

I'm not sure I understand WHY this changed between v1.7.0 and v1.7.1. I want us to be sure we are aware of this change on the engine side. .NET SDK did not change anything, only the engine changed. So I want to understand why we now return "Gladiator" instead of "Interstellar" in this test.

<img width="1029" alt="Capture d’écran 2024-03-22 à 17 04 59" src="https://github.com/meilisearch/meilisearch/assets/20380692/ae4937e3-8ee5-4b5f-b830-ce53b469898f">

So I'm not sure I understand why it's related to camelcase issue.

**Comment by sanders41** [comment]
Interestingly I checked out the `v1.7.0`, then all the way back to 4b644f6 and it was always consistent. "Gladiator" was always returned for me first unless I matched the case in the json.

**Comment by dureuill** [comment]
Hello, 

yes, Meilisearch is case-sensitive for fields, so **unless** the C# code is changing the casing before sending the requests over the wire, the field that is set as sortable does not actually exist in the DB.

We're then sorting by a non-existing field, which is the same as a placeholder search. The order of documents in a placeholder search is not guaranteed to be consistent between Meilisearch versions.

**Comment by dureuill** [comment]
I investigated further, and there's definitely a Meilisearch v1.7.1 related bug here.

### 1. The test is correct considering how the .net SDK works

The .net SDK changes the case of fields in some circumstances, so the lowercase fields in the tests are actually consistent with the uppercase fields from the JSON dataset.

<details>
<summary>Behavior of the .net SDK</summary>

1. The SDK deserializes the JSON file as a [`MovieWithInfo` class](https://github.com/meilisearch/meilisearch-dotnet/blob/main/tests/Meilisearch.Tests/Movie.cs#L19), such that the uppercased field match the corresponding upper case property
2. The SDK then serializes again the `MovieWithInfo` class in the call to [`Index.AddDocumentsAsync`](https://github.com/meilisearch/meilisearch-dotnet/blob/main/tests/Meilisearch.Tests/IndexFixture.cs#L115)
3. In doing so, [it transforms the keys so that their first letter is lowercase](https://github.com/meilisearch/meilisearch-dotnet/blob/main/src/Meilisearch/Extensions/ObjectExtensions.cs#L23). We even have [an issue](https://github.com/meilisearch/meilisearch-dotnet/issues/515) open about this behavior
4. In the end, the keys stored in the Meilisearch instance are lower-cased

</details>

### 2. Meilisearch v1.7.1 does not trigger a reindexing operation when it should with nested fields

Adding the documents with the upper case:

1. Adding the documents with the upper case: `curl http://localhost:7700/indexes/test4/documents -H 'Content-Type: application/json' -d @"/Users/dureuill/dev/meilisearch-dotnet/tests/Meilisearch.Tests/Datasets/movies_with_info.json"`
2. Checking the documents: 
```json
❯ curl http://localhost:7700/indexes/test4/documents
{"results":[{"Id":"10","Name":"Gladiator","Info":{"Comment":"a movie about old times","ReviewNb":700}},{"Id":"11","Name":"Interstellar","Info":{"Comment":"the best movie","ReviewNb":1000}},{"Id":"12","Name":"Star Wars","Info":{"Comment":"a lot of wars in the stars","ReviewNb":900}},{"Id":"13","Name":"Harry Potter","Info":{"Comment":"a movie about a wizard boy","ReviewNb":900}},{"Id":"14","Name":"Iron Man","Info":{"Comment":"a movie about a rich man","ReviewNb":800}},{"Id":"15","Name":"Spider-Man","Info":{"Comment":"the spider bit the boy","ReviewNb":900}},{"Id":"16","Name":"Amélie Poulain","Info":{"Comment":"talks about hapiness","ReviewNb":800}}],"offset":0,"limit":20,"total":7}%
```
3. Making the documents sortable by the Info.ReviewNb:
```
❯ echo '{"sortableAttributes": ["Info.ReviewNb"] }' | mieli settings -i test4
```
4. Attempting to sort the documents by review nb:
```
❯ curl http://localhost:7700/indexes/test4/search -H 'Content-Type: application/json' --data-binary '{"sort": ["Info.ReviewNb:desc"]}'

{"hits":[{"Id":"10","Name":"Gladiator","Info":{"Comment":"a movie about old times","ReviewNb":700}},{"Id":"11","Name":"Interstellar","Info":{"Comment":"the best movie","ReviewNb":1000}},{"Id":"12","Name":"Star Wars","Info":{"Comment":"a lot of wars in the stars","ReviewNb":900}},{"Id":"13","Name":"Harry Potter","Info":{"Comment":"a movie about a wizard boy","ReviewNb":900}},{"Id":"14","Name":"Iron Man","Info":{"Comment":"a movie about a rich man","ReviewNb":800}},{"Id":"15","Name":"Spider-Man","Info":{"Comment":"the spider bit the boy","ReviewNb":900}},{"Id":"16","Name":"Amélie Poulain","Info":{"Comment":"talks about hapiness","ReviewNb":800}}],"query":"","processingTimeMs":0,"limit":20,"offset":0,"estimatedTotalHits":7}%
```

**Comment by curquiza** [comment]
Closed by https://github.com/meilisearch/meilisearch/pull/4539
