### ISSUE TITLE
Ranking rules does not work like documents

### ISSUE THREAD

**Issue by khanhan2k2eliai** [meilisearch/meilisearch#4545]
**Describe the bug**
Try to custom ranking rules but it does not work as expect, just first rule is working. For example:
My ranking Rules: 
[
 "sort",
  "words",
  "typo",
  "proximity",
  "attribute",
  "exactness"
]
My Results are ranked by sort only. others do not work. I try to sort by created_at first and then sort the semantic score.
I attached my data test below.
[data-test.json](https://github.com/meilisearch/meilisearch/files/14810836/data-test.json)

**Comment by dureuill** [comment]
Hello, with a quick look to your data it looks to me like no two documents are having the same `created_at` value.

If that is correct, there is nothing that remains to be ranked by the words ranking rule after the sort ranking rule has been applied, and the behavior is expected.

What behavior were you expecting to see vs. which behavior are you seeing. That is, for a given query, what is the order of documents you're seeing, and what is the order of documents you were expecting to see?

Having sort as the first ranking rule is reserved to niche use cases, because usually you want relevancy ranking rules applied first.

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
