### ISSUE TITLE
Find total result count to enable pagination

### ISSUE THREAD

**Issue by traverseda** [meilisearch/MeiliSearch#461]
I'm working on a search application for "internet in a box", and meilisearch looks like the right choice.

I'd like to enable progressive web apps, the search-as-you-type functionality is great, but we also need to support working without javascript.

In order to properly paginate results we need a rough idea of how many results there actually are. It would also be nice to be able to display that information to the user.

**Comment by qdequele** [comment]
Hey @traverseda ! Thank you for your interest in our project! 

You wish to have in the answer the number of results that could potentially match a query. Like when google display to the user « About 618,000,000 results (0.91 seconds)  »?

**Comment by traverseda** [comment]
Yep. That's it exactly.

**Comment by John-Theo** [comment]
Awesome project! I'm so excited when discovered MeiliSearch!
I'm also looking forward to this feature that allows me to find out (approximately) how many hits match the query.

Also, maybe the current `search` functionality can be **separated into two parts**:
1. Get suggestions, "match peeks", and results count **on the fly** (like the current `search` web GUI),
2. Get detailed hits (like the current `search` API, but **no need to be instant**)

By "match peeks", I mean for example I have a very long field like "full-text", I only need to know the context of the hits rather than the complete value of the field (which is the raw full-text).

Maybe you will consider this?

**Comment by Kerollmops** [comment]
Hey @John-Theo,

We are currently working on exposing an approximate number of matching documents for a query, it is a fix to another comment https://github.com/meilisearch/MeiliSearch/issues/469#issuecomment-601723145, the PR will be open for review today and will probably be available in v0.9.1 in a week.

If I understand the feature request (1.) correclty, there already is [a feature named `attributesToCrop`](https://docs.meilisearch.com/guides/advanced_guides/search_parameters.html#attributes-to-crop) that makes the engine returns a snippet of a field content exposing the first matching position.

I am not sure I understand your feature request (2.) correctly. Do you want the engine to return the exact number of documents that match a query? If so, a temporary solution would be to ask the engine every page of result and count the number of hits.

**Comment by John-Theo** [comment]
@Kerollmops  Thanks for the reply!

I did not notice the `attributesToCrop` attribute, my apologies!

With that feature already implemented and #541 merged, the rest of my request is search suggestions, which may be the same as #525 .
I will waiting for the new feature there as nothing relevant to this issue remains.
