### ISSUE TITLE
Pagination issue when using Semantic Search

### ISSUE THREAD

**Issue by runabol** [meilisearch/meilisearch#4704]
**Describe the bug**
The pagination results behavior changes when I use semantic search. Specifically, it seems to get offsets `0-10` when I specify `offset: 5`, `limit: 5`.

**To Reproduce**

In the first two `curl` commands I turn off semantic search and get the expected results. 

In the following ones I turn it on and get the unexpected behavior.

```
# curl -s -X POST -H "content-type:application/json" -d '{"q":"car","offset":0,"limit":5,"hybrid":{"embedder":"default","semanticRatio":0}}'  'http://localhost:7700/indexes/books/search'  | jq '.hits[].id'
"658c8e3c8e2163f80f97a743"
"658c8e1e8e2163f80f97a2e8"
"658c8fc1372f01b94b520b8e"
"658c8d938e2163f80f978ffe"
"658c8df48e2163f80f979c02"


# curl -s -X POST -H "content-type:application/json" -d '{"q":"car","offset":5,"limit":5,"hybrid":{"embedder":"default","semanticRatio":0}}' 'http://localhost:7700/indexes/books/search'  | jq '.hits[].id'
"658c8ec3372f01b94b51ea56"
"658c8dd58e2163f80f979a1a"
"658c913a372f01b94b523bc7"
"658c9153372f01b94b523f2d"
"658c9205372f01b94b525476"

# curl -s -X POST -H "content-type:application/json" -d '{"q":"car","offset":0,"limit":5,"hybrid":{"embedder":"default","semanticRatio":0.5}}'  'http://localhost:7700/indexes/books/search'  | jq '.hits[].id'
"658c8e3c8e2163f80f97a743"
"658c8e1e8e2163f80f97a2e8"
"658c8fc1372f01b94b520b8e"
"658c8d938e2163f80f978ffe"
"658c8df48e2163f80f979c02"

# curl -s -X POST -H "content-type:application/json" -d '{"q":"car","offset":5,"limit":5,"hybrid":{"embedder":"default","semanticRatio":0.5}}'  'http://localhost:7700/indexes/books/search'  | jq '.hits[].id'
"658c8e3c8e2163f80f97a743"
"658c8e1e8e2163f80f97a2e8"
"658c8fc1372f01b94b520b8e"
"658c8d938e2163f80f978ffe"
"658c8df48e2163f80f979c02"
"658c8ec3372f01b94b51ea56"
"658c8dd58e2163f80f979a1a"
"658c913a372f01b94b523bc7"
"658c9153372f01b94b523f2d"
"658c9205372f01b94b525476"
```

**Expected behavior**
To only get offset 5-10 when specifying `offset: 5`, `limit: 5`.

**Meilisearch version:**
v1.8.0

**Comment by dureuill** [comment]
hello @runabol :wave:

The effect you are seeing is caused by the search algorithm of the semantic search. The semantic search uses an Approximate Nearest-Neighbor (ANN) search algorithm to find the `limit+offset` vectors that are the "closest" to the query vector.
Because the algorithm is approximate, increasing `limit+offset` might result in "closer" vectors being found, which means that the order of results is not guaranteed to remain stable for two distinct values of `limit+offset`.
As it is a design characteristic of ANN algorithms, and exact algorithms (kNN) don't scale with the number and size of vectors, this behavior is unlikely to be fixed.
As a workaround, you can set `offset` to 0, set a large value for `limit`, and then apply the pagination manually in frontend.
In the future, we might consider some mitigation to this behavior, where we would always, for example, consider the first few hundred results (as if `limit+offset` would be equal to, say 1000) regardless of the actual value of `limit+offset`. There's a correctness/performance tradeoff to measure here, though.

Thank you for the report :heart:

**Comment by runabol** [comment]
Fair enough. Was able to work around this. Thanks!

**Comment by dureuill** [comment]
hello, what do you mean by fine ranking, can you elaborate?

**Comment by bilinxing** [comment]
Fine sorting is relatively coarse sorting. Coarse sorting refers to recalling a batch of data through keywords or vector similarity, such as 10,000 records. Then, among these 10,000 records, we can do secondary sorting according to specific business attribute weights, and only take 1000 records. In this way, we can do personalized search, recommendation search based on popularity, and other higher-level search functions. I also think it can solve the problem of duplicate data in pagination.

**Comment by bilinxing** [comment]
Sorry, I expressed was not clear. It should be reranking. Then I found two alternative products: [weaviate](https://weaviate.io/developers/weaviate/search/rerank) and [milvus](https://milvus.io/docs/reranking.md)

**Comment by dureuill** [comment]
sounds like this would break pagination though?
