### ISSUE TITLE
Error while generating embeddings: user error: attempt to embed the following text in a configuration where embeddings must be user provided

### ISSUE THREAD

**Issue by alimoezzi** [meilisearch/meilisearch#4729]
I have index with a default embedder setup as the following:
```
  embedders: {
    default: {
      source: 'openAi',
      model: 'text-embedding-3-small',
      apiKey: process.env.OPENAI_API_KEY,
documentTemplate: '{{doc.content}}'
    },
},
```

  Now I want to add a new user-provided embedder:

  ```
  embedders: {
    default: {
      source: 'openAi',
      model: 'text-embedding-3-small',
      apiKey: process.env.OPENAI_API_KEY,
documentTemplate: '{{doc.content}}'
    },
      large: {
      source:  'userProvided',
      dimensions: 1024,
    },
}
```

  But I'm getting error when I update the setting to add the new embedder
  

 ```
  "error": {
        "message": "Error while generating embeddings: user error: attempt to embed the following text in a configuration where embeddings must be user provided: \" id: ceadfadfasdddsvcdsc7-4b002c3ec493\\n 
        }
 ```

  It looks like it's not possible to add new embedders when the index already has content.
  
  Tested on both v1.7.1 and v1.8.3.

**Comment by dureuill** [comment]
Hello :wave:

> It looks like it's not possible to add new embedders when the index already has content.

Yes, it is possible, in particular it should always work if you add a new openai, ollama or rest embedder.
The embeddings for the new embedder will be generated for all documents of the index while performing the settings update.

For `userProvided` embedders, it is possible also, but a bit harder, since a `userProvided` embedder cannot generate the embeddings for documents on its own.

As a result, you must specify the embeddings for that embedder in each document **before** adding the `userProvided` embedder in the settings. 
This is done by having a `_vectors` field in each of your documents, which has to be an object with one key named after your `userProvided` embedder.
That key must itself be an array of numbers describing the embedding for that document and embedder, or an  array of arrays of numbers describing multiple embeddings for that document and embedder.
It is possible to opt-out of embeddings for an embedder and document, by setting the key corresponding to that embedder to `null` in `_vectors` (or, an empty array in the upcoming v1.9).

So, in your case, you would need to do the following:

1. Update all your documents to add a `_vectors` object with the following shape:
```jsonc
"_vectors": {
  "large": [0.1, 0.2, ... 1024 numbers in total..., 0.5]
}
```
2. Add the embedder as described in your post:
```jsonc
embedders: {
  default: {
    source: 'openAi',
    model: 'text-embedding-3-small',
    apiKey: process.env.OPENAI_API_KEY,
documentTemplate: '{{doc.content}}'
  },
    large: {
    source:  'userProvided',
    dimensions: 1024,
  },
}
```

**Comment by alimoezzi** [comment]
Well, this takes huge amounts of time to manually add this field to 100k documents in the Index. It would have been much better if the default value was none for user provided embedding. Then I could gradually add the embedding to the documents as needed.

**Comment by dureuill** [comment]
The risk we wanted to avoid was users accidentally not having embeddings for some documents for a `userProvided` embedder.

The feature is still experimental so there is a possibility to revert that default now.

We wouldn't have *any* backchannel to tell users that some documents don't have embeddings, however.

**Comment by alimoezzi** [comment]
In this case, as a user I can get to know by retrieving stats regarding items with embedding. This can further be improved by adding a generate or default value in the embedders settings as the following:
```
embedders: {
  default: {
    source: 'openAi',
    model: 'text-embedding-3-small',
    apiKey: process.env.OPENAI_API_KEY,
documentTemplate: '{{doc.content}}'
  },
    large: {
    source:  'userProvided',
    dimensions: 1024,
  -> generate: false
  },
}
```

Or 

```
embedders: {
  default: {
    source: 'openAi',
    model: 'text-embedding-3-small',
    apiKey: process.env.OPENAI_API_KEY,
documentTemplate: '{{doc.content}}'
  },
    large: {
    source:  'userProvided',
    dimensions: 1024,
   default: null
  },
}
```

**Comment by alimoezzi** [comment]
@dmilith so I far I did retrieve vectors by including _vector in the attribute to check if vectors are generated.

**Comment by dureuill** [comment]
I'm not sure what the semantic of `generate` would be in your example above?

What's the behavior when `generate` is `true`? when it is `false`?

**Comment by alimoezzi** [comment]
False will skip `Error while generating embeddings: user error: attempt to embed the following text in a configuration where embeddings must be user provided` when an items is missing this embedding.

**Comment by alimoezzi** [comment]
I'm not sure semantically `default` key is better or similar keyword to `generate`.

**Comment by dureuill** [comment]
OK, so that's a bit like a `strict` mode.

I'm not certain if this is worth adding at the price of extending an already super large API surface (taking into account all kinds of embedders), but it might be worth it to flip the behavior in all cases.

What makes me hesitate is that the behavior already helped user detect that their way of adding vectors was wrong (putting `vectors` or `_vector`  instead of `_vectors`)

**Comment by alimoezzi** [comment]
This behaviour is not helping in any case as already both individual vectors and stats can be inspected.

Strict mode is also vey helpful in migration. As the index grows, the solution to manually adding is going to make changes to meilisearch cumbersome to impossible.

**Comment by alimoezzi** [comment]
You can also keep this error message as warnings in task logs rather than error. @dureuill

**Comment by dureuill** [comment]
that's an idea, but we're not putting warnings in the task queue currently, and I'm not sure that it is the best location to do so.

**Comment by alimoezzi** [comment]
Task queue logs or in stdout. I saw warnings in console already.

**Comment by curquiza** [comment]
Discussed with @dureuill, it can be closed
Feel free to ask to re-open if needed
