### ISSUE TITLE
Show default ranking rules if user reset them

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#476]
For the moment, when updating the settings of the `rankingRules` to `null` it means that the ranking rules will have its default value.

This should be changed, null shouln'd be accepted, instead if you want `rankingRules` to be reset to its default value you should omit the field in the `POST settings` route.

**Comment by qdequele** [comment]
To clarify this issue: 

1. Default ranking rules
**Before:**
If not `rankingRules` is set, the settings JSON will respond `rankingRules: null`
**After:**
If not `rankingRules` is set, the settings JSON will respond default ranking rules array`rankingRules: ["_typo", "_words", "_proximity", "_attribute", "_words_position", "_exact"]`

2. What happens if the user set `rankingRules: null`
The default rules will be used. This way to delete `rankingRules` should not be documented.
To be sure to have no ranking rules the user must set `rankingRules: []`.

3. How to delete ranking rules
`DELETE /indexes/:index_id/settings/rankingRules`
