### ISSUE TITLE
Meilisearch: Self-hosted cloud deployment network connection stalling

### ISSUE THREAD

**Issue by JoshuaLarouche** [meilisearch/meilisearch#4792]
I'm trying to work with self-hosted Meilisearch deployed on Openshift but it seems to be searching very slowly. I plan to increase the available resources but I don't think that is the main issue as each search network request seems to be stalling and waiting for the previous one to finish. I can't imagine this is how it is supposed to be working but has anyone who has worked with Meilisearch before have any ideas about what might be going on? All of the grey bars in the screenshot below are times it is showing stalled under the connection start section of the timing information. When I run the apps locally it search fine without stalling so I think it might be a network policy issue or something along those lines

I tried increasing the resources and running it locally
<img width="1470" alt="Screenshot 2024-07-05 at 9 32 15 AM" src="https://github.com/meilisearch/meilisearch/assets/161653341/70cee05d-3c1a-496a-86bc-3b0cf6917269">

**Comment by irevoire** [comment]
Hello @JoshuaLarouche,

Meilisearch can run search in parallel only when the number of threads of your machines allows it.
It limit itself to one search per thread, so I guess what you're seeing is the result of a machine with a single thread right?

This is generally not an issue because searches run so fast in Meilisearch, but from what I see some of your searches are taking around 5s am I right?
Could you share the `processingTimeMs` of a search request that took a long time?
Also I see that you're returning very large results, 478KiB over a slow network can take a lot of time to process, maybe before upgrading the spec of your server you could try to reduce the size of the payloads returned by Meilisearch?
The [`attributesToRetrieve`](https://www.meilisearch.com/docs/reference/api/search#attributes-to-retrieve) can help you to select only the required parameters.
If you're using the [`attributesToHighlight`](https://www.meilisearch.com/docs/reference/api/search#attributes-to-highlight) already, you might not need the `attributesToRetrieve` at all and set it to `{ "attributesToRetrieve": [] }` to only select the highlighted elements.

For further help, please share one of your requests and the answer from Meilisearch + the time it took you to receive the answer on your side.

**Comment by curquiza** [comment]
I close this issue due to a lack of answers. Nothing is definitive of course, feel free to ask to re-open if needed 😊
