### ISSUE TITLE
Compatibility with NFS

### ISSUE THREAD

**Issue by dimiro1** [meilisearch/MeiliSearch#481]
Hello,

Do you have any experience deploying it on an NFS filesystem? I am interested in running it on AWS ElasticBeanstalk [1] with an attched EFS [2] disk.

[1] https://aws.amazon.com/elasticbeanstalk/
[2] https://aws.amazon.com/efs/

**Comment by Kerollmops** [comment]
Hello @dimiro1,

I do not have any experience in deploying it on any network based file system. MeiliSearch is backed by the LMDB key-value store, you should check if LMDB supports NFS.

IIRC LMDB is not greatly designed for NFS because the commit operation (when you validate the write of a transaction, and [the durability of it](https://en.wikipedia.org/wiki/ACID#Durability)) it must check that the flush returns which can be slow on network based file systems.

**Comment by stevemk14ebr** [comment]
Do not run LMDB on any EBS based disk. It will be very slow, especially as the DB grows and the OS swaps pages back and forth between RAM and DISK. Use an i3 ec2 instance with an NVMe drive, or run on metal.
