### ISSUE TITLE
Get unexpected search result when using Chinese

### ISSUE THREAD

**Issue by wwbweibo** [meilisearch/meilisearch#4814]
**Describe the bug**
Get unexpected search result when using Chinese, some result are missing.

**To Reproduce**
1. make sure the index contains these data 
```text
code:SP2405050080 id:182013 name:芹菜 name_pinyin:qincai name_pinyin_abbr:qc tenant:128
code:SP24042800MH id:138087 name:毛芹 name_pinyin:maoqin name_pinyin_abbr:mq tenant:128
code:SP240720000D id:754926 name:山芹 name_pinyin:shanqin name_pinyin_abbr:sq tenant:128
code:SP24042800O6 id:138149 name:大芹菜 name_pinyin:daqincai name_pinyin_abbr:dqc tenant:128
code:SP24050500NP id:182579 name:水芹菜 name_pinyin:shuiqincai name_pinyin_abbr:sqc tenant:128
code:SP2405070016 id:183291 name:毛芹菜 name_pinyin:maoqincai name_pinyin_abbr:mqc tenant:128
code:SP240709009Q id:748777 name:大芹菜根细的 name_pinyin:daqincaigenxide name_pinyin_abbr:dqcgxd tenant:128
code:SP24042800O4 id:138147 name:精品毛芹 name_pinyin:jingpinmaoqin name_pinyin_abbr:jpmq tenant:128
code:SP240618007Z id:732892 name:二毛芹 name_pinyin:ermaoqin name_pinyin_abbr:emq tenant:128
code:SP240623001L id:737175 name:二粗毛芹 name_pinyin:ercumaoqin name_pinyin_abbr:ecmq tenant:128
code:SP240720000V id:754944 name:带根毛芹 name_pinyin:daigenmaoqin name_pinyin_abbr:dgmq tenant:128
code:SP24050500O9 id:182599 name:马家沟芹菜 name_pinyin:majiagouqincai name_pinyin_abbr:mjgqc tenant:128
```
2. using code below to search in index 
```golang
	args := &meilisearch.SearchRequest{
		Filter: []string{fmt.Sprintf("tenant = %d", 128)},
		Limit: 1000,
	}
	meilisearchClient := meilisearch.NewClient(meilisearch.ClientConfig{
		Host:   HOST,
		APIKey: MASTERKEY,
	})
	searchResponse, err := meilisearchClient.Index("sku").Search("毛芹", args)
	if err != nil {
		t.Error(err)
	}
	for _, item := range searchResponse.Hits {
		fmt.Println(item)
	}
```
3. checkout the printed search result
4. the result only contains these record
```text
map[code:SP24042800MH id:138087 name:毛芹 name_pinyin:maoqin name_pinyin_abbr:mq tenant:128]
map[code:SP2405070016 id:183291 name:毛芹菜 name_pinyin:maoqincai name_pinyin_abbr:mqc tenant:128]
map[code:SP24042800O4 id:138147 name:精品毛芹 name_pinyin:jingpinmaoqin name_pinyin_abbr:jpmq tenant:128]
map[code:SP240618007Z id:732892 name:二毛芹 name_pinyin:ermaoqin name_pinyin_abbr:emq tenant:128]
map[code:SP24042800OF id:138158 name:毛白菜 name_pinyin:maobaicai name_pinyin_abbr:mbc tenant:128]
map[code:SP240511009V id:189083 name:毛豆芽 name_pinyin:maodouya name_pinyin_abbr:mdy tenant:128]
map[code:SP24071200DT id:750446 name:毛青 name_pinyin:maoqing name_pinyin_abbr:mq tenant:128]
```

**Expected behavior**
The search result should contains records `毛芹菜`,`毛芹`, `精品毛芹`, `二毛芹`, `二粗毛芹`, `带根毛芹`

**Screenshots**
![image](https://github.com/user-attachments/assets/9e750a36-de69-415b-8758-080d9dc24fac)

**Meilisearch version:**
1.9.0

**Additional context**
Additional information that may be relevant to the issue.
I tried to change the matching strategy, but has no difference. Also tried to add `"` to the query，still cannot get  `二粗毛芹`, `带根毛芹`,`毛芹菜`

**Comment by ManyTheFish** [comment]
Hello @wwbweibo,
If I understand your issue, you can't retrieve a document containing `二粗毛芹` or `带根毛芹` with the query `毛芹`.
After some investigations, it's due to the tokenization, `二粗毛芹` and `带根毛芹` are tokenized as:
- `二 | 粗毛 | 芹`
- `带 | 根毛 | 芹`

Putting `毛` at the end of a word, and because Meilisearch does not support suffix matches, the document wouldn't match by default.

However, we can tweak Meilisearch to enhance the relevance.

### [Using the `dictionary` index setting](https://www.meilisearch.com/docs/reference/api/settings#dictionary)

you may want to always consider `毛芹` as a word in your context. In this case, I suggest adding it to the `dictionary` index setting:
PATCH `/index/sku/settings`

```json
{
  "dictionary": ["毛芹"]
}
```

This would force Meilisearch to tokenize "毛芹" as one token/word transforming `二 | 粗毛 | 芹` and `带 | 根毛 | 芹` into `二 | 粗 | 毛芹` and `带 | 根 | 毛芹`.

### [Using the `frequency` matching strategy](https://www.meilisearch.com/docs/reference/api/search#frequency)

The default search `matchingStrategy` is `last` but you may prefer using the `frequency` one for your search queries.


let me know if one of this suggestions solved your issue,

see you! 👋

**Comment by wwbweibo** [comment]
@ManyTheFish Thanks for your suggestion, I tried the two solutions you mentioned. Using dictionary setting solved this problem. However, after setting `毛芹`  into dictionary, The query using `芹` wont return the records contains `毛芹`. I understand this is the desired output, but it can make our user much more confusing. So I was wondering is the any way to make meilisearh tokenize every single Chinese character, eg: tokenize  `二粗毛芹` into `二｜粗｜毛｜ 芹`

**Comment by ManyTheFish** [comment]
Hello @wwbweibo, sorry if it didn't work for you.
The only solution you have is to use the `dictionary` setting by putting all the most common Chinese characters in order to force Meilisearch to split over each of them.
But this will deactivate the typo tolerance because all the words will contain only one character. If you want to change that, I suggest modifying the [typo tolerance](https://www.meilisearch.com/docs/learn/relevancy/typo_tolerance_settings), either.
 
see you! 👋

**Comment by wwbweibo** [comment]
@ManyTheFish  Thanks, it seems to work fine by adding the high frequency Chinese character into dictionary. Close this issue.
