### ISSUE TITLE
Include offset for cropped fields

### ISSUE THREAD

**Issue by solonovamax** [meilisearch/meilisearch#4863]
*I spent like 20 minutes writing an issue and then my browser tab decided to crash and killed all my progress, and I'm kinda annoyed about that so I'm just gonna be brief here and add more details later.*

Currently, when both `showMatchesPosition` and `attributesToCrop` are in use, it is difficult to use the matches position as you do not know where the crop begins.

I would like to propose adding `[field]_start` and `[field]_length` properties to the returned json when searching. For example, searching for `minim` might return this result:
```json5
{
  "id": 1,
  "title": "Lorem Ipsum",
  "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  "_formatted": {
    "id": 1,
    "title": "Lorem Ipsum",
    "content": "…Ut enim ad minim veniam…",
    "content_start": 124,
    "content_length": 25, // note: the length here includes the added crop marker ('…')
  },
  "_matchesPosition": {
    "content": [
      {
        "start": 135,
        "length": 5
      }
    ]
  }
}
```

then, this can be used as follows (in pseudocode)
```kt
result = /* ... */

val content = result["_formatted"]["content"]
val contentOffset = result["_formatted"]["content_start"]

val match = result["_matchesPosition"]["content"][0]
val matchOffset = match["start"] - contentOffset
val matchLength = match["length"]

// use the computed match and the content for highlighting
```

my specific usecase: I want to add match highlighting to search results for my application. However, I cannot use the built-in highlighting as that would wrap html tags around the matches, as the content is user-supplied. So if I didn't escape the html, it would open up an avenue to XSS. But since it's escaped, wrapping the matches with html tags does not work.
And, I can't use the offset provided in the match positions, as I do not know where the content was cropped, so I don't know where the match is.

**Comment by solonovamax** [comment]
An alternative syntax to the one I suggested could be:
```json5
{
  "id": 1,
  "title": "Lorem Ipsum",
  "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  "_formatted": {
    "id": 1,
    "title": "Lorem Ipsum",
    "content": "…Ut enim ad minim veniam…"
  },
  "_crops": {
    "content": { // the name of the field the content was cropped from
      "start": 124,
      "length": 25
    }
  }
  "_matchesPosition": {
    "content": [
      {
        "start": 135,
        "length": 5
      }
    ]
  }
}
```

**Comment by curquiza** [comment]
Hello @solonovamax 

Thanks for using Meilisearch

We don't handle feature request in this repository

<img width="1305" alt="Capture d’écran 2024-08-02 à 16 56 40" src="https://github.com/user-attachments/assets/c275a17e-3cb6-40d3-a324-40b5bf5f2fe5">


I usually ask for people to start a discussion about it on the [product repo](https://github.com/meilisearch/product/discussions/), but since you have a bad experience with browser and your issue is already detailed, I will try to move it to the appropriate place. GitHub is not 100% working when it's about converting issues to discussions + move them... I will do my best

Have a nice day

**Comment by solonovamax** [comment]
I could copy it over if you'd like

but the reason I opted for an issue over the discussions tab was bc this is an extremely small feature and I do somewhat consider it a "bug" that the provided offsets are unusable with the cropped content

**Comment by curquiza** [comment]
Yes both visions are ok 😊 but since you have to add new fields, it's not a matter of bug anymore and the product needs to be involved.

We will discuss it with the team 😊

I did it the transfer manually because I don't trust GitHub, I close this issue and I reopen this [one](https://github.com/orgs/meilisearch/discussions/769)
