### ISSUE TITLE
`multi-search` with federation not returning facets 

### ISSUE THREAD

**Issue by hcbaxiom** [meilisearch/meilisearch#4913]
I am using `multi-search` endpoint and having issue with getting facets when I use `federation` to combine the results. 

**To Reproduce**
1. Create a colleciton with filterableAttributes as usual
2. Try search with `multi-search` endpoint with `facets` in queries and use `federation` to get a combined result set for the queries
3. It does not return facets info in the response
4. Now, if we remove the `federation` key from request, it will return `facets` data in every query response object 

**Expected behavior**
It should be returning facets data combined together from both/all of the queries

**Meilisearch version:**
[e.g. v1.10.1]

**Comment by mbraeuner** [comment]
I tested on v1.10.0 & v1.10.1. There is no facetDistribution, facetStats in response if using federation {}

**Comment by dureuill** [comment]
Hello,

Thank you for your report. [Federated search does not currently support facet distribution](https://meilisearch.notion.site/v1-10-federated-search-698dfe36ab6b4668b044f735fb40f0b2#f65bb55da1184caa8c77fbdb8eb2ac59).

If you want it added, I encourage you to [open a product discussion](https://github.com/meilisearch/product/discussions/categories/feedback-feature-proposal) about it, stating your use case and what you would like to see.

In particular, I'm not convinced that the intuitive API where we would collect the `facets` from the individual queries would work: 

1. What should we do if two queries from the same index use different facets?
2. In particular, what about the special case of two queries in the same index, one with a list of facets, the other without?
3. Should we merge the similarly named facets that appear in queries from *different* indexes in the results?

These are design work, which is why the work was punted for v1.10.

For now, I lean towards:

1. Disallowing the declaration of `facets` at the query level for federated search, similar to how `limit` and `offset` are only allowed at the top-level. Unfortunately, this is a breaking change in a stable feature 😬, so I need to check how much leeway I can get from @meilisearch/product-team. Worst case, `facets` at the query level will not do anything, as in v1.10
2. Adding a top-level `facetsByIndex` object, whose keys will be the index names, and values the list of facets that will be looked for in queries for that index.
3. I'm really undecided on what to do regarding the merging of facets from different indexes. On the one hand, I guess most people want to merge, on the other, when you don't want to merge it is very hard to "undo" the merge, whereas merging the facets from different indexes is easy. Maybe this should be configurable 🤔 

In v1.10, as a workaround, you can do a both a federated and non-federated multi-search requests, and then manually merge the facets from the non-federated multi-search request.

**Comment by dureuill** [comment]
Will be fixed by #4929.

**Comment by dureuill** [comment]
Hey @mbraeuner  and @hcbaxiom, since you requested the feature, may I ask if the current design would suit your use cases?

Some important points:

1. Passing `facets` directly in query still do nothing, or is even upgraded to a hard error.
2. Facets need to be passed for each index in the top-level `federation` object.
3. By default, facets are merged only for queries on the same index. They are returned index by index in the response. This is to accommodate a use case where users would not want to merge similarly named facets for different types of documents and would like to, for example, display the facets under each type of document.
4. There is a `federation.mergeFacets` object to enable the merging of facets across all indexes and control its behavior.

[Find the full design here](https://meilisearch.notion.site/v1-11-Federated-search-59b30e03383c40729d7541a3dffb0069)

Thank you for any reply :pray:

**Comment by mbraeuner** [comment]
@dureuill 
yes, your design is fine. It will cover my use case. My current case asks for results of the same index with variations of the search query.

**Comment by macraig** [comment]
Hey @hcbaxiom @mbraeuner  👋 

[v1.11](https://github.com/meilisearch/meilisearch/releases/tag/v1.11.0) 🐿️ has been released and federated search now supports facets 🎉
