### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [meilisearch/meilisearch#4923]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Meilisearch application as shown [here](https://elest.io/open-source/meilisearch). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

**Comment by ManyTheFish** [comment]
Hello @kaiwalyakoparkar,
our README is no more the place for the external deployment,
there is now a [specific section in our documentation for that](https://www.meilisearch.com/docs/guides/deployment/running_production), I encourage you to move your issue and contribution on the documentation repository,

See you!

**Comment by guimachiavelli** [comment]
Hello @kaiwalyakoparkar! I'm @guimachiavelli, the documentation maintainer 👋 

Due to our limited resources, we generally do not accept content targeting third-party tools unless we have received clear feedback from the community they need dedicated content for it. At the moment, that's not the case for Elestio, so I'm afraid we'll have to refuse your offer for the moment.

**Comment by curquiza** [comment]
I think an answer has been given here

Closing
