### ISSUE TITLE
[BUG] error while decoding: unknown cookie value

### ISSUE THREAD

**Issue by thePanz** [meilisearch/meilisearch#5155]
**Describe the bug**
The request to `GET /tasks` started to return `HTTP-500` error message, with an internal error.
The reported error text, in the returned JSON was: `error while decoding: unknown cookie value`.

Checking the logs of the container, it was full of messages like:
```
2024-12-11T03:45:07.577097Z ERROR index_scheduler: error while decoding: unknown cookie value
```

**To Reproduce**
The error appeared out of the sudden, with no actions from our side.

**Expected behavior**
Meilisearch should not break and flood the logs every 2ms :shrug: 
Furthermore: the log message is quite out-of-context, as no cookies are used in the API requests

**Meilisearch version:**
[e.g. v1.10.3]

**Additional context**
The Meilisearch container is stored on Azure cloud.

**Comment by Kerollmops** [comment]
Hello @thePanz 👋

It is likely a database corruption. We have [this kind of issue with Azure](https://github.com/meilisearch/meilisearch/issues/4402) and only Azure, so it's probably more of an Azure problem.

The only solution that Meilisearch can develop in the future could be to detect this kind of corruption and return a better error message instead of reading the content without noticing. By using another, unreleased version of LMDB [we could checksum the pages](https://github.com/LMDB/lmdb/blob/63091b38e46cb64c954feb510307b325ed7bbd25/libraries/liblmdb/lmdb.h#L1045-L1053) to return better error messages. However, the problem will remain the same: being unable to use Meilisearch. The other option could be to detect corruptions and rollback to the latest committed transaction, a.k.a. batch task.

We recommend using another provider or cleaning and reindexing your dataset from scratch.

Have a nice end of the week 🦃

**Comment by thePanz** [comment]
Thanks @Kerollmops , sadly I am aware of the linked issue #4402 , the confusion was about the weird message mentioning cookies.

Unfortunately we are "forced" to stay on Azure :disappointed: and will look for alternatives way to handle this issue

**Comment by irevoire** [comment]
>  Would be great if Meilisearch can report a more precise error, and not something misleading as the "unknown cookie value".

Hey, as kero said above, we have ideas on ways to do that with a specific LMDB version, but it's not that easy when you're running on a filesystem that corrupts itself for no reason while you're doing something else :grimacing: 
It's hard to differentiate an internal error where we believe something should be here and we don't find it (an issue in our algorithm) from a corruption, where we wrote something and Azure decided to lie and not register the change :confounded: 

> Unfortunately we are "forced" to stay on Azure 😞 and will look for alternatives way to handle this issue

We chatted a bit with an engineer at Azure, and I think the conclusion was that the only way to get a real disk was to create an ephemeral VM and attach a real disk to it.

Anyway, you may be interested by this discussion where you'll find all the investigations we've already done: https://github.com/meilisearch/documentation/issues/2622
