### ISSUE TITLE
How to backup all documents

### ISSUE THREAD

**Issue by jet10000** [meilisearch/MeiliSearch#532]
Assuming there are 10TB documents, how to quick backup it?

```
Get documents
/indexes/:uid/documents
```

**Comment by Kerollmops** [comment]
Hey,

There is a route that can help you do that. The [get documents route](https://docs.meilisearch.com/references/documents.html#get-documents), you can call it in a loop until it respond with an empty list.

Be careful, this route is not atomic, it means that subsequent calls to this route can return more or less documents that there is in the database, this is because an update can have been processed been two calls, therefore removing or hading documents.
