### ISSUE TITLE
Disk space is not freed when an index is deleted

### ISSUE THREAD

**Issue by taziden** [meilisearch/MeiliSearch#547]
Hi,
It seems like disk space is still occupied after an index has been deleted.
Steps to reproduce:

- create an index
- update this index using the movies dataset
- data.ms dir takes ~118Mo
- delete the index
- data.ms dir size is unchanged

Thanks for this great project btw ;)

**Comment by Kerollmops** [comment]
Hey @taziden,

I know this issue exists, MeiliSearch uses the LMDB key-value store internally, the disk usage is entirely manage by that. LMDB doesn't shrink when it grows, this way it keep performance by keeping the pick usage it reached over time, that is part of its design and Symas have made [an article to explain that behavior](https://symas.com/understanding-lmdb-database-file-sizes-and-memory-utilization/).

However, it is a long time since I think about moving to another key-value store [derived from LMDB named mdbx](https://github.com/erthink/libmdbx), it have many improvements over LMDB and supports [automatic continuous zero-overhead database compactification](https://github.com/erthink/libmdbx#added-features) which means that it reduces disk usage over time if it can.

Thank you for your issue and your kind wordsm have a nice day!

**Comment by taziden** [comment]
Thanks a lot for the elaborate answer!
You're free to close the issue as my question has been perfectly answered.
