### ISSUE TITLE
Query parameter to return only _formatted object

### ISSUE THREAD

**Issue by andersju** [meilisearch/MeiliSearch#549]
I'm indexing a lot of large text documents. Each can easily be 500-800 KB of text, which I put in a field called full_text. When searching I specify `attributesToCrop=full_text&cropLength=50` and get the result I want in the _formatted object. However, for each hit, I also get the entire full_text back, which is wasteful; 10 hits can result in 5 MB of JSON, whereas it would've been ~40 KB or so without the whole full_text. I can't use `attributesToRetrieve`, because I *do* want the full_text field -- but only the cropped version.

So, it would be great to have the option "just give me the _formatted object and not the non-formatted".

**Comment by Kerollmops** [comment]
Hey @andersju,

That is an interresting usage, this can definitely be improved in our side, I am wondering if it could be a good behavior to only return the `_formatted` fields when the `attributesToCrop` has been defined... Or do we need to add a new parameter in the query?

This will be fixed in the future release I believe which will be out in probably a week or so.
If you need to have that feature early I will comment this pull request and you will be able to compile MeiliSearch yourself.

**Comment by andersju** [comment]
@Kerollmops: Hmm. Not sure what the best behavior would be. Either way works for me, but perhaps only returning `_formatted` if `attributesToCrop` has been defined could surprise some people? I can see people wanting both (e.g. to initially display cropped value but have the ability to expand and see the full value).

No rush, I added a dirty workaround in the meantime. Thanks for the quick reply and thanks for your work!

**Comment by securisec** [comment]
@Kerollmops I came across this ask also. I am having the same issue as the OP where the returned responses contains both the `_formatted` object along with a large amount of data. I looked through the docs, but could not figure out what to set to return only the `_formatted` results and not the whole body. Using version 0.23.1

Any suggestions on how to get only the `_formatted` hits?

**Comment by curquiza** [comment]
Hello @securisec 

The last version is v0.28.1, I'm not sure what I will explain will work with v0.23.1.
You can set up only the attributes you want to hilhight and crop in `attributesToHighliht` and `attributesToCrop`, and only the attributes you want to retrieve (cropped/highlighted or not) in `atttributesToRetrieve`. Avoid using `*` if you have a lot of data
More info about the search parameters: https://docs.meilisearch.com/reference/api/search.html#search-parameters

Thanks for using Meilisearch 😄

**Comment by securisec** [comment]
Thank you for the response @curquiza . Here is a screenshot that explains the issue I am having. I updated to 0.28.1 before attempting.

In the screenshot, you can see that I am interested in the `data` attribute. But in the response, I get back both `data` and `_formatted.data`. Now imagine data was much larger then this small text. Say it was 500kb. It would send back a ton of data to the client making the request. So in this case, I am using `attributesToRetrieve` and specifying the values, but what I would like to get back in the response is only the `_formatted`, instead of the whole data and `_formatted`. 

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/22226823/189659373-622cc5aa-e982-45dc-871c-233d14c47ae7.png">

**Comment by yewyewXD** [comment]
In my case, only `data` is searchable. I have a bunch of other fields in the response (id, title, etc.), but they are all also repeated in `_formatted`, making the response x2 larger.

With the solution above, my response has only `_formatted` -> `data` , but I want other fields too. My final solution was this, and now everything is fitted in `_formatted`, hooray!

```
{
      attributesToHighlight: ["*"],
      attributesToRetrieve: [],
}
```
