### ISSUE TITLE
jemalloc - failed to execute command: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by plluksie** [meilisearch/MeiliSearch#562]
Hello,
 thanks for this very interesting project. I encountered an issue trying to compile it on Ubuntu 18.04.4 LTS. Would you be able to point me to the right direction please?

Thank you.

[typescript.log](https://github.com/meilisearch/MeiliSearch/files/4397857/typescript.log)

**Comment by Kerollmops** [comment]
Hey @plluksie,

Thank you for your kind words, as I read the logs it seems like you need to install `make` to be able to compile MeiliSearch. You will also need to install `gcc` I think.

**Comment by plluksie** [comment]
Hey @Kerollmops 
Sorry for the noise. I forgot that I've rebuilt that machine and haven't installed dev tools:
apt-get install build-essential

Embarassing 🤦

Thanks again!

**Comment by Kerollmops** [comment]
Hey @plluksie,

Why are you building MeiliSearch from source? Is it because you are unable to run the available binaries on your machine? Or is it because you want to have the most recent features/fixes that are only available on master?

I am asking this because I want most people to be able to run the engine with the least work possible. By, for example, just downloading the binary corresponding to their platform.

**Comment by vstath** [comment]
For me the least work possible is to be able to compile clean and install myself if needed. Additionally, your apt repository only supports Ubuntu 18.04 and not 16.04 which is my test box.

Having said that, I'm unable to compile from source on 16.04 with the snapd rust and rustup. 

As you probably realize, I'm not a rust user but willing to learn ;-) 

Hope it helps answer your question (many people prefer to compile from source / test / play with things / learn etc).

**Comment by Kerollmops** [comment]
Hey @vstath, thanks, that's an helpful answer.

If you want to compile MeiliSearch from source you must have the latest `rustc` compiler, which is currently `rustc 1.42.0 stable`.
