### ISSUE TITLE
Support string equality in arrays

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/MeiliSearch#611]
The current filter engine supports case insensitive string equality but not case insensitive string equality inside of arrays (array of string). This is one particular feature that I though would be immediately available with the new filter syntax.

This feature as been highlighted by someone on crisp (visitor34965):
> How would I implement tags filtering with this?

If we support this we can make the engine way more expressive than currently, we can support tag filtering when documents can have multiple tags.

I would also like to see a "common usage" section in the filtering documentation page, to explain the usage you can do of string matching another string or string matching inside of an array of string, this way people searching for "filtering tags" or anything similar can find this.

About the potential performance issue: if the documents have big arrays and no strings in any documents contains the filtered tag this is bad. This will be kind of solved when we will introduce facetting, any attribute that is composed of a string or an array of strings can be used as a facetted field and the complexity will be drastically reduced to a simple pre-search intersection on ids.

```JSON
[
  { "id": 1, "colors": ["red", "green", "blue"] },
  { "id": 2, "colors": ["red"] },
  { "id": 2, "colors": "green" }
]
```

```SQL
colors = "red" # matches 1 and 2
colors = "green" # matches 2 and 3
colors = "red" OR colors = "green" # matches 1, 2, and 3
```

**Comment by MarinPostma** [comment]
@Kerollmops  A few questions:
- Should the empty string always match an array ?
```
colors = "" # matches 1, 2, and 3
```
- How do we match an empty array ?
we could make it the only one that does not match the empty string:
```
[
  { "id": 1, "colors": [] },
  { "id": 2, "colors": ["red"] },
  { "id": 2, "colors": "green" }
]

colors != "" # matches 1
```

However that would be weird, because the empty string matches only documents that have an empty value for that field...

On a broader subject, I realised that documents that don't have a value for a specific field are discarded. The question arises as how to handle them? Is an empty value the same thing as an unexisting field? I think not, but again this is debatable.

On a semantic level, the empty string is the only way we have to tell that we expect an empty value. 
```
// this can't be a valid syntax
color = OR color = green
```
And the fact that we allow unquoted word a a value prevents us from adding a `null` keyword (which I'm against anyway).

Now we could have the following
```
// matches all the documents that do not have a field `color`
NOT color
// matches all the documents that have a field `color`
color
```

but that implies a consequent change in the syntax.

**Comment by Kerollmops** [comment]
I think we will not provide this feature today, we will keep updating #615 when people needs that.

```SQL
colors = "" # only matches empty strings or empty strings inside of an array
```
