### ISSUE TITLE
Index creation

### ISSUE THREAD

**Issue by mjl4043** [meilisearch/MeiliSearch#667]
When i run the create index request after running the search the following message appears.
I am using Ubuntu.
command: curl -i -X POST 'http://127.0.0.1:7700/indexes' --data '{ "name": "Movies", "uid": "movies" }'

HTTP/1.1 400 Bad Request
content-length: 0
date: Sat, 09 May 2020 20:44:25 GMT

**Comment by MarinPostma** [comment]
Are you trying to re- create the same index?

**Comment by mjl4043** [comment]
Yes the one given

**Comment by mjl4043** [comment]
Not re-creating, making it for the first time only.

**Comment by qdequele** [comment]
Same error as #653. Don't forget to add the Header to say that you're sending json body.
curl -i -X POST 'http://127.0.0.1:7700/indexes' -H "Content-Type: application/json" --data '{ "name": "Movies", "uid": "movies" }'

It won't be a problem anymore, in the next release. It will be fixed with #661 and more specifically https://github.com/meilisearch/MeiliSearch/pull/661/commits/bc2e95df2bf6fa0291221d9684746844b78bf1cd.

**Comment by mjl4043** [comment]
Thank you, that helped.

But further i am not able to upload the documents on that index-

curl -i -X POST 'http://localhost:7700/indexes/movies/documents' \
> -H "Content-Type: application/json" \
> --data-binary @movies.json
HTTP/1.1 100 Continue

HTTP/1.1 404 Not Found
content-length: 36
content-type: application/json

**Comment by qdequele** [comment]
Could you try with `--data` or `-d` instead of `--data-binary`?

**Comment by mjl4043** [comment]
Sorry. I had some typo error in index creation uid.
