### ISSUE TITLE
Report queries for which no documents are found

### ISSUE THREAD

**Issue by tpayet** [meilisearch/MeiliSearch#765]
**Frustration**
Finding no results is always frustrating, if the user search for something and MeiliSearch returns no document there must be a problem somewhere.
It could either come from a poor explanation of what your search is about or come from a poor configuration of settings or synonyms.

> **Note:** I know that for enormous dataset, this would not work because MeiliSearch would always find some documents but in smaller dataset this definitely is a way to improve your search experience either by providing documents, or improving settings or synonyms. 

**Solution**
MeiliSearch should report in some ways search query that returned no result. Should it be something stored that you can get anytime using the API?

**Alternative**
An alternative could be to have something watching the MeiliSearch logs and (supposing we are answering 404 on no results queries) we can send event somewhere or write in amplitude or a tool like this which was the term that MeiliSearch did not find documetns about. 

*This came from a discussion I had with Ori at Platform.sh about their usage of MeiliSearch*

**Comment by qdequele** [comment]
If the user doesn't get a result it is often because he has written several words and it is absolutely necessary that all the words are present in the document to be a candidate. If we allow a document to be a candidate even if it does not have all the words then this will be fixed. 

On the other hand, if there is no result because no words are present then it seems normal not to answer any results. On the other hand, as Algolia does, it can be good to store this information somewhere to show the user the top of the search words that have no results.

**Comment by qdequele** [comment]
This issue will not be considered in the engine; it will probably be a part of a future dashboard. I close this issue and note it on the future dashboard roadmap.
