### ISSUE TITLE
Issue with bulk asynchronous document additions (with facet attributes)

### ISSUE THREAD

**Issue by mikerogerz** [meilisearch/MeiliSearch#784]
**Describe the bug**
I've been busy implementing a restricted access system (to limit search results per user) using the new facets feature that was recently added. Great new addition by the way, thanks for all the hard work.

The concept is based on:
[https://www.algolia.com/doc/guides/security/api-keys/how-to/user-restricted-access-to-data](url)

The documents indexed are made up of individual paragraphs/lines of long-form reports (from 1000 to 40,000 documents generated per report depending on the length), with arrays of user ids attached to facet search/filter on.

When running document additions in batches (via your PHP library, with each POST including all paragraphs of an individual report), after about 50,000 documents or so being indexed, something happens where facet searches will no longer return results. Normal query search still works fine. Even once it finishes indexing the ~180,000 documents, searches using facets still don't return results.

In the end, the fix was to increase the http payload size limit to 1GB and add all the documents in one POST.

If you need more details, please let me know.

**Expected behavior**
Expecting concurrent asynchronous document additions to work the same as adding all documents in one go.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

Meilisearch version 0.11.0.

**Comment by mikerogerz** [comment]
An update:
This seems to be related to the primaryKey (length?). I was using a unique string identifier similar to:
product-original-125-0
product-original-125-1
...
product-original-125-40000

This would result in lost documents in the results (where the nbHits count would be accurate, but the documents would be missing in the hits). I changed the identifier to a sha1 string generated from the identifier and the results came back correctly (with facet filters).

Is there something obvious here? Some sort of limitation of the primaryKey with facets?

**Comment by mikerogerz** [comment]
Update:
If the attribute for faceting is created (or queued) AFTER adding all the documents, searching via facet filtering works correctly. The issue is specific to updating the attribute for faceting before documents are added.

And additional information related to the initial issue, the documents are missing in the hits array, but the nbHits count returns correctly.

**Comment by MarinPostma** [comment]
This is related to #776
@Kerollmops @curquiza

**Comment by MarinPostma** [comment]
@mikerogerz we're trying to make this better, your input on the matter would be appreciated 😊

**Comment by mikerogerz** [comment]
@MarinPostma I'm not sure I understand the relation to #776 

The known/indexed fields (faceted attribute in this case) of previously added documents is being lost when new batches of documents are added. I don't see anything about that in the other issue.

**Comment by MarinPostma** [comment]
@mikerogerz Yes, I apologize this is not clear at all. When adding documents to meilisearch, the engine will go through each documents attributes and, if it doesn't know about them, it will add them to it's internal schema, and to the list of searchable and displayed attributes in the settings by default. Now what happens when you add a mention to a new field in the settings is that this new field is added to the schema and to the schema only (therefore not to the searchable attributes and displayed attributes). 

If you add documents that contains an attribute `foo` for example, then foo is added to the schema, displayed attributes and searchable attributes, and when you add it to attributes for faceting, the engine already know about that attribute, so it works.

The other way around, you add the field `foo` to the attributes for faceting, so the engine add it to it's schema, but when indexing documents, it already knows about it and doesn't add it to the searchable and displayed attributes.

So if you can to add attributes for faceting prior to indexing documents (which I advise to prevent reindexing), you must add the attributes you want to do faceting on in the displayed and searchable attributes too.

This is kind of a status quo, and we're not super happy with this right now, but the reason it's this way for the moment is that we have no way to know if the user meant not to add a new attribute to other categories when he first declare it in a setting. It makes little sense for `attributesForFaceting`, but a lot more for other settings, and we want to have consistent behavior with settings.

Sorry for the long read, I hope I made things clear :) we're open to suggestions

**Comment by mikerogerz** [comment]
Thanks for the explanation @MarinPostma 

I understand the issue, but I think this might be something else. I tested adding the faceted attribute to both the searchable and displayed attributes, with setting the faceted attribute before adding all the documents.. and the same issue occurred. I get the nbHits count, but no hits, if trying to filter by facets.

The only way faceting seems to work is with setting the faceted attribute after adding all the documents, which is definitely not preferred since yes it requires re-indexing everything (and maxing out my server's memory).

Regarding #776, I think that the separate "known fields" route might be the best solution if all settings behave differently in terms of affecting what's indexed, displayed, and searchable. There probably needs to be one place to configure that, vs. needing to understand & explain how each setting can possibly affect others.

**Comment by MarinPostma** [comment]
Hey @mikerogerz, I made a PR ,that may fix your problem, can you give it a try? #789

**Comment by mikerogerz** [comment]
@MarinPostma Just tested, and works great.

As a side note, it also works without needing to add the faceted attribute to both the searchable and displayed attributes.

Much appreciated.
