### ISSUE TITLE
Remove /sys-info routes

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/MeiliSearch#808]
As discussed with @Kerollmops , there are issues with this route, that often return garbage values. the added value of this route is a very low since there are many tools that are much better suited for this job. It appears that this route require more maintenance than we anticipated, and for these reasons 

I suggest that we remove it.

**Comment by eskombro** [comment]
> there are many tools that are much better suited for this job

I mainly use this route for knowing how many documents I have in an index, and the fields distribution sometimes (rarely). Is there a better way to know this?

**Comment by MarinPostma** [comment]
oops @eskombro  wrong route, I have edited the title

**Comment by curquiza** [comment]
I personally don't use this route at all despite I use MS every day, so I'm ok to remove it, but that's just my personal experience with MS 🙂

**Comment by eskombro** [comment]
>oops @eskombro wrong route, I have edited the title

Ok, that changes a few things :)

Indeed, we don't really use it a lot because we all have access to the machine where we deploy our MeiliSearch. But if you just have an API access, you can't have any information on the system.

Just need to decide if we don't need to expose that to a user. But it certainly shouldn't be the focus of MeiliSearch (and the core team) to provide stats on sys-info, and there are a lot of other tools indeed, so I mainly agree with you!

**Comment by MarinPostma** [comment]
I see 2 cases here:
- Meilisearch is run in the cloud: there are tons of tools provided by cloud providers that give instance metrics way bettter than we do
- meilisearch is run on premise: ssh and htop will give you much better results

**Comment by MarinPostma** [comment]
@qdequele WDYT?

**Comment by qdequele** [comment]
At the begining, this sys-info was needed due to our needs. We no longer have this kind of needs so, we can remove this route.
