### ISSUE TITLE
Search returns 400 Bad Request for queries with umlauts

### ISSUE THREAD

**Issue by rluba** [meilisearch/MeiliSearch#831]
**Describe the bug**
Issuing a search query with a German umlaut (eg. äöü) causes a `400 Bad Request` response. I don’t think this can be attributed to needing a new tokenzier (#624).

**To Reproduce**
``` 
curl -i '<meilisearch_host>/indexes/<any-index>/search?q=Gewähr'
``` 

It *does* work when encoding the umlaut:
```
curl -i '<meilisearch_host>/indexes/<any-index>/search?q=Gew%C3%A4hr'
```
… but that shouldn’t be necessary.

**Expected behavior**
Return results just like for any other search.

**Additional context**
Tested with meilisearch 0.11.0 using the official docker container (`getmeili/meilisearch`).

**Comment by Kerollmops** [comment]
Hey @rluba,

This issue is not directly related to the core engine of MeiliSearch, it is related to the HTTP server. Every query parameter must always be [percent encoded](https://fr.wikipedia.org/wiki/Percent-encoding), this is a requirement for any HTTP request, if not correctly percent encoded, a request cannot be handled by the HTTP server.

You should probably use one of our SDK, they already handle these behaviors.

Thank you for reporting this 😃
