### ISSUE TITLE
Backup Meilisearch DataBase triggering an HTTP route

### ISSUE THREAD

**Issue by LegendreM** [meilisearch/MeiliSearch#840]
# Summary
Linked to #561,
be able to create a backup of meilisearch database triggering an HTTP route
# Motivations
Backups, unlike snapshots, are not a representation at a time t of the database. They are a transformation into a simpler format of the database that necessarily requires reindexing to be loaded. This has the advantage of not being impacted by internal system updates.
# Explanation

## How to know when the backup is finished?

we create an update transaction that will resolve in the future. If there already exist a pending update for a backup, an error is returned to the user. 
error_code: "backup_already_in_progress"

## How do we know where to put the backup?

An environment variable specifies the backup folder.

## How do we trigger a backup?

a post route `/backup` with private authentication creates a backup in the specified folder

## how do we launch meili with a backup?

launch with argument `--backup <path>`, to reindex everything

# Documentation

## setup backup destination
`BACKUP_PATH`: Path in Env to specify backup destination

## trigger backup process
query (POST): `/backups`
responses:
- 202 (backup process launched):
```json
{
  "uid": "2sjwb2a3",
  "status": "processing"
}
```
- 409 (a backup is already in process)
```json
{
  "message": "Another backup is allready in process, please try again later",
  "errorCode": "backup_already_in_process",
  "errorType": "invalid_request_error",
  "errorLink": "https://docs.meilisearch.com/errors#backup_already_in_process"
}
```

At the end of the process backup will be stored in `$BACKUP_PATH/archives/`

## get backup process status
query (GET):  /backups/:backup_id:/status
responses:
- 200:
```json
{
  "uid": "2sjwb2a3",
  "status": "processing"|"done"|"backup_process_failed"
}
```
- 404

## instantiate meilisearch with a backup

launch with argument `--backup <path>`

# Implementation
## setup backup destination
add in the config struct a `backup_path` attribute which will be used for backups

## trigger backup process
implement a POST route (`/backup`) which will:
1) check an atomic boolean `backup_in_process` to know if a backup is in process
2) create a `backup_id` uid
3) create a backup status `In progress`  with `backup_id` in DB (optional but clearer)
4) instantiate a thread with `backup_id` which will create backup

## get backup process status
1) check the `backup_in_process` boolean and backup status
## instantiate meiliSearch with a backup
add in the config struct a `backup` cmd which will import backup in MeiliSearch  at the start of the program

# Related
- [ ] Test added
- [ ] [Documentation](https://github.com/meilisearch/documentation/pull/468)

**Comment by curquiza** [comment]
Hello!

Can you add the `meilisearch-http` label on it? 🙂

Thanks for the detailed issue.

About the routes and HTTP code errors, I would rather use:

`POST /backup`
- **202** (Accepted): backup_id (backup process launched) instead of 200
- **409** (Conflict): (a backup is already in process) instead of 400

`GET /backup/:backup_id`
- 102 (Processing) -> ok
- **200** (Ok) instead of 201: for me, 201 is used when you call a route (often `POST`) and this call **results** to a new resource creation, not to say "yes, your resource has been created". If you re-call this same GET route, no new resource will be created.
- 400 (Error) -> ok
- 404 (Not Found) -> ok

Based on this resource: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

I supposed that none of these routes will return a response JSON body since there is a detailed HTTP code error return (Proccessing/OK/Error)? I'm not against this idea, I'm just asking to be sure 🙂

**Comment by LegendreM** [comment]
Hello @curquiza, 

## status codes changes
I agree with all status code changes 👍 

## returning a json body
about the thing of returning an error text is better than use an HTTP CODE. 🤔 

so instead of:
```
GET /backup/:backup_id

    102 (Processing)
    200 (Ok) 
    400 (Error) 
    404 (Not Found) 
```

I think we should have a route:
```
GET /backup/status/:backup_id

    200 (Ok) + json body (`Error`, `Processing`, `Done`)
    404 (Not Found) if `backup_id` doesn't exist
```

### why `/backup/:backup_id` -> `/backup/status/:backup_id`?
At the end, when the process is finished, this route will never return a backup.
This route is only made to give the status of the backup processing.

### why remove `400 (Error)` and `102 (Processing)`?
#### about 400 (Error)
Client didn't made an error calling this route, an error occurred during the backup process, and it's not 5XX error because the API didn't fail to return the backup status.

#### about 102 (Processing)
it's not the status that need more time to be returned as an HTTP response, we should better return a status (200) that say ~ `backup in process` 

what do think?

thanks for your feedbacks!

**Comment by curquiza** [comment]
@LegendreM, I completely agree with your suggestions about:
- renaming the GET route into `backup/status/:backup_id`
- removing 400 and 102, for the reasons you explained -> the backup is processing or failing, not the backup status
- returning a JSON body in the response 

Can you give us an example of the JSON body that we will receive as a response? Would it be just a string or a JSON object?

**Comment by curquiza** [comment]
Oh! Sorry not to have noticed it before, but I would suggest `backup/:backup_id/status` instead of `backup/status/:backup_id`. This is more RESTful and more consistent with the other routes of the MeiliSearch API.

**Comment by LegendreM** [comment]
As we discussed with @eskombro we should probably think about:
`be able to download the backup file`.
Usefull for users who doesn't have access to filesystem/mounted-volume/s3...

**Comment by bidoubiwa** [comment]
Instead of having a subroute `/backup/:backup_uid/status/` to get status updates of the process could we not imagine a more global `/updates/:updateId` routes that will be linked to the MeiliSearch instance and not to a specific `index` ?

That way if we want to add more asynchronous processes on the instance later one we will not have to create an additional sub-route just for status updates.

**Comment by bidoubiwa** [comment]
- `--backup <path>`: Start meilisearch with a backup file

I'm suggesting a more specific name `--import-backup <path>`.

**Comment by icyJoseph** [comment]
What ever happened to this feature? 

If I understand correctly, the idea was to have an API that would export all documents to JSON, so that the data could be consumed by any other application, including MeiliSearch itself.

Is it still possible? Or is the recommended way to build a list by sequentially asking for `offset to limit`, and then exporting as JSON?

**Comment by curquiza** [comment]
Hello @icyJoseph this issue is a really old tracking issue for the implementation of our current dump.
Check out our documentation to know how to use them
- Data back up guide: https://docs.meilisearch.com/learn/advanced/snapshots_vs_dumps.html#data-backup-snapshots-vs-dumps
- Dump API reference https://docs.meilisearch.com/reference/api/dump.html
- How to upgrade to the latest version of Meilisearch: https://docs.meilisearch.com/learn/advanced/updating.html#update-to-the-latest-meilisearch-version

**Comment by icyJoseph** [comment]
@curquiza I see, yeah I've used dumps fair and square, and as far as I understand they are written in a format that the search engine understands, but it's not, say, JSON. 

I think with any of the SDK's dumping an entire index to JSON should be kinda trivial, so I'll go with that.

Thanks!
