### ISSUE TITLE
Placeholder search when query is empty does not work

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliSearch#856]
**Describe the bug**
When using the placeholder search you can either:
1. Not give the parameter `q`: In which case the placeholder search works as expected
2. Give an empry parameter `q`: in which case **no documents are returned**

**To Reproduce**
1. Create an index and add documents to it
2. Make a search with an empty query parameter
3. No documents are returned

**Expected behavior**
As it is a placeholder search, I expected it to work with an empty string. I'm not sure this is a bug as it is maybe what you have decided. I could not find a discussion about it on the related tracking issue. 

**Screenshots**

```bash
➜ curl -X GET 'http://localhost:7700/indexes/movies/search?q='  | jq
{
  "hits": [],
  "offset": 0,
  "limit": 20,
  "nbHits": 0,
  "exhaustiveNbHits": false,
  "processingTimeMs": 3,
  "query": ""
}
```

**Tests should be added**
- [ ] empty `q` with expected behavior
```rust
let query = json! ({
        "q": ""
    });
```

**Comment by qdequele** [comment]
For me, it's not an issue but expected behavior. if you are searching nothing it's normal to return nothing. Placeholder search is a search without query parameter not without words in the query.

**Comment by bidoubiwa** [comment]
I have two concerns: 
One, I don't see the use case for an empty string returning nothing.
For me, an empty string is similar to `null` in this situation. As there is nothing written, the placeholder should appear.

Two, for me, it is easier to send search requests based on the input of the user. 
In javascript, when the users writes something and then deletes it, the input value is `""` and not `null`.

```html
<input id="exemple" />
<script>
console.log(document.querySelector("#exemple").value) // ""
</script>
```

Which means that in order to use the placeholder search, the developer will have to do an extra step to change `""` into `null`

```javascript
const inputValue = document.querySelector("#search-input").value
const query = ( inputValue === "") null : inputValue;
index.search(query)
```

Of course, this is how I see it. If most of you think this is the expected behavior its allright for me!

**Comment by qdequele** [comment]
A simple example where an empty query string is totally different than no query. If you take a look at the search implemented on the documentation. If you write something and finally you erase what you write you expect to have no response and no response box. In your case, the user will always have results in the box, and not always desired documents. 

Placeholder is made for tradeoff when you have no response but it is a real feature that allows showing documents with a specific logic before the user starts to search for something. But this behavior is totally optional. You can completely avoid it by always passing a query parameter.

**Comment by MarinPostma** [comment]
> For me, an empty string is similar to null in this situation. As there is nothing written, the placeholder should appear.

Ahh, js people haha ;)

More seriously, as @qdequele correclty pointed out, placeholder may not be desired, and can be expensive resource-wise (when there are filters enable on the query for instance). Therefore this is and should be an opt-in feature :)

**Comment by curquiza** [comment]
Sorry I was on holiday when the issue was opened and then closed, so I didn't notice it, that's my fault 😅 Plus I just realized the problem when starting to use the browse yesterday during my front-end tool implementation.

>  A simple example where an empty query string is totally different than no query. If you take a look at the search implemented on the documentation.

The documentation search, so the dropdown search, is **not** most cases 🙂
See:
- Most e-commerce websites and the future @bidoubiwa's demo
- our finding-*** demos (all of them don't have a browse because they have been implemented a long time ago, but they should have one for better user experience)
- the InstanSearch use cases: Algolia enforces the placeholder search by default, as I do for our [tools with InstantSearch](https://codesandbox.io/s/ms-is-mese9).

> If you write something and finally you erase what you write you expect to have no response and no response box.

Not true in the cases I detailed above 🙂

In the case of the dropdown, you just send no request when there is no input in your HTML input. That's what Algolia does with DocSearch.

Indeed, Algolia chose to use `q=""` for the placeholder search and I understand this choice 🙂

Plus users think this is confused, see for example this comment https://github.com/meilisearch/meilisearch-js/pull/544#issuecomment-671401814. This is not intuitive, the users have to refer to the docs for a feature that should be basic.

I started to implement the browse yesterday for `instant-meilisearch` and, as this user, I think this is not intuitive. I was really kind of confused using MeiliSearch like that (and even before finding out that Algolia took another side).

Finally, by choosing `q=""` instead of `q=null`, you still would have 2 solutions to disable the browse. You can:
- use `q=null`
- send no request when your HTML input is empty (the Algolia solution). That's the front-end solution that is already intuitively used in most of the search, Algolia or not.

=> **With the kind of implementation we've chosen, we assume that most of the user does not want the browse when sending an empty string**. That's the side we took when choosing `q=null` instead of `q=""`. And I personally disagree with that.
From my POV, if the users send a `""` query, they want the browse. Otherwise, they wouldn't even send any request if the HTML input for the search is empty and wouldn't even notice this feature 🙂

## Conclusion

I would like to re-considered this issue since:
- I'm pretty sure the dropdown search is not the main use case and the browse could be needed in most cases.
- If the browse is not needed, most of our users will disable the browse without noticing it since they wouldn't send any request from the front if the HTML input is empty -> the browse could be a feature by default without any trouble.
- I found out that Algolia took the other option, despite performance reasons you give. We don't have to follow Algolia every time, but this time I'm really wondering why
- Our users find this is confusing and leads them to check the documentation for a basic feature
- As MeilISearch users, @bidoubiwa and I think this is confusing.

I don't say we absolutely **have** to change it or we did a bad choice. I just want the core-engine team to be aware of the choice we've made about the browse 😉

**Comment by qdequele** [comment]
The final decision about this request is on the tracking issue #729.

Summary:
A placeholder search is triggered by a search query without query parameter **or** an empty query parameter.

**Comment by bidoubiwa** [comment]
So in the case of juste a white space` `. What happens ?

**Comment by qdequele** [comment]
> So in the case of juste a white space . What happens ?

I think it sould be consider as a normal search query. It means the user intentionally sent a space. We will not trim the query server side and see the lenght of the string.

**Comment by curquiza** [comment]
I'm ok with doing the placeholder search for `q=''` or `q=null` (or no `q` at all) since that was planned at first in [the original tracking issue about the placeholder](https://github.com/meilisearch/MeiliSearch/issues/729) 🙂
