### ISSUE TITLE
Error: Cannot open database, expected MeiliSearch engine version: <0.12.0, currrent engine version: 0.12.0

### ISSUE THREAD

**Issue by anborg** [meilisearch/MeiliSearch#860]
**Question:**
- Which version of dockerimage"getmeili/meilisearch" should I use for db compatibility with github version?

**What i did:** 

1. run meilisearch in localhost with below image in docker compose [**windows**]
2. run a local crawler to index website into meili
3. copy the database to another meili [binary compiled from github ]

```
  meilisearch:
    image: getmeili/meilisearch
    container_name: meilisearch
```
What I expected: 
- Since it is using a db library, I thought coping databse from one meili to another would work.

**Comment by MarinPostma** [comment]
Hello @anborg,  Minor version bulb means breaking changes in the DB représentation or API.This is meant to prevent meilisearch to start with a database that is incompatible. In order to make it work on the newer version, you need to reindex you documents on the new version. We are currently working on a backup system that will make migration easier.

**Comment by anborg** [comment]
Thank you for the information
