### ISSUE TITLE
Meilisearch intermittently becomes incapable of handling new requests after index creation timeout

### ISSUE THREAD

**Issue by Bajix** [meilisearch/meilisearch#880]
**Describe the bug**
I have an initialization service that creates indexes and updates documents. Sometimes this hangs when creating an index after which point all subsequent requests fail.

**To Reproduce**
Create multiple indexes while updating bulk documents

**Expected behavior**
All requests succeed

**Additional context**
Index has ranking rules: 
```
[
      "typo",
      "words",
      "proximity",
      "attribute",
      "wordsPosition",
      "exactness",
      "desc(score)"
]
```

**Comment by roelvanmeer** [comment]
It may or may not be the same problem, but we're seeing the same (intermittent) behavior in our Jenkins CI. We're using the Docker container. I've tried both v0.12.0 and v0.10.1.

**Comment by roelvanmeer** [comment]
Same result with v0.13.0rc0.

**Comment by LegendreM** [comment]
Hello @Bajix @roelvanmeer, thank you for your issue,
we are currently implementing a new core engine which shouldn't have this bug,

but, to be able to investigate, could you provide us some logs ?

**Comment by roelvanmeer** [comment]
@LegendreM Our setup is running in a Docker container. If you can let me know what I should do to get logs that are useful to you, I'm happy to try and make that happen.

**Comment by LegendreM** [comment]
@roelvanmeer could you run meilisearch with [--env=development](https://docs.meilisearch.com/guides/advanced_guides/configuration.html#options) please ?

**Comment by roelvanmeer** [comment]
Here's the log. I'm unsure if it's any use, though. Meilisearch works, and then just stops. There are no additional messages in the log when this happens, but the request hangs. Using strace on the meilisearch process shows it is waiting for epoll_pwait() to finish. If I can provide you with anything else, please let me know, thanks!

[meilisearch.log](https://github.com/meilisearch/MeiliSearch/files/5034593/meilisearch.log)

**Comment by JayDijkstra** [comment]
@LegendreM Hello LegendreM, same as what @roelvanmeer mentioned, my Meilisearch also hangs when trying to build search indexes within a Jenkins docker container. You already mentioned that there will be a renewed core engine, which will resolve this bug (which is awesome!) 

In the meantime .. Is there something which we can be do to tackle this "hanging" issue (provide more logs, information of installed packages etc.).

Kind regards!

**Comment by Kerollmops** [comment]
Hello @JayDijkstra, @roelvanmeer we would to have more information on what you were doing before the engine "hang".

Were you deleting, creating and adding documents to the engine as fast as possible?
I think that there likely is a problem with some mutexes internally, but I am not sure, it is hard to debug and would be could to have a repro.

Thank you for your help!

**Comment by roelvanmeer** [comment]
Hi @Kerollmops , we're running this as part of our CI tests. This is at a point where we take our test database and add a document to the index for every object in the database. These are at most a couple of hundred records. It's easy to reproduce inside the CI but I didn't yet manage to get one outside of the CI suite.

I can report that it doesn't matter whether we use the meilisearch/getmeili Docker container, or whether we use a standard buster container where we install the meilisearch deb. Same results for both.

Maybe @Bajix can help out, since it was his issue that we've apparently hijacked? :)

**Comment by Kerollmops** [comment]
Hi @roelvanmeer, are you able to do queries on the engine? For example doing some simple search;

**Comment by roelvanmeer** [comment]
@Kerollmops Usually yes - until it locks up. After that, any connection to meilisearch just hangs and sits there, waiting. Are you helped by a section of strace output of the meilisearch process when that happens?

**Comment by Kerollmops** [comment]
Ok, thank you,

So I would just say that it means that the MeiliSearch server has just been killed by being out of memory while indexing.

Until you prove to mean that the search engine is still up and running by maybe calling the `/health` route I would say that the engine has simply been killed.

This would also explain that you are unable to trigger this bug on your machine, just have more memory on your machine than on your docker machine.

**Comment by roelvanmeer** [comment]
@Kerollmops No, the process hasn't been killed. It is still running. It seems there's a deadlock somewhere.

I noticed something very unusual though. If, while in this hanging state, I do a request to the server, I can do three requests succesfully, and the fourth one hangs.

So three times I get:

    root@360ccfc92b95:/# curl -i http://meilisearch:7700/health
    HTTP/1.1 200 OK
    content-length: 0
    date: Tue, 01 Sep 2020 07:51:22 GMT

And the fourth time I get nothing, the curl command is just waiting, and I have to abort with Ctrl-C:

    root@360ccfc92b95:/# curl -i http://meilisearch:7700/health
    ^C

It doesn't matter whether I call the /health or the /search route, the effect is the same. I thought this may have had to do with the fact that our docker host has 4 CPU's, but this also happens when I run it with a single CPU.

I've attached strace output of the meilisearch process while doing this: [meilisearch-strace.txt](https://github.com/meilisearch/MeiliSearch/files/5154712/meilisearch-strace.txt)

**Comment by ssankko** [comment]
Hey!
Just landing in with similar issue.
We have a docker container with `getmeili/meilisearch` image. Pushing multiple documents in quick succession causes engine to hang up indefinitely.
Im sure there are enough memory to operate with. At least when i check process with `top` it shows meilisearch currently uses ~25% of available mem. Cpu is not used at all.
In a whole there are a lot of similar symptoms with deadlocking, as someone already mentioned above.

Im using 0.20.0 version currently, meilisearch running in production enviroment.
Is there any workaround at this moment, or should we wait for new engine mid summer to test?

**Comment by curquiza** [comment]
Hello @ssankko we are working currently on a new search engine that will be release in the next release (v.0.21.0). We would like to fix this kind of issue if possible, would you please send us your dataset + your script so that we can reproduce the bug and fix it? It would be really helpful

**Comment by ssankko** [comment]
Hello @curquiza!
I'm sorry, I can't provide a dataset for a reason. We were testing different search engines to replace our dependency on Algolia. So far we used our production dataset which is private.

Though, we conducted some extensive testing to find the cause. Looks like the engine works alright (without deadlocks) if you don't create an index while another one is being created. Basically, if meilisearch is indexing documents, we can't create another index, or system will block itself.
This is very unfortunate tbh, so I’m looking forward to see what kind of a technical miracle the new engine will become with the next release.

Also, to further aid the investigation, I'll add some details about a machine we are running meilisearch on. 
We are using the Compute Engine by Google Cloud. Machine is categorized by Google as `n1-standard-2` with 2 vCPUs and 7.5 Gb of RAM. Machine is running Container Optimized OS with meilisearch image from Docker Hub. As for storage, there is one persistent hard drive with 100 Gb capacity. It's not a SSD, just the "Standard" one Google provides.

**Comment by curquiza** [comment]
Thanks for sharing this! 
We will do our best so that the new search engine can fix it!
One a RC is out, I will share it here so that everyone who got the issue can test it

**Comment by Tarpsvo** [comment]
Exactly the same issue here and exactly the same setup as @ssankko  - MeiliSearch running in Google Cloud. Just impossible to create a new index without the MeiliSearch process killing itself.

**Comment by curquiza** [comment]
Hello @Tarpsvo, @ssankko, @roelvanmeer, @JayDijkstra, @Bajix and everyone following the issue!

The [first RC of MeiliSearch v0.21.0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.21.0rc0) is out.
We did our best to fix indexation and crash issues. We succeeded to improve it, but not to totally fix them.

You can test this new release by downloading the binaries available in this release.
Or you can use it with docker:

```bash
docker run -p 7700:7700 getmeili/meilisearch:v0.21.0rc0 ./meilisearch
```

We will still improve this after the release of the v0.21.0. We would rather release a non-completely optimized version rather than delay it and, at the same time, delay the release of new features. Be sure we are doing our best to always improve these indexation issues.

As a reminder:
* despite the improvements, we always recommend pushing your documents to MeiliSearch by batch and not one by one. The maximum payload size of MeiliSearch is 100Mb and [can be optionally increased](https://docs.meilisearch.com/reference/features/configuration.html#payload-limit-size). It means most of the dataset can be pushed with one call to the API.
* If you still have a memory crash, it means the RAM of your machine might not be adapted to your dataset size. We recommend increasing the RAM of your machine.

Thanks for your patience and your help with this! ❤️

**Comment by curquiza** [comment]
Hello everyone reading this issue.

I close this issue due to the lack of feedback since it was happening with an old version of Meilisearch.

However, for anyone having issues in general with indexation performance, like this issue, please, refer to [this discussion](https://github.com/meilisearch/meilisearch/discussions/2131). Your feedback will be really appreciated 🙂
