### ISSUE TITLE
Max indexes?

### ISSUE THREAD

**Issue by adammeyer** [meilisearch/MeiliSearch#881]
**Describe the bug**
Getting this error when I try to create a new index `MDB_DBS_FULL: Environment maxdbs limit reached"`

**To Reproduce**
Create more than 300 indexes.

The total database size is only 15mb, so this isn't a size issue.  Is this a bug or is there a limit setting somewhere?  Can't find anything in docs.

**Comment by LegendreM** [comment]
Hello @adammeyer thanks for your issue, 
you should be able to create up to `3000` indices, it's an hardcoded limitation in meilisearch.
* if you are not able to create up to `3000` indices it may be a bug (and we will investigate further)
* if you are able to create up to `3000` indices but want to be able to choose this limit we could add an env var to edit it

[here](https://github.com/meilisearch/MeiliSearch/blob/v0.12.0/meilisearch-core/src/database.rs#L165-L179) seems to be the hardcoded value

[here](https://github.com/meilisearch/MeiliSearch/blob/v0.12.0/meilisearch-http/src/option.rs#L40-L46) is the struct which manage env var

**Comment by adammeyer** [comment]
I can only create around 330, it's not an exact number, sometimes it's 333.  I've tried a few different times with clean databases and things start to fail around 330.

I can re-do my schema to use just one index.  My issue was I need to be able to get all docs filtered by the "account" attribute, without a query (q).  The only way I could come up with was to create separate indexes for each account, since searching with an empty query and just a filter fails.

**Comment by LegendreM** [comment]
Is [facet filters](https://docs.meilisearch.com/guides/advanced_guides/search_parameters.html#facet-filters) could fit your need ?

searching without a query (q) will be soon possible in meilisearch `v0.13.0` which is in [pre-release](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.13.0rc0) ✨

**Comment by adammeyer** [comment]
Yes, I'm using facet filters, but a (q) is still required.  Looking forward to v13, thanks!

**Comment by lming** [comment]
@LegendreM - thanks for building this great piece of search engine! We plan to use Meili for a SAAS product in which we prefer to create one index for each user's data, and each index contains relatively small set of data. Do you think we may hit any wall if we change the max db count to 1 million? Thanks!

**Comment by LegendreM** [comment]
Hey @adammeyer @lming,
meilisearch is based on LMDB to store indexes and 1 index use several LMDB DBs. this explain why limit is around 300 indexes.
To manage LMDB we use Heed environments and for each environment we have a limit of 3000 LMDB DBs. Today we have 1 environment for all indexes,  but we are currently reimplementing our core engine which will have 1 env for each index and so the limit will be dropped.

@lming I think you should use facet filters instead of creating an new index for each user (if you want to share the same instance between several end users), but if you want to change the limit feel free to Fork our repository, If you want to know more about LMDB limits read more on http://www.lmdb.tech/doc/group__mdb.html#gaa2fc2f1f37cb1115e733b62cab2fcdbc

@adammeyer meilisearch [v0.13.0 is released](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.13.0) ✨
