### ISSUE TITLE
CentOS 7 - MeiliSearch uses only 1 core

### ISSUE THREAD

**Issue by thebitbrine** [meilisearch/MeiliSearch#932]
**Describe the bug**
I'm trying to add more than 5,000,000 documents to MeiliSearch but it indexes so slowly and it only uses 1 out of 64 cores available. Each document has around 10,000 chars.

**To Reproduce**
1. Add more than 100,000 documents
2. ???

**Expected behavior**
It should utilize all 64 core or at least more than one core to speed up the indexing process.

**Additional context**
I'm not sure it MeiliSearch has multi-core support but it is an amazing search engine and definitely would make it even better.

**Specs***
OS: CentOS 7 3.10.0-1127.el7.x86_64
CPU: 64 vCores @ 2.8 Ghz
RAM: 256GB

**Comment by Kerollmops** [comment]
Hi @thebitbrine,

This is a known issue that I already fixed in [the futur version of the engine](https://twitter.com/Kerollmops/status/1291808680934019073?s=20), it is able to use the 32 cores of the machine to index more than half a billion document in _only_ 2h.

The only advice I can give to you is to send a little bit more documents in your batches (by maybe increasing the max-request-size param), but be carreful as the engine will use more memory too! The OOM issue as also been addressed in the new engine.

Thank you for the kind words too :)
