### ISSUE TITLE
Some Settings seem to be overwritten when documents are pushed after updating settings

### ISSUE THREAD

**Issue by LegendreM** [meilisearch/MeiliSearch#942]
**Describe the bug**
Some settings seem to be overwritten when documents are pushed after updating settings:
- `searchableAttributes`
- `displayedAttributes`

**To Reproduce**
I made a test on this branch:
https://github.com/LegendreM/MeiliSearch/commit/2d109cabbc798003f705a1f02d03ba0e6973f22e

**Expected behavior**
`searchableAttributes` and `displayedAttributes`should be unchanged.

**Additional context**
related to #891

**Comment by MarinPostma** [comment]
While fixing this bug, I have encountered a problem with `update_documents_with_facet_distribution`. This test checks that documents that are updated correctly when using facet distribution. It configures meilisearch with the following settings: 
```json
{
        "attributesForFaceting": ["genre"],
        "displayedAttributes": ["genre"],
        "searchableAttributes": ["genre"]
}
```

with the current settings behaviour, the values for `displayedAttribures` and `searchableAttributes` are not overriden when new attributes are found in a document. This means that with the current (fixed the upcoming pr), this search returns an empty result:

```json
{
        "q": "album",
        "facetsDistribution": ["genre"]
}
```
on these documents:
```json
[
        {
            "id": "1",
            "type": "album",
            "title": "Nevermind",
            "genre": ["grunge", "alternative"]
        },
        {
            "id": "2",
            "type": "album",
            "title": "Mellon Collie and the Infinite Sadness",
            "genre": ["alternative", "rock"]
        },
        {
            "id": "3",
            "type": "album",
            "title": "The Queen Is Dead",
            "genre": ["indie", "rock"]
        }
    ]
```

This is expected because `type` is not set as a `SearchableAttribute`. The obvious way to fix the test is to add `"type"` to the searchable attributes.

Now if we **update** the documents with `id` 3 to the following:
```json
{
            "id": "3",
            "title": "The Queen Is Very Dead"
        }
```
The expected behaviour is that the title for this document is updated, and pevious search query on the updated document set should return the same results as before (with the `"type"` fixed).

What acutally happens is that the when the document is updated, the old documents id fetched and dereseialized from the store [here](https://github.com/meilisearch/MeiliSearch/blob/master/meilisearch-core/src/update/documents_addition.rs#L194-L202), and new values are updated. The problem comes from the fact that the deserialization only returns the displayed attributes, (which "title" and "type" are not part of).

We'd expect the indexed keys to be part of this document so we can properly update it, which is not the case.

@LegendreM @Kerollmops we should re-think the way we deserialize the documents.
